### ISSUE TITLE
What are some good ways to handle dynamic refresh permissions in "security"

### ISSUE THREAD

**Issue by feyounger** [spring-projects/spring-security#10043]
What are some good ways to handle dynamic refresh permissions in "security"?
Sometimes there is a need to dynamically update the permissions of certain roles or people. When the current online user has this role or has this permissions, he or she needs to dynamically change the permissions he or she has without quitting the system.

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
