### ISSUE TITLE
Is there a way to check WebSession is expired for a current logged in session

### ISSUE THREAD

**Issue by rishisc** [spring-projects/spring-security#10152]
I tried using WebFilter and GlobalFilter in SCG but no where it was able to check isExpired Flag

Add a webFilter ordered after Authorization or First in WebFlux spring boot application subscribe to exchange.getSession() WebSession object.
OR
Add a Global Filter ordered -1 using exchange.getSession() WebSession Object using map check isExpired Flag.

Is there a different way to check isExpired flag for WebSession in WebFlux spring boot application

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
