### ISSUE TITLE
Principal claim name in JwtAuthenticationConverter is null but documented default

### ISSUE THREAD

**Issue by djechelon** [spring-projects/spring-security#10214]
**Describe the bug**

At [JwtAuthenticationConverter](https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationConverter.java#L39) the `principalClaimName` is null, but the setter method is documented

```
Sets the principal claim name. Defaults to {@link JwtClaimNames#SUB}.
```

**Expected fix**
Initialize by default the `principalClaimName` to `sub`, preferrably by using constant `JwtClaimNames.SUB`

**Comment by jzheaux** [comment]
Hi, @djechelon, thanks for the report.

I believe this is because [if the name is null](https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationConverter.java#L44) it uses [the `JwtAuthenticationToken` constructor](https://github.com/spring-projects/spring-security/blob/d0fbe6b5011e24015444129d1ac8e210d94d8a00/oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationToken.java#L57) that defaults to `SUB`.

That said, it would be nicer if [this logic](https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationConverter.java#L44) were simplified.

Can you submit a PR that sets the claim name to `SUB` and then also simplifies the logic to always call [the constructor that takes the claim value](https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationConverter.java#L48)?
