### ISSUE TITLE
Add `serialVersionUID`  to `DefaultSavedRequest` and `SavedCookie` 

### ISSUE THREAD

**Issue by xhh1314** [spring-projects/spring-security#10594]
**Describe the bug**
the class org.springframework.security.web.savedrequest.DefaultSavedRequest and org.springframework.security.web.savedrequest.SavedCookie had implements Serializable , but did't added serialVersionUID,  lead a deserialization exception

**To Reproduce**
use spring-session-data-redis and  SkyWalking would got exception

**Expected behavior**
please add serialVersionUID to those class

**Sample**

**Comment by marcusdacoregio** [comment]
Hi, thanks for reaching out.

The absence of the `serialVersionUID` property alone should not cause a deserialization exception, because the `serialVersionUID` is calculated based on many aspects of the class.

Can you elaborate more on your configuration? Are you upgrading from another version?

Also, if you can provide a [minimal reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example), it would be even better for us to analyze further.

**Comment by xhh1314** [comment]
> 


I am using  Spring OAuth2, Spring-Session-Data-Redis  and SkyWalking APM which is a java agent that enhances DefaultSavedRequest object

You can reference this issue: https://github.com/spring-projects/spring-security-oauth/issues/1684

Please Declare serialVersionUID on those classes

Thanks

**Comment by marcusdacoregio** [comment]
@xhh1314 are you interested in submitting a PR to fix this? One way to do this is by using `SpringSecurityCoreVersion`:

`private static final long serialVersionUID = SpringSecurityCoreVersion.SERIAL_VERSION_UID;`

**Comment by jakspok** [comment]
Hello everyone, this is the contribution mentioned in previous threads, I hope it will be useful
