### ISSUE TITLE
Manager oauth2 credentials by configuration

### ISSUE THREAD

**Issue by khamlaoui** [spring-projects/spring-security#10677]
Hello,

The current configuration for **spring-boot-starter-oauth2-client** does not allow to configure credentials by configuration.
Please find attached an example of the desired config.
[oauth2-client.txt](https://github.com/spring-projects/spring-security/files/7810155/oauth2-client.txt)

in case you think this is a good idea, i could contribute on this feature.

Regards

**Comment by jgrandja** [comment]
@khamlaoui This ticket should be logged with Spring Boot, since the properties are defined there.

However, I don't feel this new property makes sense because it would only be applicable for clients using `private_key_jwt`. Furthermore, key material may be retrieved from another type of source other than KeyStore and TrustStore, so this property would not work in those cases.

I'm going to close this as I feel this type of configuration should be applied/customized in application.
