### ISSUE TITLE
AbstractWebClientReactiveOAuth2AccessTokenResponseClient should allow to add URI parameter

### ISSUE THREAD

**Issue by muhdalavu** [spring-projects/spring-security#10838]
[AbstractWebClientReactiveOAuth2AccessTokenResponseClient ](https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/AbstractWebClientReactiveOAuth2AccessTokenResponseClient.java) Should be allowed to do URI customization.

Any `Token response client` derived from `AbstractWebClientReactiveOAuth2AccessTokenResponseClient` should be allowed to do URI customization.

### Current Behavior
No option is provided to do URL customize  to the **Token response client**.

### Context
The authorization servers with which I have been working required the URI query string parameter to get the refresh token.

**Example request**
`POST: https:/domain.com/oauth/v2/token?grant_type= refresh_token&refresh_token={current_refresh_token}`

With current `AbstractWebClientReactiveOAuth2AccessTokenResponseClient / WebClientReactiveRefreshTokenTokenResponseClient ` I do not have any option to accomplish the same.

**Possible another extension point**

`ReactiveOAuth2AuthorizedClientProviderBuilder.RefreshTokenGrantBuilder` could have accept a `ReactiveOAuth2AccessTokenResponseClient<T>` and set that in `RefreshTokenReactiveOAuth2AuthorizedClientProvider`.

[Refere code here](https://github.com/spring-projects/spring-security/blob/a99a04f0506a20c3c8b77616c6b150b24c95c264/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/ReactiveOAuth2AuthorizedClientProviderBuilder.java#L404)

_To achieve the same, please suggest to me if any workaround is available._

[Reference document link](https://docs.spring.io/spring-security/reference/reactive/oauth2/client/authorization-grants.html#_customizing_the_webclient_2)

**Comment by muhdalavu** [comment]
This may require a change in the builder class as well.

[https://github.com/spring-projects/spring-security/blob/a99a04f0506a20c3c8b77616c6b150b24c95c264/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/ReactiveOAuth2AuthorizedClientProviderBuilder.java#L349](link)

**Comment by sjohnr** [comment]
@muhdalavu, thanks for the request.

The link you provided to the documentation regarding customizing the `WebClient` details the steps necessary to customize the `RefreshTokenReactiveOAuth2AuthorizedClientProvider` with your own configured instance of `WebClientReactiveRefreshTokenTokenResponseClient`, which allows you to modify the request using an `ExchangeFilterFunction`. Further, the example in the previous section regarding the [ReactiveOAuth2AuthorizedClientManager](https://docs.spring.io/spring-security/reference/reactive/oauth2/client/core.html#oauth2Client-authorized-manager-provider) shows how to provide the configured instance as an `@Bean` to override the default. The full definition would look something like this:

```java
	@Bean
	public ReactiveOAuth2AuthorizedClientManager authorizedClientManager(
			ReactiveClientRegistrationRepository clientRegistrationRepository,
			ServerOAuth2AuthorizedClientRepository authorizedClientRepository) {

		WebClientReactiveRefreshTokenTokenResponseClient refreshTokenTokenResponseClient =
			new WebClientReactiveRefreshTokenTokenResponseClient();
		WebClient webClient = WebClient.builder()
			.filter((request, next) -> {
				// Modify the request here. For example...
				UriComponents uri = UriComponentsBuilder.fromUri(request.url())
					.queryParam("refresh_token", "...")
					.build();
				ClientRequest modifiedRequest = ClientRequest.from(request)
					.url(uri.toUri())
					.build();
				return next.exchange(modifiedRequest);
			})
			.build();
		refreshTokenTokenResponseClient.setWebClient(webClient);

		ReactiveOAuth2AuthorizedClientProvider authorizedClientProvider =
			ReactiveOAuth2AuthorizedClientProviderBuilder.builder()
				.authorizationCode()
				.refreshToken(configurer -> configurer.accessTokenResponseClient(refreshTokenTokenResponseClient))
				.build();

		DefaultReactiveOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultReactiveOAuth2AuthorizedClientManager(
				clientRegistrationRepository, authorizedClientRepository);
		authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

		return authorizedClientManager;
	}
```

Hopefully this illustrates how to achieve your desired customization allowing you to work with your existing provider(s). Since this is possible and examples are provided in the reference documentation, I'm going to close this issue for now. However, if I've misunderstood anything or you have further thoughts, you can comment on this issue to continue the conversation.
