### ISSUE TITLE
Add Kotlin example for password encoding of crypto module

### ISSUE THREAD

**Issue by talerngpong** [spring-projects/spring-security#10850]
**Describe the bug**
An example of [Password Encoding](https://docs.spring.io/spring-security/reference/features/integrations/cryptography.html#spring-security-crypto-passwordencoders) comes with only Java example under Spring Security Crypto Module.

**To Reproduce**
1. browse to Password Encoding bullet with the link above.
2. A coding block of `PasswordEncoder` interface provides only Java example. In the other word, the block comes without language toggle buttons.

**Expected behavior**
It provides both of Java and Kotlin examples.

**Sample**

Reference to [Password Encoding](https://github.com/spring-projects/spring-security/blob/5.7.x/docs/modules/ROOT/pages/features/integrations/cryptography.adoc#password-encoding) ADOC file of `5.7.x` series.

**Comment by eleftherias** [comment]
Thanks for reaching out @talerngpong.
This interface is intentionally only shown in Java because that is how it is written internally in Spring Security.

In other examples we show how to use Spring Security, however the `PasswordEncoder` interface is not an example use-case, but rather an internal Spring Security class that is written only in Java.
I believe it would be misleading to share a Kotlin equivalent, because no such class exists in the codebase.

For that reason I'm going to close this issue.
