### ISSUE TITLE
Filter chain, where there are multiple identical filters

### ISSUE THREAD

**Issue by leshalv** [spring-projects/spring-security#11035]
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/30397655/160264109-64414282-15dd-48fb-8381-3942f8f90dd9.png">

**Comment by sjohnr** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
