### ISSUE TITLE
OAuth using Salesforce is not working.

### ISSUE THREAD

**Issue by chiragasawa** [spring-projects/spring-security#11173]
I am using salesforce for the OAuth purpose and added all the properties but it not showing to option to login with salesforce.

```
spring.security.oauth2.client.registration.salesforce.provider=salesforce
spring.security.oauth2.client.registration.salesforce.authorization-grant-type=code
spring.security.oauth2.client.registration.salesforce.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.salesforce.client-id=******************
spring.security.oauth2.client.registration.salesforce.client-secret=********************
spring.security.oauth2.client.registration.salesforce.scope=id,openid,profile
spring.security.oauth2.client.registration.salesforce.redirect-uri=https://login.salesforce.com/services/oauth2/success
spring.security.oauth2.client.registration.salesforce.client-name=Salesforce



spring.security.oauth2.client.provider.salesforce.token-uri=https://login.salesforce.com/services/oauth2/token
spring.security.oauth2.client.provider.salesforce.authorization-uri==https://login.salesforce.com/services/oauth2/authorize
spring.security.oauth2.client.provider.salesforce.issuer-uri=https://login.salesforce.com
spring.security.oauth2.client.provider.salesforce.user-info-uri=https://login.salesforce.com/services/oauth2/userinfo
spring.security.oauth2.client.provider.salesforce.user-name-attribute=sub
```

but this is not working no error is showing in console. Also a blank login screen is showing.

![image](https://user-images.githubusercontent.com/43067874/165581021-3c19d5ae-87f3-4bd5-ad1e-50b507d0fa38.png)

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
