### ISSUE TITLE
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the header value "??448s84c36e2" is not allowed.

### ISSUE THREAD

**Issue by yangdong6** [spring-projects/spring-security#11269]
An error is reported when Chinese attributes are set in the request header.
In the StrictHttpFirewall class, when the validateAllowedHeaderValue method is invoked, the value in the header is verified. If the value that contains Chinese characters is added to the header, the verification fails.

**Comment by sjohnr** [comment]
Hi @yangdong6, what version of Spring Security are you using?

**Comment by yangdong6** [comment]
I use versions 5.6.3 and 5.6.5.

**Comment by sjohnr** [comment]
Thanks @yangdong6. This seems to have been an issue for some time, whether it is expected behavior or a bug. Take a look at [HttpFirewall](https://docs.spring.io/spring-security/reference/servlet/exploits/firewall.html) in the reference docs. You may be interested in:

> StrictHttpFirewall also checks header names and values and parameter names. It requires that each character have a defined code point and not be a control character.

It goes on to state that you can adjust this behavior. For example, you can use `StrictHttpFirewall#setAllowedHeaderValues(Predicate)` to allow Chinese characters that are normally blocked. (I'm not sure how recommended that is, but if it's an issue for you it may be a valid workaround in your situation.)

It may be a few days before we can look into this issue deeper. Does this workaround move you past this issue in the meantime?

**Comment by yangdong6** [comment]
thanks very mush. Your suggestion is very useful. But I don't know how to use the bean annotation.

@Bean
    public StrictHttpFirewall httpFirewall() {
        StrictHttpFirewall firewall = new StrictHttpFirewall();
        firewall.setAllowedHeaderNames((header) -> true);
        firewall.setAllowedHeaderValues((header) -> true);
        firewall.setAllowedParameterNames((parameter) -> true);
        return firewall;
    }

**Comment by sjohnr** [comment]
You can place it in a class annotated with `@Configuration`, like this:

```java
@Configuration
public class FirewallConfiguration {
    @Bean
    public StrictHttpFirewall httpFirewall() {
        StrictHttpFirewall firewall = new StrictHttpFirewall();
        firewall.setAllowedHeaderNames((header) -> true);
        firewall.setAllowedHeaderValues((header) -> true);
        firewall.setAllowedParameterNames((parameter) -> true);
        return firewall;
    }
}
```

**Comment by rwinch** [comment]
@yangdong6 Please also provide a sample that reproduces the problem.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
