### ISSUE TITLE
Does not execute the initFilterBean method of the GenericFilterBean parent class.

### ISSUE THREAD

**Issue by asanera** [spring-projects/spring-security#11345]
**Describe the bug**
Do not execute the initFilterBean method when a filter is defined within the SecurityFilterChain bean definition.
![image](https://user-images.githubusercontent.com/22320522/172367963-486d39b8-998e-42f2-b6d1-c4e8d26ef6d8.png)
![image](https://user-images.githubusercontent.com/22320522/172367995-0d6b89c7-ed1c-4203-9298-a885fbe216c9.png)

Spring-boot-parent 2.7.0
Spring-security-web 3.3.10 RELEASE.
![image](https://user-images.githubusercontent.com/22320522/172367898-ce6f47df-56e0-490e-888f-1180d3c1f577.png)

**Comment by rwinch** [comment]
Spring Security does not invoke any lifecycle methods on objects that are instantiated outside of it's DSL as it is not aware if the methods have already been invoked.

The method `initFilterBean` is only used for a `Filter` registered directly with the servlet container and unnecessary for cases where you are initializing it in Spring. Rather than initializing `uidRestClient` in the `initFilterBean` method, I'd suggest injecting the uidRestClient into the `AuthorizationFilter` instead. For example:

```java
@Bean
DefaultSecurityFilterChain springSecurity(HttpSecurity http, UIDMicroRestClient uidRestClient) throws Exception {
	http
		.addFilterAfter(new AuthorizationFilter(uidRestClient), BasicAuthenticationFilter.class)
		...
	return http.build();
}

@Bean
UIDMicroRestClient uidRestClient(Environment env) {
       return new UIDMicroRestClient(...);
}
```

**Comment by asanera** [comment]
Thank you very much! Sorry for the inconvenience.
