### ISSUE TITLE
ConcurrentModificationException in Spring Security header writing during async requests with MockMvc

### ISSUE THREAD

**Issue by EagerSloth** [spring-projects/spring-security#11452]
An issue similar to spring-projects/spring-framework#23460 exists in current spring versions, encountered using both spring boot 2.6.6 and 2.7.1.

My use case:

- some application URLs are secured with spring security via BASIC authentication 
- controller is performing asynchronous request handling 
- a parametrized test is checking endpoint behaviour for multiple input values (simplified to `@RepeatedTest` for this report) via `MockMvc`

I assume the issue is not really caused by Spring Security, but I was not able to reproduce the behavior with a custom filter adding (multiple) headers.

Example project including test showing error behavior:
https://github.com/EagerSloth/spring-framework

**Comment by rwinch** [comment]
Thanks for the report @EagerSloth I'm closing as duplicate of gh-9175

**Comment by EagerSloth** [comment]
Thanks a lot for looking into this. As this is a duplicate of a two year old known issue, is there any known workaround but skipping spring-security setup during my specific test case?

**Comment by rwinch** [comment]
You can configure Spring Security to write the headers eagerly using something like:

```java
http
					.headers()
					.addObjectPostProcessor(new ObjectPostProcessor<HeaderWriterFilter>() {
						@Override
						public HeaderWriterFilter postProcess(HeaderWriterFilter filter) {
							filter.setShouldWriteHeadersEagerly(true);
							return filter;
						}
					});
```

This has the disadvantage of writing cache control headers for every response vs only responses that have no cache control headers.

**Comment by 2is10** [comment]
My team has seen sporadic test failures for all async endpoints that use `StreamingResponseBody` or, more generally, any async endpoints that use the `WebAsyncManager.startCallableProcessing` code path. All of these failures are due to `ConcurrentModificationException` in Spring Security’s `HeaderWriterFilter.writeHeaders`.  Some occur in the original dispatch thread, while unwinding the filter chain; the rest occur in the async dispatch thread when our code begins writing to the response.

The crux of the problem seems to be that `OnCommittedResponseWrapper` is used in multiple threads, but isn’t thread-safe. One simple solution would be to make it thread-safe. Its `boolean disableOnCommitted` field that’s used here:
```java
    private void doOnResponseCommitted() {
        if (!this.disableOnCommitted) {
            onResponseCommitted();
            disableOnResponseCommitted();
        }
    }
```
…could be changed to `final AtomicBoolean` and used thus:
```java
    private void doOnResponseCommitted() {
        if (!this.disableOnCommitted.getAndSet(true)) {
            onResponseCommitted();
        }
    }
```
An even simpler solution would be for `HeaderWriterFilter` to stop trying to write to the response from two different threads. Application code normally commits any given HTTP response from exactly one thread. If `HeaderWriterFilter` just let `OnCommittedResponseWrapper` do its thing, there would be no race condition. I think the simplest fix would be simply deleting the `finally` block below:
```java
    try {
        filterChain.doFilter(headerWriterRequest, headerWriterResponse);
    }
    finally {
        headerWriterResponse.writeHeaders();
    }
```
Any reason not to?

For the time being, the workaround I’ve adopted is adding a `response.flushBuffer();` call just before the `return` statement in each affected async endpoint. That call commits the response synchronously in the main dispatch thread before async processing begins—before the race condition can develop.

**Comment by oleg-astakhov** [comment]
> Thanks a lot for looking into this. As this is a duplicate of a two year old known issue, is there any known workaround but skipping spring-security setup during my specific test case?
> 
> The whole explanation above also make me realize that another odd, very rare Exception we are observing in production most likely has the same root cause:
> 
> `java.lang.NullPointerException: Cannot invoke "org.apache.tomcat.util.http.MimeHeaderField.getName()" because "this.headers[i]" is null org.apache.tomcat.util.http.MimeHeaders.setValue(MimeHeaders.java:317) 


Another one with the same issue here. Getting the exception sporadically from controllers which return `ResponseEntity<StreamingResponseBody>`. And yes I'm writing Cache-Control headers. (Exception example at the end of the post).

My setup is Spring Boot: 3.2.3 with embedded Tomcat.

I recently migrated from Spring Boot 2 + Jetty, and I have never seen this exception before migration. It only started with SB3 + Tomcat. But the exception source is clearly Tomcat in my case. I can see that this issue persists for a long time already, and even though it happens once in 2-3 days, it gets me alerted every time. 

Does anybody experience the same issue with Jetty (and SpringBoot 3) ?

Also, I don't know if this is connected, but I've recently noticed that images were loading slower. I checked CDN statuses and was surprised to see `BYPASS` statuses. My `ResponseEntity<StreamingResponseBody>` image controllers were setting `Cache-Control: public` headers, but for some reason, there was a 2nd pair of `Cache-Control` header with a `private` value. Of course, `private` is what was causing `BYPASS` and slow loading. When I debugged the app, my code was not setting `private` anywhere, it was added somewhere implicitly. So the way I fixed it, is by how I add this header. 

Previously I did it as follows: 
```
final HttpHeaders headers = new org.springframework.http.HttpHeaders();
headers.setCacheControl(<my public value>);
...
return new ResponseEntity<>(stream, headers, HttpStatus.OK);
```

But now directly on instance of `HttpServletResponse`: 
```
response.setHeader("Cache-Control", "<my public value>");
```
and the problem with CDN is solved.
I still use `HttpHeaders ` instance for other headers, but `Cache-Control` I set explicitly on the `HttpServletResponse` instance.

So, I wonder, what happens if I set all headers directly on the `HttpServletResponse` and not via `org.springframework.http.HttpHeaders`...

Here's the relevant part of the stacktrace:

```
java.lang.NullPointerException: Cannot invoke "org.apache.tomcat.util.http.MimeHeaderField.getName()" because "this.headers[i]" is null
	at org.apache.tomcat.util.http.MimeHeaders.getValue(MimeHeaders.java:322)
	at org.apache.tomcat.util.http.MimeHeaders.getHeader(MimeHeaders.java:354)
	at org.apache.coyote.Response.containsHeader(Response.java:365)
	at org.apache.catalina.connector.Response.containsHeader(Response.java:1082)
	at org.apache.catalina.connector.ResponseFacade.containsHeader(ResponseFacade.java:309)
	at jakarta.servlet.http.HttpServletResponseWrapper.containsHeader(HttpServletResponseWrapper.java:65)
	at jakarta.servlet.http.HttpServletResponseWrapper.containsHeader(HttpServletResponseWrapper.java:65)
	at org.springframework.security.web.header.writers.HstsHeaderWriter.writeHeaders(HstsHeaderWriter.java:156)
	at org.springframework.security.web.header.HeaderWriterFilter.writeHeaders(HeaderWriterFilter.java:99)
	at org.springframework.security.web.header.HeaderWriterFilter$HeaderWriterResponse.writeHeaders(HeaderWriterFilter.java:132)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:93)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
```

**Comment by FoKas90** [comment]
I faced same problem as @oleg-astakhov mentioned. I've upgraded sb2 -> sb3 and my controller method returning ResponseEntity<StreamingResponseBody> become occasionally fall with same Exception
