### ISSUE TITLE
OpenSaml4AuthenticationRequestResolver method resolve

### ISSUE THREAD

**Issue by tundoMatteo** [spring-projects/spring-security#11659]
In spring-security-saml2-service-provider 5.7.2. the class OpenSaml4AuthenticationRequestResolver has this method:

`
@Override
	public <T extends AbstractSaml2AuthenticationRequest> T resolve(HttpServletRequest request) {
		return this.authnRequestResolver.resolve(request, (registration, authnRequest) -> {
			authnRequest.setIssueInstant(Instant.now(this.clock));
			this.contextConsumer.accept(new AuthnRequestContext(request, registration, authnRequest));
		});
	}
`

the method authnRequest.setIssueInstant(); requires a DateTime not an Instant.

The result is a 

java.lang.NoSuchMethodError: org.opensaml.saml.saml2.core.AuthnRequest.setIssueInstant(Ljava/time/Instant;) at org.springframework.security.saml2.provider.service.web.authentication.OpenSaml4AuthenticationRequestResolver.lambda$resolve$1OpenSaml4AuthenticationRequestResolver.java:58)

Could you please check the issue?

**Comment by marcusdacoregio** [comment]
Hi @tundoMatteo, this is a duplicate of https://github.com/spring-projects/spring-security/issues/10547.

I'll close this but feel free to reach out if you need any further help.

**Comment by tundoMatteo** [comment]
@marcusdacoregio so the solution is to update OpenSaml to version 4.1.0? But spring brings with it the version 3.4.6 and the problem is not concerned with the logout, since i was trying to change the nameIdPolicy of the Saml Request.

**Comment by marcusdacoregio** [comment]
Yes, Spring Security SAML Service Provider has the OpenSAML version 3.4.6 in it because we support OpenSaml3 (which will be removed in Spring Security 6, see #10556).

Since you are using `OpenSaml4AuthenticationRequestResolver` you have to use OpenSAML4, [see here](https://github.com/spring-projects/spring-security-samples/blob/1fc20d346e4c5d486b3283087df3c88d21e77313/servlet/spring-boot/java/saml2/login/build.gradle#L16-L20) how to configure it using Gradle. The OpenSAML team does not publish their newest [versions in Maven Central](https://shibboleth.atlassian.net/wiki/spaces/DEV/pages/1123844333/Use+of+Maven+Central), so you have to [add their own repository](https://github.com/spring-projects/spring-security-samples/blob/1fc20d346e4c5d486b3283087df3c88d21e77313/servlet/spring-boot/java/saml2/login/build.gradle#L12) to your build file.

**Comment by tundoMatteo** [comment]
@marcusdacoregio ok thank you but it would be useful to update the guide [here](https://docs.spring.io/spring-security/reference/servlet/saml2/login/authentication-requests.html) where there is this snippet of code:

`@Bean
Saml2AuthenticationRequestResolver authenticationRequestResolver(RelyingPartyRegistrationRepository registrations) {
    RelyingPartyRegistrationResolver registrationResolver =
            new DefaultRelyingPartyRegistrationResolver(registrations);
    OpenSaml4AuthenticationRequestResolver authenticationRequestResolver =
            new OpenSaml4AuthenticationRequestResolver(registrationResolver);
    authenticationRequestResolver.setAuthnRequestCustomizer((context) -> context
            .getAuthnRequest().setForceAuthn(true));
    return authenticationRequestResolver;
}`

Here it shows to use the OpenSaml4AuthenticationRequestResolver,  but it will not work if i don't force the import of open saml 4 in the pom.
