### ISSUE TITLE
Multiple SecurityFilterChain Beans with Basic Auth and Oauth support

### ISSUE THREAD

**Issue by sohamindellient** [spring-projects/spring-security#11689]
**Describe the bug**
I am migrating from `WebSecurityConfigurerAdapter `to use `SecurityFilterChain `bean. In my current implementation I have an ability to support both Basic authentication as well as Oauth2ResourceServerAuthentication. (using the WebSecurityConfigurerAdapter and having 2 different configuration files). But with the bean I can only support either of the two types of authentication. Is there a way to support both.

**Comment by jzheaux** [comment]
@sohamindellient, I'm not really clear on where the limitation is. `SecurityFilterChain` can have both the basic auth filter as well as the resource server filter.

It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
