### ISSUE TITLE
HttpSessionRequestCache.matchingRequestParameterName = continue

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#11757]

**Comment by daixixidai** [comment]
> _No description provided._
Hello,I found an error or problem when I used newest Spring Security（6.0.0）. 
For example，when I request for an Api http://localhost:8080/a ，I’m not authenticated，so I'm forced to Login。
Then I can see the request response after I log in the system,but the request url change to http://localhost:8080/a?continue，this performance looks like misleading because I never input continue。
When I leave for a moment，I refresh the page ,I will get a URL http://localhost:8080/a?continue&continue。

Another continue，so I think mybe add “continue” suffix to the cached url can resolve some problems，but we can get url with no “continue”  when retrived the cached url。
