### ISSUE TITLE
Multiple @Bean public SecurityFilterChain samlFilterChain(HttpSecurity http)

### ISSUE THREAD

**Issue by babita-verma** [spring-projects/spring-security#11820]
I want to create a fallback security chain that means it will authorize all the request but i want to register it last .
I added @order on top of Beans But its seems it not working . How can we make sure that it registers at the end when all the matchers are registered 

Is there a concrete way to do this ? To put a ordering in the these Security Filter Chain

**Comment by babita-verma** [comment]
Is there a better way to reorganize, instead of using @DependsOn and few other conditions

**Comment by sjohnr** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
