### ISSUE TITLE
MappedJwtClaimSetConverter make converters accessible

### ISSUE THREAD

**Issue by buksvdl** [spring-projects/spring-security#11914]
I have token claims to explicitly convert at this point, but in stead of implementing my own converters i would like to use existing converters. All accessors are private.

`Converter<Map<String, Object>, Map<String, Object>> claimSetConverter =
            MappedJwtClaimSetConverter.withDefaults(
                Map.of("myClaim", MappedJwtClaimSetConverter::convertInstant));`

**Comment by sjohnr** [comment]
Hi @buksvdl, thanks for reaching out!

The `MappedJwtClaimSetConverter.convertInstant` method simply uses the `ClaimConversionService` which you can access via `ClaimConversionService.getSharedInstance()`. I don't believe it makes sense to make methods like `convertInstant` public, since it is implemented specifically for the claims in `MappedJwtClaimSetConverter` and you can easily implement your own using the `ClaimConversionService`.

I'm going to close this for now, but if you have any questions about using the `ClaimConversionService` for your use case, feel free to open a stackoverflow question and link it here (so that others can find it), and I'll be happy to take a look.
