### ISSUE TITLE
OAuth2AuthorizedClientRepository  There is a circular dependency problem

### ISSUE THREAD

**Issue by imaxun** [spring-projects/spring-security#11974]
![image](https://user-images.githubusercontent.com/29112991/194687876-4721e4d5-85a9-416a-bdf8-433e3b13b360.png)
![image](https://user-images.githubusercontent.com/29112991/194687886-24760136-2450-4d45-acf0-f4f208bbcfff.png)

**Comment by imaxun** [comment]
spring boot version 2.6.10
spring security version  5.6.6
spring-security-oauth2-authorization-server version  0.3.1

**Comment by marcusdacoregio** [comment]
Hello @imaxun, thanks for getting in touch.
It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [Getting Support](https://github.com/spring-projects/spring-security#getting-support), questions should be submitted to StackOverflow. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
