### ISSUE TITLE
Instrument (Reactive)AuthorizationManager

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#11990]

**Comment by Shabin** [comment]
When moving from spring 5 to 6 for one of our legacy applications, the change in [HttpSecurityBeanDefinitionParser.java](https://github.com/spring-projects/spring-security/commit/8c610684f3f6b25d05b9b28d7f6c640e05bc327c#diff-4463dd70adb0df73ca02a5778c4f2f672d09052ffc6bfde84b21362c4ae7e0bc) which added a ChildAuthenticationManagerFactoryBean factory bean messed up the bean creation order of the application. Since this is a factory bean, it got eagerly initialized during a bean postprocessor creation and hence our xml based http security userdetails service bean also got initialized before autowiring postprocessor was created and hence the autowired beans inside in our userdetails resulted in null. It will be very difficult for us to change the bean ordering since it a complicated legacy application. Any option to fall back to the original ProviderManager based security initialization if observability is not required?

**Comment by nucleussoftwareopen** [comment]
@jzheaux , I am facing the same problem as mentioned by @Shabin.
