### ISSUE TITLE
only first SecurityFilterChain is processed

### ISSUE THREAD

**Issue by rrittwag** [spring-projects/spring-security#12079]
**Describe the bug**
If a config contains multiple SecurityFilterChain definitions, only the first definition is processes, all others are ignored.

concerns Spring Security 6 RC1 / Spring Boot 3 RC1

**To Reproduce**
- define 2 endpoints
- define 1 SecurityFilterChain per endpoint, permitting access without authentication/authorization
- try to access both endpoints

**Expected behavior**
both endpoints are accessible

**Sample**
[minimal, reproducible sample](https://github.com/rrittwag/spring-multi-filterchain).

**Comment by marcusdacoregio** [comment]
Hello @rrittwag.

As stated [in the docs](https://docs.spring.io/spring-security/reference/servlet/architecture.html#servlet-multi-securityfilterchain-figure), "Only the first SecurityFilterChain that matches will be invoked". That said, because you didn't specified an `http.securityMatcher(...)`, that `SecurityFilterChain` will match to every request, see [the docs](https://docs.spring.io/spring-security/reference/6.0.0-RC1/servlet/configuration/java.html#_multiple_httpsecurity_instances).

I've submitted a PR to your sample to show you how to fix that https://github.com/rrittwag/spring-multi-filterchain/pull/1
