### ISSUE TITLE
Incompatble with reactor release 2022.0.0 - removed Mono.subscriberContext()

### ISSUE THREAD

**Issue by 5V715** [spring-projects/spring-security#12214]
**Describe the bug**

effects up to spring-security 5.7.5

The latest release of project reactor https://mvnrepository.com/artifact/io.projectreactor/reactor-bom/2022.0.0
which updates reactor-core to 3.5.0 has removed some methods
https://projectreactor.io/docs/core/3.4.0-RC2/api/deprecated-list.html

e.g. `reactor.core.publisher.Mono reactor.core.publisher.Mono.subscriberContext()` is used in
´ServerOAuth2AuthorizedClientExchangeFilterFunction´ which at runtime can no longer be instantiated 

**To Reproduce**
update reactor, run app that uses `spring-security-oauth2-client-5.7.5.jar` with `org.springframework.boot:spring-boot-starter-oauth2-client`

**Expected behavior**
should still work

**Comment by marcusdacoregio** [comment]
Hi @5V715, thanks for the report.

Spring Security 5.7.5 is using `io.projectreactor:reactor-bom:2020.0.24`, notice that this is not the same major version you are mentioning (2022). We do not update dependencies to a new major/minor version during patch releases because it might be a breaking change, therefore it is not expected that Spring Security 5.7.x works with a greater version of reactor-bom than `2020.0.x`.

However, you might want to try Spring Security 6 which uses reactor-bom 2022.0.0 and will be released on Nov 21st.
