### ISSUE TITLE
`AuthorizationFilter` behaves different from `FilterSecurityInterceptor` for requests without bearer token

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-security#12278]
I'm observing this with Spring Boot 2.7.5 (Spring Security 5.7.4).

Consider the following minimal resource server application:

```java
@SpringBootApplication
@RestController
public class SampleApplication {

    public static void main(String[] args) {
        SpringApplication.run(SampleApplication.class, args);
    }

    @RequestMapping(path = "/")
    String home() {
        return "Hello World!";
    }

    @Bean
    SecurityFilterChain securityFilterChain(HttpSecurity httpSecurity) throws Exception {
        httpSecurity.authorizeRequests(requests -> requests.anyRequest().authenticated());
        httpSecurity.oauth2ResourceServer(OAuth2ResourceServerConfigurer::opaqueToken);
        return httpSecurity.build();
    }

}
```

Issuing `POST` request to `/` without authorization header will result in `401`, as expected.

However, if `AuthorizationFilter` is used by changing `SecurityFilterChain` bean to this:

```java
@Bean
SecurityFilterChain securityFilterChain(HttpSecurity httpSecurity) throws Exception {
    httpSecurity.authorizeHttpRequests(requests -> requests.anyRequest().authenticated());
    httpSecurity.oauth2ResourceServer(OAuth2ResourceServerConfigurer::opaqueToken);
    return httpSecurity.build();
}
```

Then the same request will result in `403`.

I didn't dig too deep, but I observed that in first case `FilterChain#doFilter` invocation in `ExceptionTranslationFilter#doFilter` will throw `AccessDeniedException` which in turn results in invocation of `BearerTokenAuthenticationEntryPoint`, while in second case the same `FilterChain#doFilter` invocation in `ExceptionTranslationFilter#doFilter` won't throw an exception.

**Comment by marcusdacoregio** [comment]
This is not only related to a resource server, if any kind of authentication is being used, like `httpBasic` and `formLogin` the behavior is not consistent between the two filters.

This is happening because even if `FilterSecurityInterceptor#observeOncePerRequest` is `true`, the filter still applies to `ERROR` dispatch. The same is not true for `AuthorizationFilter`. Note that this does not happen in 6.0 because both filters apply to every request by default #11027.

If we configure it like the below, the `AuthorizationFilter` will apply to ERROR dispatch, therefore, returning a 401:
```java
http
	.authorizeHttpRequests((requests) -> requests
		.shouldFilterAllDispatcherTypes(true)
		.anyRequest().authenticated()
	)
        // ...
```

I wonder if we should change [this property](https://github.com/spring-projects/spring-security/blob/9b3f834bff38c80e3bcfa26e5d33d3d3e0eefa83/web/src/main/java/org/springframework/security/web/access/intercept/AuthorizationFilter.java#L58) to `true` for this reason. I'll reach out to @rwinch to check his opinion on this.

**Comment by jzheaux** [comment]
Though this ticket is focused on 5.7, [this portion](https://docs.spring.io/spring-security/reference/5.8/migration/servlet/authorization.html#_use_authorizationmanager_for_request_security) of the 5.8 migration guide may be helpful for additional context.

**Comment by marcusdacoregio** [comment]
Hi @vpavic, I've talked to @rwinch, and indeed we should not change the default given that we have ways to configure the filter to behave as we want.

I'm only curious what has made you switch from `authorizeRequests` to `authorizeHttpRequests`? Asking this because we might find something that we can improve in the docs or the migration guides.

**Comment by blaenk** [comment]
> I'm only curious what has made you switch from `authorizeRequests` to `authorizeHttpRequests`? Asking this because we might find something that we can improve in the docs or the migration guides.

I am an unrelated observer/subscriber to this issue, but for what it's worth, I myself switched because after upgrading to Spring Boot 3 and Spring Security 6, I noticed that my IDE stated that `authorizeRequests` was deprecated and the deprecation message said to use `authorizeHttpRequests` instead.

I wouldn't be surprised if others have done the same.

Thank you all for working on this project!

(Also unrelated: the most confusing/time-consuming aspect was trying to figure out why some routes were failing authorization even though clearly authorized, logs would show that authorization passed but then the filter would somehow re-run for the same request and that one failed authorization. It ended up being related to the change that the filter runs for all dispatcher types now, I believe, and "fixed" it by setting `.shouldFilterAllDispatcherTypes(false)`. The docs state that it is instead preferred to explicitly specify which dispatcher types to filter on, but I had considerable trouble figuring out what "dispatcher types" even were let alone which ones I should allow, and I did dedicate a decent amount of time trying to figure that out before giving up and simply specifying that option).

**Comment by marcusdacoregio** [comment]
Thanks for your input @blaenk.

Yes, we are aware that most users will migrate because of the deprecation notice.

Did you see the [Preparing for 6.0](https://docs.spring.io/spring-security/reference/5.8/migration/index.html) section of Spring Security 5.8 documentation? There you have all the steps necessary to prepare for 6.0 changes, including the [filter all dispatcher types](https://docs.spring.io/spring-security/reference/5.8/migration/servlet/authorization.html#switch-filter-all-dispatcher-types).

You might want to permit forward dispatch if you are using [Spring MVC to resolve view names](https://docs.spring.io/spring-security/reference/5.8/migration/servlet/authorization.html#switch-filter-all-dispatcher-types), or async dispatch if using `WebClient`. If you have any suggestions on how to improve the documentation to help figuring out the dispatcher types, that would be nice.

**Comment by marcusdacoregio** [comment]
I'll close this as solved but feel free to continue the discussion.
