### ISSUE TITLE
[CsrfWebFilter] For what this line?

### ISSUE THREAD

**Issue by meiblorn** [spring-projects/spring-security#12305]
https://github.com/spring-projects/spring-security/blob/45a963a011f3190ac9870d1c82d39ebe91fa39d3/web/src/main/java/org/springframework/security/web/server/csrf/CsrfWebFilter.java#L122

IMO, it's no sense.

**Comment by jzheaux** [comment]
Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
