### ISSUE TITLE
Decoded JWT Token results in invalid content in newer versions

### ISSUE THREAD

**Issue by madduci** [spring-projects/spring-security#12329]
**Describe the bug**
We use Spring Security for OAuth2 login using Keycloak. Until Spring Security 5.7.5 the JWT Token validation has worked perfectly.
Since the update at 5.8.0, but also using the newer version, 6.0.0, it stopped working, producing an odd format.

Spring Security 5.7.5:
`jwt.getClaimAsString("resource_access")` produces `{"notification-entry-service":{"roles":["disease-notification-sender"]}}`

Spring Security 5.8.0+:
`jwt.getClaimAsString("resource_access")` produces `{notification-entry-service={roles=[disease-notification-sender]}}`

This happens by simply updating the dependency in the project, without touching/modifying the existing code.

**To Reproduce**
Setup Spring Security 5.8. 0with OAuth2 and JWT. 

**Expected behavior**
The JWT parsing should not change behaviour (not even reported in the Changelog here - https://docs.spring.io/spring-security/reference/5.8/whats-new.html)

**Sample**

Could not be provided

**Comment by michaelweidmann** [comment]
Hi @jzheaux,

we had a look on it and we found out that the issue is caused by a dependency upgrade from the `com.nimbusds:nimbus-jose-jwt` library (see [this commit](https://github.com/spring-projects/spring-security/commit/a799528679b1d0bf76cbb971a7db171bf9f56261)). The library switched the JSON parser from `JSON-smart` to `GSON` (see [here](https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/74a64ad633771362d7a30edb359f9e02e6774143#Lsrc/main/java/com/nimbusds/jose/util/JSONObjectUtils.javaT119)).

The call to parse the token looks like this and from there on the library does its job (see [here](https://github.com/spring-projects/spring-security/blob/7ad4ebd07ad0c3c8a507cf68bb35308b6595042a/oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java#L154)):

```java
JWTClaimsSet jwtClaimsSet = this.jwtProcessor.process(parsedJwt, null);
```


The stacktrace looks like this:
![stacktrace nimbusds library](https://user-images.githubusercontent.com/37302540/207319786-31a461ca-247d-4d12-a82f-124ae1e3747a.png)

With JSON-smart a complex claim value was parsed to a `JSONObject` and with GSON the result is a `LinkedTreeMap`.

Up to 5.7:
![source type spring security 5.7](https://user-images.githubusercontent.com/37302540/207320373-5aa53436-34d7-41e4-b6e6-7476b424c7fe.png)

From 5.8 on:
![source type spring security 5.8 and upwards](https://user-images.githubusercontent.com/37302540/207320437-4cc0e3de-f717-4376-b789-970e413934c7.png)

This leads to the wrong conversion of the value from an object to the string in the class `ObjectToStringConverter` (see [here](https://github.com/spring-projects/spring-security/blob/7ad4ebd07ad0c3c8a507cf68bb35308b6595042a/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/converter/ObjectToStringConverter.java#L38)):

```java
@Override
public Object convert(Object source, TypeDescriptor sourceType, TypeDescriptor targetType) {
	return (source != null) ? source.toString() : null;
}
```

- in Spring Security 5.7: input is a `JSONObject` which gets converted to a JSON object string
- in Spring Security 5.8: input is a `LinkedTreeMap` which gets converted to a key-value string

How to proceed with this?

**Comment by adase11** [comment]
If it helps I noticed this as well in this issue https://github.com/spring-projects/spring-security/issues/12108#issue-1428041031

**Comment by jzheaux** [comment]
> The JWT parsing should not change behaviour

Since `JSONObject` and `LinkedTreeMap` both implement the `Map` interface, I guess I'm not clear yet on what the problem is. Could you clarify? It sounds like your code could be relying on Nimbus implementation details. I'll leave it to the Nimbus team to say whether they support that. 

Either way, Spring Security merely wraps Nimbus, so I'd recommend [filing an issue with them](https://bitbucket.org/connect2id/nimbus-jose-jwt/issues?status=new&status=open) if you'd like to see changes in its parsing behavior. The only parsing that we have dedicated code for are standard claims. Since `resource_access` is a non-standard claim, there is not much that Spring Security can do in the way of adapting changes in third-party code.

If you end up filing an issue with Nimbus, please consider posting the link here so that folks can follow that discussion.

In the meantime, you can use a custom claim converter to convert any given claim to the representation that you need:

```java
@Bean 
JwtDecoderFactory<ClientRegistration> jwtDecoderFactory() {
    OidcIdTokenDecoderFactory factory = new OidcIdTokenDecoderFactory();
    Map<String, Converter<Object, ?>> converters = OidcIdTokenDecoderFactory
            .createDefaultClaimTypeConverters();
    converters.put("resource_access", (object) -> {
        // ... reformulate as a JSONObject
    });
    ClaimTypeConverter claimTypeConverter = new ClaimTypeConverter(converters);
    factory.setClaimTypeConverterFactory((registration) -> claimTypeConverter);
    return factory;
}
```

For completeness, I'll also mention that `getClaimAsMap` is preferred given that the value is a `Map`. If the string representation is needed for serialization, note that `Jwt#getTokenValue` has the original serialized value.

> not even reported in the Changelog here

I'll take this as feedback for the future, thank you. I believe the [release notes](https://github.com/spring-projects/spring-security/releases/tag/5.8.0) do say that Nimbus was updated, though our release notes aren't linked in the What's New section.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by madduci** [comment]
Hi

Thank you very much for the support and help debugging this. I will report the problem to Nimbus developers and post here updates if I'll receive any.

For sure, this was a weird one.
