### ISSUE TITLE
WebSecurityConfigurationAdapter is missing from spring-security

### ISSUE THREAD

**Issue by nedim-bajric** [spring-projects/spring-security#12338]
I used to work with spring security before 15 days, and I implemented a basic JWT auth system. It works fine, but now, I am facing an error that says that there is no WebSecurityConfigurerAdapter in the security package. Also, I cannot Override the method for configuring Auth manager and builder.

https://github.com/nedim-bajric/basicJWTspring/blob/main/src/main/java/com/example/springjwt/config/WebSecurityConfig.java

**Comment by jzheaux** [comment]
Hi, @nedim-bajric, thanks for reaching out.

`WebSecurityConfigurerAdapter` was deprecated in 5.x and removed in 6.x. Please see the migration guide for a description on [what to do instead of extending `WebSecurityConfigurerAdapter`](https://docs.spring.io/spring-security/reference/5.8/migration/servlet/config.html#_stop_using_websecurityconfigureradapter).
