### ISSUE TITLE
Loading service provider xml without IDPSSODescriptor element

### ISSUE THREAD

**Issue by litalhalawi** [spring-projects/spring-security#12337]
https://github.com/spring-projects/spring-security/blob/cd0f02de49248a0fd0a2021201034a5f6c680417/saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/OpenSamlMetadataAssertingPartyDetailsConverter.java#L88

hey,
I'm trying to load my service provider xml into a relying party registration, in order to perform saml2:SPSSODescriptor endpoint
but the xml does not contain IDPSSODescriptor element - but SPSSSODescriptor.
(is it something I'm missing?)

**Comment by jzheaux** [comment]
Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
