### ISSUE TITLE
Add more deprecation metadata as of Spring Security 6 using @Deprecated attributes

### ISSUE THREAD

**Issue by ghusta** [spring-projects/spring-security#12429]
**Expected Behavior**

As Spring Security 6 is now using Java 17, we could provide more deprecation metadata thanks to the [`@Deprecated`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Deprecated.html) annotation, with the `since` and `forRemoval` attributes.

**Context**

Spring FWK 6 or Spring Boot 3 are already using this.

For example in https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/util/StringUtils.java#L226 : 

```java
@Deprecated(since = "6.0")
public static String trimWhitespace(String str) 
```

**Example**

```java
@Deprecated(since = "6.0")
public final class ExpressionUrlAuthorizationConfigurer<H extends HttpSecurityBuilder<H>> ...
```

or on methods :

```java
public final class org.springframework.security.config.annotation.web.builders.HttpSecurity 

@Deprecated(since = "6.0", forRemoval = true)
public ExpressionUrlAuthorizationConfigurer<HttpSecurity>.ExpressionInterceptUrlRegistry authorizeRequests()
```

What do you think ?

**Comment by marcusdacoregio** [comment]
Thanks for the suggestion @ghusta.

We are already using the `@Deprecation` properties to enhance the notice, see [the `CookieCsrfTokenRepository`](https://github.com/spring-projects/spring-security/blob/25133a97f956d9ab72f1bdc972fbe29848f65ea0/web/src/main/java/org/springframework/security/web/csrf/CookieCsrfTokenRepository.java#L163).

The suggestion is excellent and I'll talk to the team to keep that in mind, especially when doing code reviews. On the other hand, adding more metadata to existing `@Deprecated` annotations is a low-priority task and I don't think it has much value since we already provide enough information in the `@deprecated` tag.

**Comment by ghusta** [comment]
OK, thank you for the feedback.
