### ISSUE TITLE
Custom longin form problem

### ISSUE THREAD

**Issue by kentyeh** [spring-projects/spring-security#12446]
I want a custom login form to include an additional field.
So I plan to provide a custom  _UsernamePasswordAuthenticationFilter_ replacing the  original _FORM_LOGIN_FILTER_.
I wrote a demo application  [here](https://github.com/kentyeh/SS6) .
Direct run will be good  to login to /index by
```bash
mvn jetty:run
```
I use an old-fashioned  style [applicationContext.xml](https://github.com/kentyeh/SS6/blob/main/src/main/resources/applicationContext.xml) config.

Including [applicationContext-sec3.xml](https://github.com/kentyeh/SS6/blob/main/src/main/resources/applicationContext-sec3.xml) is a standard config that works fine.

But when I replace it by [applicationContext-sec1.xml](https://github.com/kentyeh/SS6/blob/main/src/main/resources/applicationContext-sec1.xml) or [applicationContext-sec2.xml](https://github.com/kentyeh/SS6/blob/main/src/main/resources/applicationContext-sec2.xml) (not even change _UsernamePasswordAuthenticationFilter_), the page always redirects to /login after login success.

The application work find before , Did I do something wrong?

**Comment by jzheaux** [comment]
Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
