### ISSUE TITLE
Built-in Class for Generating and Validating JWT Token

### ISSUE THREAD

**Issue by hannah23280** [spring-projects/spring-security#12480]
Hi,
   Recently i learn that when it comes to generating and validating JWT token, we have to write our own logic. Is this considered anti-pattern for us to write such boilerplate code? Any intention to provide built-in security filters that does this?

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
