### ISSUE TITLE
How to add user authorities(Role) to the Authentication.getAuthorities

### ISSUE THREAD

**Issue by Waylon-Firework** [spring-projects/spring-security#12481]
How to add user authorities(Role) to the Authentication.getAuthorities.

<img width="987" alt="image" src="https://user-images.githubusercontent.com/95599645/210248647-c251240b-43b4-4ab8-b2a9-b100a4881afa.png">

For jwt token, I can customize a class implement the Converter<Jwt, Collection<GrantedAuthority>> interface to solve this issue.
```
Converter<Jwt, Collection<GrantedAuthority>>

http.jwt().jwtAuthenticationConverter(jwtAuthenticationConverter)
```

But for the opaqueToken, we don't have a opaqueAuthenticationConverter method.

Could you please help take a look? Thanks.

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

Please see the reference for [OAuth 2.0 Resource Server Opaque Token](https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/opaque-token.html), specifically, `http.opaqueToken().authenticationConverter(opaqueTokenAuthenticationConverter)`.
