### ISSUE TITLE
I'm getting 401 error instead of 404.

### ISSUE THREAD

**Issue by Almadavic** [spring-projects/spring-security#12572]
When we are logged in the system and we access a resource that is not mapped ( doesn't exist) we get back a 404 error but it's not happening to me, I'm getting 401 error but it doesnt' make any sense because I'm already logged and i think its a spring security bug.

Filter :

        if (tokenJWT != null) { 

            User user = recoverUser(tokenJWT); 

            Authentication authentication = new UsernamePasswordAuthenticationToken(user, null, user.getAuthorities()); 
            SecurityContextHolder.getContext().setAuthentication(authentication); // The authentication is being done here, the user is already logged!

        }

          filterChain.doFilter(request, response); // Here, the request goes to the next class, SecurityConfigurations.
    }

SecurityConfigurations : 

                ...
                .anyRequest().authenticated() 

When i'm logged and access any resource that doesn't exist i had do get back 404 error but i'm getting 401.

![image](https://user-images.githubusercontent.com/85299065/213840696-ae95e456-eb37-4841-ab0a-307cebaa1be3.png)

I'm sure the token is valid!
It started happening when I updated the spring boot version to 3.0.1

**Comment by sjohnr** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

**Comment by JohannesSchwegler** [comment]
@Almadavic did you solve this issue? if so, how did you do it?

**Comment by Almadavic** [comment]
> @Almadavic did you solve this issue? if so, how did you do it?

Yes, I solved it. Reach me on my e-mail almadavic@live.com so we can talk about that.

**Comment by fkressmann** [comment]
> > @Almadavic did you solve this issue? if so, how did you do it?
> 
> Yes, I solved it. Reach me on my e-mail [almadavic@live.com](mailto:almadavic@live.com) so we can talk about that.

@Almadavic would you pls share your findings here (or somewhere else and link to it)? Otherwise this issue is useless for everybody else who found it on google etc (like me :D) 
And I guess you don't want a million people to contact you via email...
Thanks!

**Comment by MilanObrenovic** [comment]
> Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

isn't this a bug?

why does a wrong username/password return a 401 "unauthorized" during authentication? this is **authentication** process, not **authorization** process. if the user is already logged in and tries to access a resource, then returning 401 "unauthorized" makes sense. but if a user is NOT logged in and tries to login, it does not make sense to return 401 "unauthorized". why is a user "unauthorized" to login? it should be a 404 not found because the username/password is not found in the database.

so this smells like a spring security bug. how to override this behavior?

**Comment by sjohnr** [comment]
@MilanObrenovic as mentioned earlier, we do intend GitHub to be used only for bugs and enhancements, and not as a discussion board or question-answer forum. It sounds like you still have questions about Spring Security, and I'd encourage you to move that discussion to the appropriate forum.

Your question is answered elsewhere however, including in talks from Spring Security team members. See for example this Spring Security talk from [SpringOne 2021](https://www.youtube.com/watch?v=5tlU_Vjv8Ns).
