### ISSUE TITLE
No provider found for OAuth2AuthorizationCodeAuthenticationToken when running Spring Native Reactive app using OAuth2

### ISSUE THREAD

**Issue by msosa** [spring-projects/spring-security#12615]
**Describe the bug**
Logging in using reactive OAuth2 built with native throws after redirect from OAuth2 server(Google in my case). 

```
java.lang.IllegalStateException: No provider found for class org.springframework.security.oauth2.client.authentication.OAuth2AuthorizationCodeAuthenticationToken
        at org.springframework.security.web.server.authentication.AuthenticationWebFilter.lambda$authenticate$6(AuthenticationWebFilter.java:123) 
```
Do note that the non-reactive counterpart does work and is able to find the provider correctly.

**To Reproduce**
run `gradlew bootBuildImage`, run the docker image that is created, and attempt to login via OAuth2.

**Expected behavior**
Login with reactive Oauth2 without error

**Sample**

[Here](https://github.com/msosa/ReactiveOauth2/blob/main/src/main/kotlin/com/example/reactiveoauth2/security/SecurityConfiguration.kt) is a repo with a working example minus client id/secrets for the oauth2 client

**Comment by marcusdacoregio** [comment]
Hi @msosa, thanks for the report.

The problem here is that there is no hint for `JwtDecoder` that [is used here](https://github.com/spring-projects/spring-security/blob/59829321a8045c26f19c725f3ae081ac297e4079/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java#L3513). In the meantime, while I'm working on the fix and the version is not released, you can workaround that by changing your application to include that hint:

```java
@SpringBootApplication
@ImportRuntimeHints(MyHints::class)
class ReactiveOauth2Application

fun main(args: Array<String>) {
	runApplication<ReactiveOauth2Application>(*args)
}


class MyHints: RuntimeHintsRegistrar {

	override fun registerHints(hints: RuntimeHints, classLoader: ClassLoader?) {
		hints.reflection().registerType(TypeReference.of("org.springframework.security.oauth2.jwt.JwtDecoder"), MemberCategory.INVOKE_PUBLIC_CONSTRUCTORS)
	}

}
```

**Comment by msosa** [comment]
Awesome! I did try adding a few hints but not this one. Appreciate you looking into it.
