### ISSUE TITLE
Spring Security users.sql script should use uppercase SQL keywords

### ISSUE THREAD

**Issue by NewbieDong** [spring-projects/spring-security#13064]
**Expected Behavior**

The SQL keywords in the users.sql script provided by Spring Security should be written in uppercase letters, as is the convention for SQL.

**Current Behavior**

The SQL keywords in the users.sql script provided by Spring Security are not written in uppercase letters, which goes against the convention for SQL.

<img width="1277" alt="CleanShot 2023-04-18 at 16 38 19@2x" src="https://user-images.githubusercontent.com/108622342/232722805-2e61e337-f825-4cee-b0ae-e7c34ec4c208.png">

I would be happy to revise this issue.

**Comment by marcusdacoregio** [comment]
Hi @NewbieDong, thanks for the suggestion.

I don't think we would like to change this since nowadays people are using (most of the time) an IDE to read that script, and, like in the picture you shared, the IDE already highlights the keywords.

In addition to that, that file has not been changed since 2013, and applying a cosmetic change to such a stable file may lead to undesired side effects.

I'm closing this as declined but feel free to browse through the [ideal for contribution issues](https://github.com/spring-projects/spring-security/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+ideal-for-contribution%22) if you are interested in contributing to Spring Security ❤️
