### ISSUE TITLE
Invalid custom AuthorizationRequestRepository

### ISSUE THREAD

**Issue by BingChunMoLi** [spring-projects/spring-security#13076]
[docs](https://docs.spring.io/spring-security/reference/servlet/oauth2/client/authorization-grants.html#_storing_the_authorization_request)

1. Create a custom InMemoryOAuth2AuthorizationRequestRepository and configure it according to the document
2. Expected to use InMemoryOAuth2AuthorizationRequestRepository, but actually used HttpSessionOAuth2AuthorizationRequestRepository
tip:
> Because springboot is provided as a backend API for Vue to use,  So the following code was used.
```java
 http
                .csrf().disable()
                .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
```
Also, Can I provide InMemoryOAuth2AuthorizationRequestRepository for spring security？
I have One more question , 
```java
http.requestMatchers("/a")).permitAll()
```

if interface a throw Exception responseHeader have a Location http://127.0.0.1:8080/login . 
Is it expected behavior？ Alternatively, it is also a bug

- github repository
https://github.com/BingChunMoLi/security_oauth_demo

**Comment by jzheaux** [comment]
Thanks for getting in touch, @BingChunMoLi! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
