### ISSUE TITLE
http://www.springframework.org/schema/security/spring-security.xsd returns 404

### ISSUE THREAD

**Issue by marketsimulator** [spring-projects/spring-security#13131]
**Expected behavior**
[http://www.springframework.org/schema/security/spring-security.xsd](http://www.springframework.org/schema/security/spring-security.xsd) 

returns 404

should't it return/point-to the latest version of spring-security.xsd? e.g. spring-security-5.4.xsd

I had to update WEB-INF/classes/META-INF/spring/security-context.xml because a .war refused its deployment.

**Comment by jzheaux** [comment]
Thanks, @marketsimulator. Since the latest is 6.0, http://www.springframework.org/schema/security/spring-security.xsd will point to `spring-security-6.0.xsd`. I will leave this ticket open to look into what caused the missing file. For now, I've restored it manually.

As a side note, it's recommended that you [use HTTPS URLs](https://github.com/spring-io/nohttp#introduction) like https://www.springframework.org/schema/security/spring-security.xsd which the Spring Framework will resolve locally in your deployed WAR. In this way, you'll get a more secure URL and you will not reach out to the public internet to resolve the schema.

If you do choose to resolve the schema remotely, it's also recommended that you pick a specific version so that you are always downloading the schema that is compatible with your Spring Security version. In the case you mentioned, this would be https://www.springframework.org/schema/security/spring-security-5.4.xsd
