### ISSUE TITLE
oauth2 authorized login

### ISSUE THREAD

**Issue by yangwenliang123** [spring-projects/spring-security#13159]
I have already used oAuth2LoginReactiveAuthenticationManager.authenticate for authentication, but I will still need to log in the next time I visit.

**Comment by jzheaux** [comment]
Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
