### ISSUE TITLE
Can i override OAuth2LoginAuthenticationProvider originally?

### ISSUE THREAD

**Issue by xxyz30** [spring-projects/spring-security#13158]
**Context**
if my scope has openid, it will return null and then use the `OidcAuthorizationCodeAuthenticationProvider`
![图片](https://github.com/spring-projects/spring-security/assets/81208875/0fd86711-33ac-4307-a92f-af3adb9ae1ec)

But I hope not, because the target website not support Oidc. it just use 'openid' scope.
if use `OidcAuthorizationCodeAuthenticationProvider` ,i must use `jwk-set-uri`,or else throw INVALID_STATE_PARAMETER_ERROR_CODE

so can i  override OAuth2LoginAuthenticationProvider?

**Comment by jzheaux** [comment]
Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
