### ISSUE TITLE
Spring Security 6 combined with AspectJ weaving of spring-security-aspects executes PreAuthorize twice

### ISSUE THREAD

**Issue by rolevinks** [spring-projects/spring-security#13160]
**Describe the bug**
We just updated Spring Security to version 6 in our project , and replaced the @EnableGlobalMethodSecurity with @EnableMethodSecurity, both with adviceMode ASPECTJ. Furthermore, we have a @PostFilter on some getters in our entities, so we also use the aspectj maven plugin. 
Previously, this worked perfectly, but since the upgrade, the permission checks on methods in components are executed twice instead of once. 

**To Reproduce**
See attached project.

**Expected behavior**
Permission checks are executed once. 

**Sample**
[test.zip](https://github.com/spring-projects/spring-security/files/11461031/test.zip)

**Comment by jzheaux** [comment]
Thanks for the report, @rolevinks.

It appears this is due to the fact that the AOP Advisor bean is registered even when `ASPECTJ` mode is activated.

You can address this in your application for the moment by changing the annotation to:

```java
@EnableMethodSecurity(prePostEnabled = false, mode = ASPECTJ)
```

And then publishing the following bean:

```java
@Bean 
fun preAuthorizeAuthorizationMethodInterceptor(expressionHandler: MethodSecurityExpressionHandler): MethodInterceptor {
    val authorizationManager = PreAuthorizeAuthorizationManager()
    authorizationManager.setExpressionHandler(expressionHandler);
    return AuthorizationManagerBeforeMethodInterceptor.preAuthorize(authorizationManager);
}
```

The reason this works is because it is publishing the same bean as a `MethodInterceptor` instead of an `Advisor`, meaning that Spring doesn't try picking it up as an AOP Advisor as well.

To fix this may take a bit of research; however, I believe one way to address it is to publish a different configuration class when the advice mode is `ASPECTJ`. In that case, the components can be registered as ``MethodInterceptor``s instead.

**Comment by rolevinks** [comment]
Hi Josh,

Thanks for the quick reply, the workaround will do for now.

**Comment by marcusdacoregio** [comment]
Just a heads up that this has been reopened for `6.0.x` and `6.1.x`
