### ISSUE TITLE
R2dbcReactiveOAuth2AuthorizedClientService.loadAuthorizedClient query Exception

### ISSUE THREAD

**Issue by yangwenliang123** [spring-projects/spring-security#13187]
I attempted to log in using oauth2 authorization, but the R2dbcReactiveOAuth2AuthorizedClientService.loadAuthorizedClient method encountered a java.lang.IllegalArgumentException: Cannot encode class io.r2dbc.spi.Parameters $InParameter when querying binding parameters

**Comment by jzheaux** [comment]
Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
