### ISSUE TITLE
AuthorizationAnnotationUtils.findUniqueAnnotation broken for inherithed repository methods

### ISSUE THREAD

**Issue by hqrd** [spring-projects/spring-security#13234]
This issue is similar to https://github.com/spring-projects/spring-security/issues/13132
But for repository methods going through proxies.

Example code : 
```java
@NoRepositoryBean
@RepositoryRestResource
public interface DefaultCrudRepository<T, K> extends JpaRepository<T, K> {
	@PreAuthorize(SUPPORT_ROLE_RULE_FOR_CRUD)
	@Override
	@RestResource
	@NonNull
	<S extends T> S save(@NonNull S entity);

}
```

Then in `AuthorizationAnnotationUtils#findUniqueAnnotation`, the `mergedAnnotations` contains 2 PreAuthorize : 
![image](https://github.com/spring-projects/spring-security/assets/22975382/593cd98c-d422-4031-9ef0-03aa0efa9de4)

Which results in an `AnnotationConfigurationException`

**Comment by nightswimmings** [comment]
Looks like a rationale decision 

<img width="751" alt="image" src="https://github.com/spring-projects/spring-security/assets/9316403/27823240-57e2-40e9-8f28-67d0618f4b5a">

**Comment by jzheaux** [comment]
@hqrd Could you please do me the favor of creating a reproducer?

**Comment by nightswimmings** [comment]
I think I misunderstood the poster, because now we are facing this. The issue is not about multiple inheritance which is forbidden by a rationale now, but the fact that AuthorizationAnnotationUtils.findMergedAnnotations is detecting as duplicate the same exact annotation on same classs. In our case this  happens exactly in the same scenario, when our child repository is a @RestResourceRepository and contains a @PreAuthorize in save() method

**Comment by saulgiordani** [comment]
Hi @jzheaux, i would say this is the same as https://github.com/spring-projects/spring-security/issues/13490. The user that started the opened the issue also provided a very basic reproducer
