### ISSUE TITLE
Request: Include a simple fix for a bug with IE11 that was moved to v6 in a v5 release

### ISSUE THREAD

**Issue by kealjones-wk** [spring-projects/spring-security#13308]
This issue: https://github.com/spring-projects/spring-security/issues/13106
It has a fix that was initially slated for 5.8.4 but then that v5 release never came to be and the fix was moved into v6. Although our team is working on migrating to all Spring v6 stuff it is a large lift and taking us some time and this issue is blocking certain functionality for our customers. Is there any chance that the fix could be included in a v5 release?

**Comment by marcusdacoregio** [comment]
Hi @kealjones-wk, I don't think I follow what you are requesting.

The fix is scheduled for `5.8.4` which will be released on June 19th as you can [see here](https://github.com/spring-projects/spring-security/milestone/290). The `6.1.0` version already contains the fix because it was released last month.
