### ISSUE TITLE
permitAll() broken?

### ISSUE THREAD

**Issue by UglyHobbitFeet** [spring-projects/spring-security#13303]
I am upgrading from Spring 2.7.10 to 3.1. Part of that is converting authorizeRequests to authorizeHttpRequests.

I'm using the example here as a guideline:
https://docs.spring.io/spring-security/reference/servlet/authorization/authorize-http-requests.html#favor-permitall

My old code looked like so and still works in v3.1 but throws deprecation warnings:
```
  http.authorizeRequests().requestMatchers("/authenticate/**").permitAll().anyRequest().authenticated();
```

When I modify it to get rid of the deprecation warnings it no longer works:
```
 http.authorizeHttpRequests((authorize) -> authorize.requestMatchers("/authenticate/**").permitAll().anyRequest().authenticated());
```
Note that all other config code is identical. The only difference is the one line above to remove the deprecation warning.

Am I doing something wrong or is this a bug? I am calling a url similar to https://someserver/authenticate/blah from a frontend service. FWIW if I call it directly in the browser I notice I do get different HTTP responses for both.  i.e. A direct call with authorizeHttpRequests generates a 403 code whereas authorizeRequests generates a 405 code.

**Comment by marcusdacoregio** [comment]
Hi @UglyHobbitFeet, thanks for the report.

Can you share more details about your request? Are you sending any kind of authentication with it, even if it permits all?
Ideally, it would be great if you can provide a minimal, reproducible sample, if not, please try to share as much detail as possible.

> A direct call with authorizeHttpRequests generates a 403 code whereas authorizeRequests generates a 405 code.

This is odd, 405 means that the HTTP method is not supported. Can you also add the code of the controller that handles that method?

**Comment by UglyHobbitFeet** [comment]
I am sending X509 authentication that extends (
org.springframework.security.authentication.AbstractAuthenticationToken)
along with the request. Unfortunately I cannot share that code nor do I
have a small reproducible sample.

**Comment by marcusdacoregio** [comment]
In that case, I would recommend adding `logging.level.org.springframework.security=TRACE` to your `application.properties` and checking the console logs. The difference between `authorizeRequests(...)` (`FilterSecurityInterceptor`) and `authorizeHttpRequests(...)` (`AuthorizationFilter`) is that the former tries to authenticate the user if possible, that might be one of the reasons. Maybe your request is falling into the `anyRequest, the filter authenticates it and the request is allowed, but we need some debugging to be sure. You can try putting a breaking-point in both of those filter to see what is happening exactly.

You do not need to share the details as is, you can mask them and just share the pertinent parts.

**Comment by marcusdacoregio** [comment]
The x509 part of your code seems to be customized, so there is not much we can assume from here. It is important to remember that `permitAll` will try to authenticate the user if possible, contrary to `WebSecurity#ignoring` which does not invoke the filters.

> I changed to username/password login and it works fine.

What is working fine? Which request? What clues did you get from making that change?

**Comment by UglyHobbitFeet** [comment]
I am not sure what other logging I can provide. I know the X509 code works with the deprecated authroizeRequests call

My application has two modes of authentication.  One is X509, the other is username/password.  Based off your comments I decided to switch to username/password to see if it worked, and it did.  So I thought I would mention that in my response because it helped confirm that the X509 is what is tripping up the authorizeHttpRequests call.

**Comment by marcusdacoregio** [comment]
It is strange that you have an authentication token in the security context with no authorities:
```
TRACE 1 --- [-nio-443-exec-9] o.s.s.w.a.AnonymousAuthenticationFilter  : Did not set SecurityContextHolder since already authenticated MyCustomX509Token [Principal=MyPrincipalInfo, Credentials=[PROTECTED], Authenticated=false, Details=null, Granted Authorities=[]]
```

However, your logs do not show the 403 happening. If there is any security-related error, the exception should be printed to the console. Can you find it in the logs output?

**Comment by marcusdacoregio** [comment]
Hi @UglyHobbitFeet, since you did not share the logs where the 403 is happening, and based on what I could assume from your code, here are my thoughts:

1. The code on `CustomX509AuthenticationProcessingFilter#attemptAuthentication` looks strange, ideally it should run the authentication token against an `AuthenticationManager`, see the `UsernamePasswordAuthenticationFilter` [implementation as an example](https://github.com/spring-projects/spring-security/blob/61e2bae7f2a3127c6b0ca662a2611ac8fff091f2/web/src/main/java/org/springframework/security/web/authentication/UsernamePasswordAuthenticationFilter.java#L72-L85).
2. The token returned from `CustomX509AuthenticationProcessingFilter#attemptAuthentication` is not authenticated, therefore, when using `authorizeRequests(...)` and the code hits [this method](https://github.com/spring-projects/spring-security/blob/61e2bae7f2a3127c6b0ca662a2611ac8fff091f2/core/src/main/java/org/springframework/security/access/intercept/AbstractSecurityInterceptor.java#L321-L337), that unauthenticated token gets authenticated using the `CustomX509AuthenticationProvider`. However, when you switch to `authorizeHttpRequests` you are switching from `FilterSecurityInterceptor` to `AuthorizationFilter`, and the latter does not re-authenticate the request.

With that said I suggest that you put a breakpoint on the code I linked above to check the behavior described and you should revisit your custom filter implementation in order to validate the authentication token against the `AuthenticationManager` that you already have, that should get things working for you.
