### ISSUE TITLE
Why does RequestRejectException occur when a client sends a request to OAuth?

### ISSUE THREAD

**Issue by seonghoo1217** [spring-projects/spring-security#13471]
## Issue
- Exception in client's API request
- I knew that "//" was a problem in the error logging message, so I thought the client's request was wrong.
- So I logged the Request URI on the Custom Filter and looked at it, but it didn't send the problem URL to the server.

## Current States
- Eventually, I found a double slash in the OAuth Redirect part, and when I corrected it, the error disappeared.
- However, since it was Request RejectException, I knew that there was a problem with the request sent by the client, but how can I get the error because there was a mistake in the OAuth setting?
- I wonder if 'RequestRejectException' also reflects the wrong value of Response.

**Comment by jzheaux** [comment]
Thanks for the insight, @seonghoo1217, and I'm glad you got the issue corrected.

If I understand you correctly, you are wondering whether a situation like this should throw a `RequestRejectedException`. The answer is "yes" since it violates one of the firewall rules. Sometimes mismatches like these happen, but not much can be done since the firewall comes first and doesn't know anything about your OAuth settings.
