### ISSUE TITLE
WebSecurityConfigurerAdapter migration strange outcome

### ISSUE THREAD

**Issue by rawfg** [spring-projects/spring-security#13555]
**Describe the bug**
Some time ago I performed the [Spring Security 5.7 migration](https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter) in our codebase. I noticed that the order of the execution/applying security changed when `WebSecurityConfigurerAdapter` was removed and the `SecurityFilterChain` beans were introduced. 

I report this _phenomena_ as it could be useful (and time saving) as a guide when migrating from Spring Boot 2.x to Spring Boot 3.x (and from Spring Security 5.x to Spring Security 6.x which is `WebSecurityConfigurerAdapter` less).

**To Reproduce**
1. Clone the [sample repository](https://github.com/rawfg/spring-migration-gimmicks)
2. Examine the [`DevSecurity`](https://github.com/rawfg/spring-migration-gimmicks/blob/main/src/main/java/ch/rcode/migration/gimmicks/DevSecurity.java) configuration class
3. Run the `mvn spring-boot:run` in the project root directory
4. Notice the order of the execution in the logs
5. Switch to the [`migrated`](https://github.com/rawfg/spring-migration-gimmicks/blob/migrated) branch
6. Examine the [`DevSecurity`](https://github.com/rawfg/spring-migration-gimmicks/blob/migrated/src/main/java/ch/rcode/migration/gimmicks/DevSecurity.java) configuration class
7. Run the `mvn spring-boot:run` in the project root directory
4. Notice the changed order of execution

**Expected behavior**
The order is the same or this behavior is explained / documented.

**Sample**
Sample repository can be found [here](https://github.com/rawfg/spring-migration-gimmicks/).

It contains two branches, each with a separate `README.md`:
- [`main`](https://github.com/rawfg/spring-migration-gimmicks/blob/main) branch
- [`migrated`](https://github.com/rawfg/spring-migration-gimmicks/blob/migrated) branch

**Comment by marcusdacoregio** [comment]
Hi @rawfg, has this order change caused any problems in your applications? If so, can you explain more about that scenario?

When reading your README I notice that you mentioned:

> secondChain was executed first
innerChain of the FirstConfiguration configuration class, despite having @Order(Ordered.HIGHEST_PRECEDENCE) was executed later

They are not really being "executed", instead, it's the order that the beans are being created. When using `WebSecurityConfigurerAdapter`, the logs are inside the `configure` method instead of the bean creation, it is expected that it may vary.

**Comment by rawfg** [comment]
> Hi @rawfg, has this caused any problems in your applications? If so, can you explain more about that scenario?

Hi @marcusdacoregio as far as I remember it caused some problems with migration last year. I need to double check commit history and issues description to confirm that and give more details. Please keep it low profile, I will update ASAP.

**Comment by rawfg** [comment]
Hi @marcusdacoregio I updated the sample repository with the missing `HttpSecurity` configuration on both branches. 
To better present the issue I added two controllers (`LoginController` and `HelloWorldController`) and a login form. The sample looks like this:

1. on the [main](https://github.com/rawfg/spring-migration-gimmicks/blob/main/src/main/java/ch/rcode/migration/gimmicks/DevSecurity.java) branch, when there are `WebSecurityConfigurerAdapter` used, is the `FirstConfiguration` that configures the login form and the `InMemoryUserDetailsManager` bean. The second configuration has some CORS preflight configuration. When I start the application I navigate to the http://localhost:8080/hello and I'm prompted to provide credentials - after providing I see _hello user_ produces by the `HelloWorldController`. This is the expected behavior.
2. on the [migrated](https://github.com/rawfg/spring-migration-gimmicks/blob/migrated/src/main/java/ch/rcode/migration/gimmicks/DevSecurity.java) branch, when simple migration (replace `WebSecurityConfigurerAdapter` `configure` methods with `SecurityFilterChain` beans) was done the behavior is different - when I navigate to the `http://localhost:8080/hello` I see "hello anonymousUser" instead of the login prompt and the entire login security configuration seems totally ignored.

**Comment by marcusdacoregio** [comment]
Hi, @rawfg. [I opened a PR](https://github.com/rawfg/spring-migration-gimmicks/pull/1) in your repository to show the expected configuration. Basically, you need to define the order of the bean itself instead of the order of the configuration class.

I do not quite understand what you are trying to achieve with the second filter chain, but if you need to customize CORS you can always specify [a `CorsConfigurationSource` bean](https://docs.spring.io/spring-security/reference/servlet/integrations/cors.html#page-title).
