### ISSUE TITLE
Alternative to deprecated ClientCredentialsResourceDetails and OAuth2RestTemplate

### ISSUE THREAD

**Issue by VanitaDhanagar** [spring-projects/spring-security#13559]
HI ,

I am migrating  spring boot  application to 3.1.1 and Jdk 17 

And i have "OAuth2RestTemplate " with dependency 
<dependency>
			<groupId>org.springframework.security.oauth</groupId>
			<artifactId>spring-security-oauth2</artifactId>
			<version>2.5.2.RELEASE</version>
		</dependency>
		
It shows all the methods from this are deprecated ,And i do not find proper doc , all the documents are partial , Can share  sample example?

Kinldy help here 

Regards,
Vanita

**Comment by sjohnr** [comment]
@VanitaDhanagar, thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

Having said that please see the [OAuth2 Migration Guide](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide) and the [reference documentation](https://docs.spring.io/spring-security/reference/servlet/oauth2/index.html).
