### ISSUE TITLE
Need help with understanding the usage of encryptionX509Credentials

### ISSUE THREAD

**Issue by AkashB23** [spring-projects/spring-security#13578]
https://github.com/spring-projects/spring-security/blob/2ef9dc916fe5d98a99319c72f575b1f5c8cdf474/saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistration.java#L416

Hi, can somebody help with significance of encryptionX509Credentials and what are its usage

**Comment by jzheaux** [comment]
Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
