### ISSUE TITLE
Google OAuth2 Login get Userinfo invalid content type 'application/json;charset=utf-8'. 

### ISSUE THREAD

**Issue by JL-Code** [spring-projects/spring-security#13646]
**Describe the bug**
[invalid_user_info_response] An error occurred while attempting to retrieve the UserInfo Resource from 'https://www.googleapis.com/oauth2/v3/userinfo': response contains invalid content type 'application/json;charset=utf-8'. The UserInfo Response should return a JSON object (content type 'application/json') that contains a collection of name and value pairs of the claims about the authenticated End-User. Please ensure the UserInfo Uri in UserInfoEndpoint for Client Registration 'google' conforms to the UserInfo Endpoint, as defined in OpenID Connect 1.0: 'https://openid.net/specs/openid-connect-core-1_0.html#UserInfo'

**To Reproduce**
<img width="935" alt="image" src="https://github.com/spring-projects/spring-security/assets/14163944/d3f5ba6f-bb65-4e59-b049-e8e3c596ae8a">

**Expected behavior**
Normal parsing

**Sample**

**Comment by sjohnr** [comment]
Thanks for getting in touch @JL-Code. I apologize for the delay, this issue slipped through the cracks and I've noticed it just now while reviewing older issues. Unfortunately, you have not provided very much information. I am not aware of any issues with using Google as an OpenID Connect 1.0 provider, but I'm not certain based on the information provided if that's even what you're trying to do. 

Therefore, it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
