### ISSUE TITLE
Adding Signature to Service Provider Metadata in Spring Security SAML

### ISSUE THREAD

**Issue by sumeetpri** [spring-projects/spring-security#13657]
I'm currently working with Spring Security SAML to generate service provider metadata for integration with an identity provider (IDP). While the metadata is being generated successfully, it is not including the `<ds:Signature>` attribute, which is necessary for the IDP to trust the uploaded metadata.

The expected behavior is to have the service metadata details signed, allowing it to be trusted by the IDP when uploaded. Could you provide guidance on how to include the `<ds:Signature>` attribute after signing the metadata details? Any assistance with configuring this functionality would be greatly appreciated.

Is there any way I can extend the class metadata filter or implement my own class to sign metadata details?

Thank you!

**Comment by sumeetpri** [comment]
@marcusdacoregio @sjohnr - Looking forward for your expert input on how to achieve IDP login keeping session stateless

**Comment by sjohnr** [comment]
Thanks for reaching out @sumeetpri! However, it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

**Comment by sumeetpri** [comment]
@sjohnr Thank you for you input . I have asked [stackover question](https://stackoverflow.com/questions/76926392/adding-signature-to-service-provider-metadata-in-spring-security-saml ) .

**Comment by ckarawani** [comment]
@sumeetpri were you ever able to resolve this?
