### ISSUE TITLE
Method springSecurityFilterChain in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a single bean, but 2 were found

### ISSUE THREAD

**Issue by dylan-tao** [spring-projects/spring-security#13756]
**Describe the bug**

Method springSecurityFilterChain in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a single bean, but 2 were found:
	- requestMappingHandlerMapping: defined by method 'requestMappingHandlerMapping' in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]
	- controllerEndpointHandlerMapping: defined by method 'controllerEndpointHandlerMapping' in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/servlet/WebMvcEndpointManagementContextConfiguration.class]

**To Reproduce**
1. Version: Spring boot 2.7.12 & security-config 5.8.3
2. start application failed

**Expected behavior**
start application success

**Sample**
not yet

**Comment by sjohnr** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

**Comment by dylan-tao** [comment]
WebSecurityConfiguration  get RequestMappingHandlerMapping bean support：  getBean("requestMappingHandlerMapping", RequestMappingHandlerMapping.class) or @Qualifier("requestMappingHandlerMapping") ，Why not fix him？
Spring Boot 2.7.x WebMvcAutoConfiguration$EnableWebMvcConfiguration init   RequestMappingHandlerMapping‘s method  has been removed @Primary annotation，please fix it

**Comment by dylan-tao** [comment]
> Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.


WebSecurityConfiguration get RequestMappingHandlerMapping bean support： getBean("requestMappingHandlerMapping", RequestMappingHandlerMapping.class) or @qualifier("requestMappingHandlerMapping") ，Why not fix him？
Spring Boot 2.7.x WebMvcAutoConfiguration$EnableWebMvcConfiguration init RequestMappingHandlerMapping‘s method has been removed @primary annotation，please fix it

**Comment by sjohnr** [comment]
@dylan-tao apologies but I'm not quite able to understand you. It sounds as though you're reporting a change in behavior in Spring Boot, because `WebMvcAutoConfiguration` is a [Spring Boot](https://github.com/spring-projects/spring-boot/) class. Please provide a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the issue, and also consider making your report in the spring boot [issue tracker](https://github.com/spring-projects/spring-boot/issues/new).
