### ISSUE TITLE
how to register a global filter

### ISSUE THREAD

**Issue by mazenaissa** [spring-projects/spring-security#13790]
Hello,

Is there any way XML/Java config to register a global filter which will be invoked in all the security filter chains?
I don't want to register the filter by XML/Java config myself in all the security filter chains additionally I don't want to add it in the web.xml (for servlet container apps), is there any way that make it easy and straightforward ?

Thanks,

**Comment by marcusdacoregio** [comment]
Hi, @mazenaissa, thanks for reaching out. It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.

That said, if you are using Spring Boot you can take a look at [its documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.servlet.embedded-container.servlets-filters-listeners.beans). If you have an implementation of `Filter` you can make it a Spring Bean to be registered with the embedded container.
