### ISSUE TITLE
/oauth2/revoke endpoint returns status 200 but access token still valid in spring security 6

### ISSUE THREAD

**Issue by kalaskaratul321** [spring-projects/spring-security#13859]
**Describe the bug**
i have writen custom controller to logout user and in same controller i am calling .oauth2/revoke api using restTemplet i am getting status 200 but my token is till valid

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by sjohnr** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
