### ISSUE TITLE
If user does not do anything (i.e. use mouse, key press, scrolling etc) for 2 mins then user will be logged out automatically and the page will be redirected to login page:

### ISSUE THREAD

**Issue by Imrnkhan** [spring-projects/spring-security#13863]
**Describe the bug**
A make a demo app that is work on the signup page and login page but when the user not active in 2 min than redirect in again login page 
**To Reproduce**
Steps to reproduce the behavior.
its based on Spring Security use in this project one kind of demo when If user does not do anything (i.e. use mouse, key press, scrolling etc) for 2 mins then user will be logged out automatically and the page will be redirected to login page:
use dependencies 1.spring security 2. spring web 3. thymeleaf some use of js,html

**Expected behavior**

**Sample**

If user does not do anything (i.e. use mouse, key press, scrolling etc) for 2 mins then user will be logged out automatically and the page will be redirected to login page:
spring boot project application java.and this this is my code can any one fix and help out this code
[demo2-master.zip](https://github.com/vaadin/flow/files/12706288/demo2-master.zip)

**Comment by sjohnr** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
