### ISSUE TITLE
Add possibility to use @PreAuthorize and @PostAuthorize  with Java code

### ISSUE THREAD

**Issue by PavelTurkish** [spring-projects/spring-security#14086]
**Current Behavior**

I am just learning Spring Security and method security and reading about `@PreAuthorize` and `@PostAuthorize` with EL. Besides EL is used In all examples I found in internet. EL is great when we use it where we can't use Java code. For example in test data in excel file. But in java class it is an absolute evil.

**Expected Behavior**

I would suggest to give in annotation class literal with parameters. Of course it is not very good solution but I think it is much better than strings. So, something like this:

```
@FunctionalInterface
public interface AuthorizePredicate { // <!-- must be declared in spring security library
    boolean test(Object... args);
}

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
@NonELPreAuthorize() // <!-- must be declared in spring security library
public @interface  CustomNonELPreAuthorize {
    Class<? extends AuthorizePredicate> predicateClass();
    String[] args() default {};
}

public class DefaultAuthorizePredicate implements AuthorizePredicate {
    @Override
    public boolean test(Object... args) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}

@Controller
public class FooController {
    @GetMapping(value = "/bar", produces = MediaType.TEXT_HTML_VALUE)
    @CustomNonELPreAuthorize(args = {"one"}, predicateClass = DefaultAuthorizePredicate.class)
    public String bar(Model model) {
        return "index";
    }
}
```

**Comment by sjohnr** [comment]
@PavelTurkish thanks for your interest in the project and the suggestion.

Looking at your example, I'm not 100% sure I understand your goal, but it seems you are suggesting a solution that allows for a new annotation that can reference a `class` and invoke a functional interface (via reflection, but without requiring SpEL), passing it method arguments. Is that correct? If so, this is a very specific request that seems more appropriate as a customization on top of Spring Security.

Custom authorization is indeed a complex topic, but I believe that what you're requesting is already possible in a variety of ways. I won't provide a full example here as the purpose of this issue is to discuss an enhancement, but you can review the documentation on [using a custom AuthorizationManager](https://docs.spring.io/spring-security/reference/servlet/authorization/method-security.html#custom-authorization-managers) to get started. The docs discuss using pointcuts to provide custom authorization with code, including (but not limited to) the ability to replace the functionality of `@PreAuthorize` entirely.

While not exactly specific to your use case, you can see [this helpful example](https://github.com/jzheaux/devnexus-2023/blob/ce244bd9247f965bd60b0519edc73f5a2a618bc1/flights-api/src/main/java/com/example/api/SecurityConfiguration.java#L54-L68) from a [recent talk at DevNexus 2023](https://github.com/jzheaux/devnexus-2023). You could also develop a completely custom annotation and use similar configuration to apply it.

If you'd like help working through how to achieve something similar to what you're requesting in this issue, please feel free to submit a question on [StackOverflow](https://stackoverflow.com/questions/tagged/spring-security) and I'd be happy to take a look.

For now, I'm going to close this issue as I don't believe the specifics of your suggestion would make a good candidate for adding directly to the framework. However, if I seem to be misunderstanding your suggestion, please let me know.
