### ISSUE TITLE
Change to Using Saml2AuthenticationRequestResolver instead of Saml2AuthenticationRequestFactory

### ISSUE THREAD

**Issue by testpasha777** [spring-projects/spring-security#14253]
Hello, We have custom SamlAuthenticationRequestFactory implements Saml2AuthenticationRequestFactory
with override createAuthenticationRequest, createPostAuthenticationRequest, createRedirectAuthenticationRequest

In migration guide to saml4 we have to configure Saml2AuthenticationRequestResolver instead of Saml2AuthenticationRequestFactory.
Is it possible to do something similar to what is done in the Saml2AuthenticationRequestFactory?

Can you show example, how to make createAuthenticationRequest, createPostAuthenticationRequest and createRedirectAuthenticationRequest in Saml2AuthenticationRequestResolver?

Thanks for help

**Comment by jzheaux** [comment]
Thanks for getting in touch, @testpasha777! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question so that other people can find it.

In your SO post, will you please include an example of what customization you are doing already?
