### ISSUE TITLE
DispatcherServletDelegatingRequestMatcher causes errors when there is more than one ServletContext

### ISSUE THREAD

**Issue by LewisMcReu** [spring-projects/spring-security#14418]
**Describe the bug**
In a Spring Boot application with multiple servlets registered to the context (DispatcherServlet and at least one other), an `IllegalArgumentException` with message `Failed to find servlet [] in the servlet context` is thrown when running tests with `MockMvc` and `@SpringBootTest(webEnvironment = RANDOM_PORT)`.

The problem started occurring after an upgrade from Spring Boot 3.0.2 to Spring Boot 3.2.1 (Spring Security 6.2.1).

The exception is thrown in the DispatcherServletDelegatingRequestMatcher due to an incompatibility with the standard MockHttpServletRequest instances created with the MockMvcRequestBuilders class. These have a generic HttpRequestMapping with an empty String as the servletName, thus causing the Matcher to not find a ServletRegistration and throw the exception.

Gist with full stacktrace: [Gist](https://gist.github.com/LewisMcReu/af1c1bd53cd80decffb496583db50702)

**To Reproduce**
Run the tests in the provided sample to reproduce.

In the sample is a simple Spring Boot app with an extra servlet registered to the context and a basic security setup. 
The included tests demonstrate 2 working cases and one failing case.
The test TestWithRandomPortEnvironment#expected_failure demonstrates the exception.
TestWithRandomPortEnvironment#expected_success demonstrates the fix I implemented to make this work with a RequestPostProcessor, but this solution would have to be applied everywhere I'm using MockMvc.

**Expected behavior**
The DispatcherServletDelegatingRequestMatcher should be compatible with the standard MockHttpServletRequest instances created with the MockMvcHttpRequestBuilders and not throw an exception.

**Sample**
[Sample repository](https://github.com/LewisMcReu/spring-security-multiservlet-bug)

**Comment by atrepczik** [comment]
I have a very similar problem that is not just limited to running tests with MockMvc. It can also happen in a Spring Boot application at runtime, if **all** of the following conditions are given:

1. `management.server.port=8081` or anything that is not the same as `server.port`
2. Use `securityMatcher` in Spring Security DSL
3. Register a custom servlet
4. Start the application and try to access a non-existing endpoint on the management port, e.g. `curl -i http://localhost:8081/foo`

This will get you an internal server error with HTTP status code 500. With Spring Boot 3.1.0, you would see a 404 as expected for a non-existing endpoint.

The stacktrace is similar to the one from the initial post, but the message is slightly different. In my case, the servlet it fails to find does have a non-empty name: `Failed to find servlet [dispatcherServletRegistration] in the servlet context`

The sample repository from the initial post seems unavailable. I have created another sample repository with a sample application to reproduce the issue I described: https://github.com/atrepczik/spring-security-request-matching-issue

**Comment by Sax388** [comment]
@LewisMcReu Could you perhaps add the fix you had in mind? I didn't manage to (yet) and the repository you mentioned is empty right now.

**Comment by sabinisshrestha** [comment]
Did anyone solve the issue. I am looking to solve this for a while. How do I get past this issue?

**Comment by piotrszczepankowski** [comment]
I have the same problem. On our side it started to appear after adding random port to spring boot test annotation :( 

Not working: @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
Working: @SpringBootTest

Spring 3.2.2: 
Exception:
java.lang.IllegalArgumentException: Failed to find servlet [] in the servlet context

**Comment by nstuart-idexx** [comment]
Having the same problem, but only with some of our applications. Digging into the difference, the problem is with the
DispatcherServletDelegatingRequestMatcher and only comes into play if there are more than one Servlet registrations, for us. I have not tied it to the Random port, as our app does in fact have to servlet registrations.

The key decision point is in AbstractRequestMatcherRegistry, [here](https://github.com/spring-projects/spring-security/blob/69527f9a9c6ded890763d67d992cbcbb3a393162/config/src/main/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistry.java#L244).

It does NOT use the MVC matcher, but the Delegating matcher instead. The delegating matcher does not seem to work with the MockMvc request as the servlet name is in fact null when it gets to [here](https://github.com/spring-projects/spring-security/blob/69527f9a9c6ded890763d67d992cbcbb3a393162/config/src/main/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistry.java#L541) in DispatcherServletDelegatingRequestMatcher.

AbstractRequestMatcherRegistry does say it's new since 3.2, so seems like a regression when using MockMvc in tests.

**Comment by freddiN** [comment]
This is not only happening in tests:
https://stackoverflow.com/questions/77710370/actuator-endpoints-returning-500-error-after-upgrade-to-spring-boot-3
https://stackoverflow.com/questions/77785192/spring-boot-3-missing-dispatcherservletregistration-bean-in-actuator

I sprinkled some "AntPathRequestMatcher" calls around in my code, but imho this needs more attention as its a regression (that strangely enough not more people run into)

**Comment by laguiar** [comment]
So, no official response from `spring-security` team yet about this bug 😞 
Got all the same issues described above after 3.2.x migration.

**Comment by strakz1** [comment]
We encountered the same problem (java.lang.IllegalArgumentException: Failed to find servlet [dispatcherServletRegistration]) after upgrading to Spring Boot 3.2.4 and changing the actuator port.

The constant dispatcherServletRegistration mentioned in the exception is declared in org.springframework.boot.autoconfigure.web.servlet.DispatcherServletAutoConfiguration#DEFAULT_DISPATCHER_SERVLET_REGISTRATION_BEAN_NAME.

I expected this constant to be used in the method org.springframework.boot.autoconfigure.web.servlet.DispatcherServletAutoConfiguration.DispatcherServletRegistrationConfiguration#dispatcherServletRegistration, but instead, DEFAULT_DISPATCHER_SERVLET_BEAN_NAME is used.

To resolve the issue, I excluded the DispatcherServletAutoConfiguration from the application, copied its content to a custom auto-configuration class, and modified the usage of the constant.

After starting the application, the actuator works. However, I am unsure if this solution is correct because the relevant line in the https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/DispatcherServletAutoConfiguration.java has been in place for over 10 years.

**Comment by jzheaux** [comment]
Thanks for the reports and for your patience as this gets addressed.

A workaround for this failure is to instead use `requestMatchers(requestMatcher)` instead, like so:

```java
@Bean 
MvcRequestMatcher.Builder mvc(HandlerMappingIntrospector introspector) {
    return new MvcRequestMatcher.Builder(introspector);
}

@Bean
@Order(1)
public SecurityFilterChain dummyFilterChain(HttpSecurity http, MvcRequestMatcher.Builder mvc) throws Exception {

        // ...

        http.authorizeHttpRequests(config -> {
            config.requestMatchers(mvc.pattern("/hello")).permitAll();
            config.requestMatchers(mvc.pattern("/actuator"), mvc.pattern("/actuator/**"), mvc.pattern("/readyz"), mvc.pattern("/livez")).permitAll();
            config.anyRequest().fullyAuthenticated();
        });

        // ...

        return http.build();
    }
```

That said, I am investigating [a fix](https://github.com/jzheaux/spring-security/commit/564095d3ea7a99eb8891f7ff762e9078ee118483) to learn about its implications. I'm targeting the next milestone release to have a fix out.

**Comment by jzheaux** [comment]
Reopening to take a look the OP's use case, which is separate from some of the non-test-related reports here.

**Comment by jzheaux** [comment]
@atrepczik, regarding the bug you are seeing with MockMvc, the above fix will not help completely. 

As a bit of background, when using `requestMatchers(String)`, Spring Security doesn't know whether it is an MVC endpoint or not. So, in applications that have both MVC and non-MVC endpoints (the custom servlet in your case), Spring Security needs more information. 

Spring Security could possibly use the fact that it's running inside a MockMvc test, though I'm not clear of a generic way to do that. I'll reach out to the Spring Web team to see what they think.

In the meantime, you can [use `requestMatcher(RequestMatcher)`](https://github.com/spring-projects/spring-security/issues/14418#issuecomment-2143152371) instead. Or, if you update to the latest SNAPSHOT, you instead only need to update your tests like so:

```java
this.mvc.perform(get("/").with((request) -> {
	request.setHttpServletMapping(new MockHttpServletMapping("/", "/", "dispatcherServlet", MappingMatch.PATH));
	return request;
})).andExpect(status().isOk());
```

Or, if you want it to be a little bit more generic, you can do:

```java
private static RequestPostProcessor mvcMapping() {
	return (request) -> {
		String matchValue = request.getRequestURI();
		String servlet = "dispatcherServlet";
		String pattern = request.getServletContext().getServletRegistration(servlet).getMappings().iterator().next();
		HttpServletMapping mapping = new MockHttpServletMapping(matchValue, pattern, servlet, MappingMatch.PATH);
		request.setHttpServletMapping(mapping);
		return request;
	};
}

// ...

this.mvc.perform(get("/").with(mvcMapping()).andExpect(status().isOk());
```

**Comment by jzheaux** [comment]
With #13849 closed, the MockMvc tests in @atrepczik's sample all pass now. Please confirm by using the latest 5.8, 6.2, 6.3, or 6.4 snapshot.

**Comment by atrepczik** [comment]
Can confirm there's no longer an error with spring-security 6.3.1-SNAPSHOT. Thanks a lot for fixing!
