### ISSUE TITLE
SessionManagementSpec missing on latest release 

### ISSUE THREAD

**Issue by ionutgyn** [spring-projects/spring-security#14444]
Hi.

I saw that there was an issue regarding the Max Sessions on WebFlux (https://github.com/spring-projects/spring-security/commit/57ab15127af082a75bdc4a7a35d27469d7417756) that was solved and the changes are already on the main branch. I want to make use of this in my project but after downloaded the latest release the SessionManagementSpec is missing in config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java. Also I didn't found this enhancement in the release notes.

Was this enhancement released or not yet ?

Thank you.

**Comment by jzheaux** [comment]
Hi, @ionutgyn, I'm not sure what you mean by "latest release". Can you clarify? It appears that `SessionManagementSpec` is released since `6.3.0-M1`: https://github.com/spring-projects/spring-security/blob/6.3.0-M1/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java#L323

**Comment by ionutgyn** [comment]
> Hi, @ionutgyn, I'm not sure what you mean by "latest release". Can you clarify? It appears that `SessionManagementSpec` is released since `6.3.0-M1`: https://github.com/spring-projects/spring-security/blob/6.3.0-M1/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java#L323

Hi @jzheaux. By the latest release I meant to 6.3.1 which I'm trying to use and the SessionManagementSpec is not there

**Comment by ionutgyn** [comment]
Hi @jzheaux. By the latest release I meant to 6.3.1 which I'm trying to use and the SessionManagementSpec is not there

**Comment by ionutgyn** [comment]
My use case is based on spring-boot-starter-security 3.2.1 witch does not include spring security 6.3.0-M1 yet

**Comment by ionutgyn** [comment]
I see 6.3.0-M1 is in pre release https://github.com/spring-projects/spring-security/releases so it's not released yet

**Comment by ionutgyn** [comment]
@jzheaux do you have a clue of when it will be released ?

**Comment by jzheaux** [comment]
Yes, @ionutgyn, 6.3.0 should be released in May, following our [release guidelines](https://github.com/spring-projects/spring-security/wiki/Release-Schedule-Guidelines).

You are of course welcome to use the milestone releases in the meantime for your development needs so that you can be ready to go once the GA version is released.

**Comment by ionutgyn** [comment]
> Yes, @ionutgyn, 6.3.0 should be released in May, following our [release guidelines](https://github.com/spring-projects/spring-security/wiki/Release-Schedule-Guidelines).
> 
> You are of course welcome to use the milestone releases in the meantime for your development needs so that you can be ready to go once the GA version is released.

Thank you @jzheaux
