### ISSUE TITLE
Not Logout when i config spring.cloud.gateway.discovery.locator.enable is true

### ISSUE THREAD

**Issue by congnguyen1905** [spring-projects/spring-security#14577]
I using spring.cloud.gateway.discovery.locator.enable to define dynamic route in gateway (eureka micorservice).
If i config by spring.cloud.gateway.routes. everything will be oke. 
When i config like:
spring:
  cloud:
    discovery:
      reactive:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
i can't logout.
When i debugging. i see new session id, that is not in the.sessions. So make i can't logout

**Comment by jzheaux** [comment]
Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
