### ISSUE TITLE
Add a method named authenticationProviders() in HttpSecurityBuilder

### ISSUE THREAD

**Issue by ghusta** [spring-projects/spring-security#14586]
Could you consider adding a method `authenticationProviders()` in interface `HttpSecurityBuilder` ?

It could take varargs or List as parameter.

**Expected Behavior**

It would make it more obvious that HttpSecurity can accept multiple Authentication Providers.

**Current Behavior**

`httpSecurity.authenticationProvider()` must be called multiple times. The order is of course important.

Currently, `ProviderManager` already supports this behaviour, with constructors like : 

* `public ProviderManager(AuthenticationProvider... providers)`
* `public ProviderManager(List<AuthenticationProvider> providers)`

---

Related with https://github.com/spring-projects/spring-security/issues/11428 ?

**Comment by jzheaux** [comment]
Hi, @ghusta. I see your point about how taking a varargs would make the ordering clearer. I suppose the concern would be now it might seem like `authenticationProvider` and `authenticationProviders` would conflict. It wouldn't get rid of the ordering issue since I suppose you could reasonably call `authenticationProviders` and `authenticationProvider` in the same stack unless `authenticationProvider` is also deprecated.

Just curious, have you considered using `.authenticationManager` instead? As you pointed out, `ProviderManager` already communicates the possibility of multiple providers. Using this method also aligns with #11428 since that ticket indicates that `.authenticationProvider` may eventually go away.

**Comment by jzheaux** [comment]
@ghusta, good points. I think let's hold off, given that folks can already use `authenticationManager`.
