### ISSUE TITLE
Port between Spring MVC Http Api to Reactive Http API

### ISSUE THREAD

**Issue by SkepticCoder** [spring-projects/spring-security#14687]
How to convert Http Api to Reactive Http API? It would be great if we have bridge between 2 APIs

**Comment by CrazyParanoid** [comment]
You can use `ReactiveAuthenticationManagerAdapter`, what other API are you missing for your case?

**Comment by SkepticCoder** [comment]
I mean I wanna to use Firewall API for Reactive stack

**Comment by rwinch** [comment]
The firewall is primarily to ensure consistency across servlet containers. However, the Spring team already manages consistency through the WebFlux API (Spring's WebFlux creates this) and thus that consistency can be maintained there. Is there a specific feature you are looking for that you are not finding?

**Comment by SkepticCoder** [comment]
@rwinch But I see configuration to protect from external input parameters at StrictHttpFirewall

[Issue 10669 HttpFirewall interface for reactive applications #10669 (https://github.com/spring-projects/spring-security/issues/10669)](https://github.com/spring-projects/spring-security/issues/10669)
I would like to have  possibility to set up https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/web/firewall/StrictHttpFirewall.html to prevent vulnubiriteis with header and query parameters
I mean global configuration
Do you mean  [ServerWebExchangeUtils](https://github.com/spring-cloud/spring-cloud-gateway/blob/main/spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/support/ServerWebExchangeUtils.java) is already provides this functional?

**Comment by marcusdacoregio** [comment]
@SkepticCoder, as mentioned by Steve [here](https://github.com/spring-projects/spring-security/issues/10669#issuecomment-1007520958), we would need an example that demonstrates whether an application can be vulnerable to some exploit. If there is an existing attack vector, please [responsibly report the vulnerability](https://github.com/spring-projects/spring-security/security/policy).

I'll close this since there is no action issue and it has been already discussed in https://github.com/spring-projects/spring-security/issues/10669.
