### ISSUE TITLE
SEC-1249: AbstractPreAuthenticatedProcessingFilter should better support continueFilterChainOnUnsuccessfulAuthentication

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1499]
[Ray Suliteanu](https://jira.spring.io/secure/ViewProfile.jspa?name=raysuliteanu) (Migrated from [SEC-1249](https://jira.spring.io/browse/SEC-1249?redirect=false)) said:

AbstractPreAuthenticatedProcessingFilter helpfully has continueFilterChainOnUnsuccessfulAuthentication. However, the try/catch that enables the continue is not broad enough. The methods getPreAuthenticatedPrincipal() and getPreAuthenticatedCredentials() are not covered, so if, for example, when using the request header preauth and the preauth header (SM_USER or otherwise) is not found, the filter chain does not continue; you get an auth failure instead because it throws PreAuthenticatedCredentialsNotFoundException. 

The behavior I'm looking for is if AbstractPreAuthenticatedProcessingFilter.doAuthenticate() fails, the filter chain continues, whether it's getPreAuthenticatedPrincipal() or getPreAuthenticatedCredentials() or authenticationManager.authenticate() that fails. 

I don't know if you want to just extend the try/catch to cover the two get methods or have some separate configuration property, but since you already support a "continue" configuration it'd be nice to support continuing on any failure in doAuthenticate().

**Comment by spring-issuemaster** [comment]
This issue is related to #1500

**Comment by aciccarello** [comment]
I would prefer if authentication exceptions in the `getPreAuthenticatedPrinciple` call of `AbstractPreAuthenticatedProcessingFilter.doAuthenticate` were handled by the `AbstractPreAuthenticatedProcessingFilter.unsuccessfulAuthentication` method. That way errors in the `RequestHeaderAuthenticationFilter.getPreAuthenticatedPrinciple` or any other implementation would be handled in a way that is consistent with other errors. Currently a 500 error is returned rather than a  400 Bad Request which I would expect.

Currently the only way to override the current functionality is to override `doFilter` and wrap the super call in a try catch.
