### ISSUE TITLE
HttpSessionSecurityContextRepository used for AbstractPreAuthenticatedProcessingFilter

### ISSUE THREAD

**Issue by cristibozga** [spring-projects/spring-security#15041]
I think we should not use HttpSessionSecurityContextRepository  as default repository mainly if the security filter chain can be explicitly configured  as stateless

IN the version 5.7 inside AbstractPreAuthenticatedProcessingFilter we had a NullSecurityContextRepository and the comment for the setter of the repository  is : '_The default action is not to save the SecurityContext_'.
In the version 6.0 the repository is a HttpSessionSecurityContextRepository  by default but the comment of the setter of the repository still says '_The default action is not to save the SecurityContext_.'
Our configuration for the security chain contains
 .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
but I see that a SessionFaçade is created to store the security context. 

Of course, we can explicitly set the repository, but I wonder if the behavior in the 6.0 version is the desired one and which are the arguments of using the HttpSessionSecurityContextRepository .

Thanks in advance

**Comment by marcusdacoregio** [comment]
Hi, @cristibozga. That was a result of https://github.com/spring-projects/spring-security/issues/11763.

More concretely, the fact that it used to use `NullSecurityContextRepository` was misleading because previously the `SecurityContext` would get saved using `HttpSessionSecurityContextRepository` automatically with the `SecurityContextPersistenceFilter`.
When [gh-11786](https://github.com/spring-projects/spring-security/issues/11762) was resolved, it meant that any authentication needed to be persisted in the Authentication Filter. This means that to preserve the previous behavior, we needed to [update](https://github.com/spring-projects/spring-security/commit/4479cefade65333c1a60904a67d993b69b277206#diff-b9376389ef77383ad282c387359020ed122ad52d641cf25de70f104deae213d8R113) AbstractPreAuthenticatedProcessingFIlter to use `HttpSessionSecurityContextRepository`.
