### ISSUE TITLE
Does Spring Security support QR code login?

### ISSUE THREAD

**Issue by tearsmoon** [spring-projects/spring-security#15301]
Scenario: After logging in on a mobile phone, the user scans the QR code to log in to the computer's web page,
I searched once and found that I need to develop additional code myself. 
Does Spring Security support QR code login?

**Comment by sjohnr** [comment]
Thanks for getting in touch @tearsmoon, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

Having said that, please see gh-15114.
