### ISSUE TITLE
Dynamic register  SecurityFilterChain  

### ISSUE THREAD

**Issue by leshalv** [spring-projects/spring-security#15423]
I want to configure a SecurityFilterChain for each tenant. How do I do that

**Comment by marcusdacoregio** [comment]
Hi, @leshalv, thanks for reaching out. It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.

**Comment by marcusdacoregio** [comment]
In addition to that, please see https://docs.spring.io/spring-security/reference/servlet/configuration/java.html#_multiple_httpsecurity_instances
