### ISSUE TITLE
SpringSessionBackedReactiveSessionRegistry removeSessionInformation hasn't been implemented

### ISSUE THREAD

**Issue by dreamstar-enterprises** [spring-projects/spring-security#15627]
This looks like a bug:

It's the only method not implemented?

```
	@Override
	public Mono<ReactiveSessionInformation> removeSessionInformation(String sessionId) {
		return Mono.empty();
	}
```

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by marcusdacoregio** [comment]
Hi @dreamstar-enterprises, thanks for the report. Since this class is from Spring Session, the ticket should be opened on [its issue tracker](https://github.com/spring-projects/spring-session/issues).

The reason that the method does nothing is the same reason that `org.springframework.session.security.SpringSessionBackedSessionRegistry#removeSessionInformation` also does nothing. The sessions are not maintained by the session registry, instead, when using Spring Session, they are maintained by the `SessionRepository`.
