### ISSUE TITLE
Documentation ReactiveOidcSessionStrategy should be ReactiveOidcSessionRegistry

### ISSUE THREAD

**Issue by dreamstar-enterprises** [spring-projects/spring-security#15724]
I believe this documentation is wrong:

ReactiveOidcSessionStrategy should be ReactiveOidcSessionRegistry

Here:

https://docs.spring.io/spring-security/reference/reactive/oauth2/login/logout.html#_customizing_the_oidc_provider_session_strategy

My IDE could not find ReactiveOidcSessionStrategy, but it found ReactiveOidcSessionRegistry

**Comment by kse-music** [comment]
This fixed by [f372f5c](https://github.com/spring-projects/spring-security/commit/f372f5cf526edb58963a9da2619b886548986dba) and [2ba9b68](https://github.com/spring-projects/spring-security/commit/2ba9b6821a867d51c01b73e2108a1fd1472633ea)

**Comment by dreamstar-enterprises** [comment]
Thank you!

The docs still say though 'Strategy' instead of 'Registry' - see here: [ReactiveOidcSessionStrategy](https://docs.spring.io/spring-security/reference/reactive/oauth2/login/logout.html#_customizing_the_oidc_provider_session_strategy)

**Comment by jzheaux** [comment]
@dreamstar-enterprises, I believe that's because the [bug is fixed](https://github.com/spring-projects/spring-security/pull/15686) but not yet released. I'm going to close this as a duplicate; however please let me know if I've misunderstood.

We also [publish the snapshot reference](https://docs.spring.io/spring-security/reference/6.3-SNAPSHOT/servlet/oauth2/login/logout.html#_customizing_the_oidc_provider_session_registry), so you should see the correction there at this point.
