### ISSUE TITLE
Custom reactiveUserDetail or custom reactiveAuthenProvider , maximumSessions() not working 

### ISSUE THREAD

**Issue by githubanhduong** [spring-projects/spring-security#15903]
**Describe the bug**
When i custom reactiveUserDetail or custom reactiveAuthenProvider , maximumSessions() not working 

**code
@Bean
SecurityWebFilterChain filterChain(ServerHttpSecurity http) {
    http
        // ...
        .sessionManagement((sessions) -> sessions
            .concurrentSessions((concurrency) -> concurrency
                .maximumSessions(SessionLimit.of(1))
            )
        );
    return http.build();
}

**Expected behavior**
I want a user only exist a session
**Sample**

https://docs.spring.io/spring-security/reference/reactive/authentication/concurrent-sessions-control.html

**Comment by ngocnhan-tran1996** [comment]
You can find a sample in the last section and check it with your config

https://docs.spring.io/spring-security/reference/reactive/authentication/concurrent-sessions-control.html

**Comment by jzheaux** [comment]
Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.

**Comment by githubanhduong** [comment]
thank you
