### ISSUE TITLE
Commit missed of overriding WebClient in ReactiveOidcIdTokenDecoderFactory

### ISSUE THREAD

**Issue by JohnNiang** [spring-projects/spring-security#16021]
**Describe the bug**
Overriding WebClient in ReactiveOidcIdTokenDecoderFactory was implemented in one part of <https://github.com/spring-projects/spring-security/pull/14357> that had [two commits](https://github.com/spring-projects/spring-security/pull/14357/commits). But at last, only [one commit](https://github.com/spring-projects/spring-security/commit/9c352c4b4b4b853798b6ffd3c7b27f6cb51b84ce) got merged.

In <https://github.com/spring-projects/spring-security/pull/13301>, the [commit](https://github.com/spring-projects/spring-security/commit/9c352c4b4b4b853798b6ffd3c7b27f6cb51b84ce) only containing author info was merged.

**To Reproduce**

See https://github.com/spring-projects/spring-security/pull/14357#issuecomment-2443524739 for more.

**Expected behavior**

The [commit](https://github.com/spring-projects/spring-security/pull/14357/commits/566634e44e9d97213a2ba3fbce7bd060b75392fd) should be merged as well.

**Comment by jzheaux** [comment]
Hi, @JohnNiang, thanks for double-checking. The commit was not missed. It was reverted due to https://github.com/spring-projects/spring-security/issues/14178#issuecomment-2050434392.

The main concern is that it would matter for only some client registrations, causing possible confusion as to the setter's impact. You can follow that comment to see an example of how to customize `WebClient`.
