### ISSUE TITLE
Why is UsernamePasswordAuthenticationFilter a GenericFilterBean and not OncePerRequestFilter?

### ISSUE THREAD

**Issue by d3bt3ch** [spring-projects/spring-security#16052]
Why is `UsernamePasswordAuthenticationFilter` a `GenericFilterBean` and not a `OncePerRequestFilter`?

**Comment by jzheaux** [comment]
Usually old decisions like this are because there wasn't a need at the time (about 15 years ago at this point). While it's speculation on my part, since all request dispatches are worth securing, it makes sense to select `GenericFilterBean` unless there is a need to ensure that something only happens once per request.

Thanks for reaching out, @d3bt3ch. In the future. we prefer that folks post questions to [Stack Overflow](https://stackoverflow.com/) so that we can [use GitHub for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). If this is causing a bug for you or you would like to request an enhancement, please update the ticket with those details. Otherwise, feel free to post any follow-up StackOverflow link to this ticket and we can continue the conversation over there!

**Comment by rwinch** [comment]
`OncePerRequestFilter` is to ensure that the `Filter` does not process the request more than once in a single request for other dispatch types (e.g. a forward). This is useful for `Filter`s that process every request like `HeadersWriterFilter`. However, `UsernamePasswordAuthenticationFilter` only processes on a single URL, so it is it will not process other dispatch types unless the URL matches in which case it probably should.

**Comment by d3bt3ch** [comment]
> `OncePerRequestFilter` is to ensure that the `Filter` does not process the request more than once in a single request for other dispatch types (e.g. a forward). This is useful for `Filter`s that process every request like `HeadersWriterFilter`. However, `UsernamePasswordAuthenticationFilter` only processes on a single URL, so it is it will not process other dispatch types unless the URL matches in which case it probably should.

This can be achieved through `OncePerRequestFilter` as well. For example the filters for `Authorization Server` uses `OncePerRequestFilter`
