### ISSUE TITLE
SEC-1505: Generic-enabled Authentication interface

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1731]
[Keith Donald](https://jira.spring.io/secure/ViewProfile.jspa?name=kdonald) (Migrated from [SEC-1505](https://jira.spring.io/browse/SEC-1505?redirect=false)) said:

Something like this would be nice:

```
   @RequestMapping(value="/twitter", method=RequestMethod.GET)
    public String twitterConnectView(Authentication<GreenhouseUserDetails> auth) {
        if (isConnected(auth.getPrincipal())) {
            return "/settings/twitterConnected";
        } else {
            return "/settings/twitterConnect";
        }
    }

    private boolean isConnected(GreenhouseUserDetails principal) {
        return false;
    }
```

**Comment by rwinch** [comment]
I don't think we are going to do this because you can already use [`@AuthenticationPrincipal`](https://docs.spring.io/spring-security/site/docs/5.5.x/reference/html5/#mvc-authentication-principal) to resolve the principal without reference to the `Authentication` object. This is the preferred approach since you don't need to depend on any Spring Security classes.
