### ISSUE TITLE
SEC-1817: FilterBasedLdapUserSearch requires BaseLdapPathContextSource but never uses it

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2047]
[Michael Osipov](https://jira.spring.io/secure/ViewProfile.jspa?name=michael-o) (Migrated from [SEC-1817](https://jira.spring.io/browse/SEC-1817?redirect=false)) said:

The constructor signatures is

```
 public FilterBasedLdapUserSearch(String searchBase, String searchFilter, BaseLdapPathContextSource contextSource)
```

but contextsource is assigned to `
 private ContextSource contextSource
`. This constraint seems to be superfluous.
ContextSource would suffice in the constructor.

**Comment by bmcguire** [comment]
Sorry to resurrect a very old issue but I think I have a valid use case for this change. My security setup is to use the FilterBasedLdapUserSearch along with the org.springframework.security.ldap.userdetails.LdapUserDetailsService and the org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationProvider

In my case the user is already authenticated from a proxy in front of my applications so I'm getting the username only and not needing to go through the BindAuthenticator 
 which was mentioned at #2090. I would still like to use the pooling provided by org.springframework.ldap.pool.factory.PoolingContextSource but can not because of the current constructor.

Hoping you see this as an acceptable use case for make the code change.
