### ISSUE TITLE
SEC-1862: AbstractAuthorizeTag must search in web application context to find bean

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2096]
[Thomas Champagne](https://jira.spring.io/secure/ViewProfile.jspa?name=lafeuil) (Migrated from [SEC-1862](https://jira.spring.io/browse/SEC-1862?redirect=false)) said:

If you configure your webapp with the following configuration : 

``` xml
<sec:http security="none" pattern="/static/**/*"/>
```

``` xml
<http auto-config='true'>
  <intercept-url pattern="/**" access="ROLE_USER" />
</http>
```

The JspAuthorizeTag generates an exception, because it doesn't find the WebInvocationPrivilegeEvaluator. It searches only in the root application context and there isn't this bean. 

```
java.io.IOException: No visible WebInvocationPrivilegeEvaluator instance could be found in the application context. There must be at least one in order to support the use of URL access checks in 'authorize' tags.
    org.springframework.security.taglibs.authz.AbstractAuthorizeTag.getPrivilegeEvaluator(AbstractAuthorizeTag.java:332)
    org.springframework.security.taglibs.authz.AbstractAuthorizeTag.authorizeUsingUrlCheck(AbstractAuthorizeTag.java:207)
    org.springframework.security.taglibs.authz.AbstractAuthorizeTag.authorize(AbstractAuthorizeTag.java:107)
```

I think the JspAuthorizeTag should also search in the web application context. 
In the code, at line 311 in class org.springframework.security.taglibs.authz.AbstractAuthorizeTag, the application context should be found with org.springframework.web.servlet.support.RequestContextUtils.getWebApplicationContext(ServletRequest, ServletContext) method.

**Comment by splashvarun** [comment]
@spring-issuemaster 

Can you recheck this issue. Currently, it is possible to define the http element in the web application context. In my project, I am defining all web related configuration, with security and authorization beans in the web application context. Currently, to overcome the issue of this tag, I had to extend and create my own version of the JspAuthorizeTag with only one change. 

Instead of doing as follows: `ApplicationContext ctx = SecurityWebApplicationContextUtils.findRequiredWebApplicationContext(getServletContext());`

I am doing this: `ApplicationContext ctx = RequestContextUtils.findWebApplicationContext((HttpServletRequest)getRequest(), getServletContext());`

Above changes in the core file can be done without any issue and should work for both context cases.

**Comment by rwinch** [comment]
@splashvarun Thanks for the report, but this issue is closed since 2011. Please create a new ticket
