### ISSUE TITLE
SEC-1945: Encapsulation of Pre/PostAuthorize expressions in custom annotations and combining them on methods

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2171]
[Jan Novotný](https://jira.spring.io/secure/ViewProfile.jspa?name=novoj) (Migrated from [SEC-1945](https://jira.spring.io/browse/SEC-1945?redirect=false)) said:

I would like to raise an idea for further discussion. When using PreAuthorize / PostAuthorize annotations on methods in a larger scale there is a lot of redundancy and repetition of some expression parts. This makes code less readable and might introduce bugs just because developer looses perspective on the code. I described my idea in more detail in article on my blog and would be happy if it would inspire you somehow to extend current features of Spring Security. If you wouldn't consider it to be a good idea, please close this issue immediately.

http://blog.novoj.net/2012/03/27/combining-custom-annotations-for-securing-methods-with-spring-security/

Thank you for your time.

Might be connected in certain aspects with these issues:
https://jira.springsource.org/browse/SEC-1629
https://jira.springsource.org/browse/SEC-1796

**Comment by mansiganatra** [comment]
Are there any updates on the addition of this feature?

**Comment by albertocavalcante** [comment]
Is there any update on this or is there currently another way to achieve this?

**Comment by jzheaux** [comment]
Spring Security's method security support has evolved a great deal since this ticket was first posted. For example, now you can create an annotation composed of several other annotations like this:

```java
@PreAuthorize(...)
@PostAuthorize(...)
@AuthorizeReturnObject
public @interface MyAuthorize {}
```

You can also use templates in your SpEL expression:

```java
@PreAuthorize("hasAuthority('SCOPE_{scope}')")
@PostAuthorize(...)
@AuthorizeReturnObject
public @interface MyAuthorize {
    String scope();
}
```

And refer to beans in your expression:

```java
@PreAuthorize("@remoteAuthz.check('{scope}')")
@PostAuthorize(...)
@AuthorizeReturnObject
public @interface MyAuthorize {
    String scope();
}
```

Given that, I think this addresses the majority of what was wanted here, so I'm going to close. If there is something still missing, please feel free to add more detail and we can look at adding to #14595. For now, please read [the updated method security documentation](https://docs.spring.io/spring-security/reference/6.3-SNAPSHOT/whats-new.html#_authorization) for a detailed overview of what is supported today.
