### ISSUE TITLE
SEC-2109: Custom socket factory in ActiveDirectoryLdapAuthenticationProvider

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2312]
[Davide Angelocola](https://jira.spring.io/secure/ViewProfile.jspa?name=dfa) (Migrated from [SEC-2109](https://jira.spring.io/browse/SEC-2109?redirect=false)) said:

Actually there is no way to specify a custom socket factory in _ActiveDirectoryLdapAuthenticationProvider_ (property `java.naming.ldap.factory.socket` of _DirContext_).

It could be useful for a number of reasons as described by
http://docs.oracle.com/javase/jndi/tutorial/ldap/security/ssl.html (section "Using Custom Sockets").

**Comment by sksjava** [comment]
Not sure why the issue is still not progressed. This is a valid issue and causes inconviniece when developing multiple softwares running on same JVM and are connecting do different URLs over SSL.

The current implementation is not allowing the software to process LDAPS without having to override the JVM truststore parameters. This causes issues if there are multiple application installed on the same server having different truststores.

**Comment by nE0sIghT** [comment]
This is very important feature that will allow to properly validate custom enterprise certificates.
We can introduce some method to set ```SSLSocketFactory``` name and later use it in ```bindAsUser()```.

**Comment by rwinch** [comment]
@nE0sIghT  Thanks for the feedback.

I think what we should do is allow leverage a `ContextSource.getContext(String principal, String credentials)` implementation to resolve the DirContext for `ActiveDirectoryLdapAuthenticationProvider.bindAsUser`. Users wishing to customize the environment could inject a custom ContextSource. 

If you are interested in submitting a Pull Request, please do so!

**Comment by rwinch** [comment]
Closing in favor of #5674 since it is a PR
