### ISSUE TITLE
SEC-2678: Remove default HSTS header to avoid accidental DoS of HTTP content

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2898]
[David Eckel](https://jira.spring.io/secure/ViewProfile.jspa?name=dvdckl) (Migrated from [SEC-2678](https://jira.spring.io/browse/SEC-2678?redirect=false)) said:

It is trivial to cause an outage of HTTP-only (insecure) content for an entire domain it is hosted on if you deploy an application using Spring Security 3.2+ due to the addition of Strict-Transport-Security by default.  It is not intuitive that explicit configuration of security headers is necessary to support HTTP only pages in the same application and in the same domain.

Unlike the other security headers, HSTS affects an entire domain and not just the current URL, and HSTS is cached (currently set to 1 year), making it impossible to restore HTTP functionality for that domain once a browser has been served the HSTS header.  This could be disastrous for domains with HTTP-only pages, far worse than the SSL-stripping vulnerability that HSTS mitigates.  We have had this happen to us, causing requests to our webapps that redirect from HTTPS to HTTP to go into infinite redirect loop after a user visited an unrelated application under the same domain that set HSTS after it upgraded to Spring Security 3.2.

To avoid this risk, please remove the call to `httpStrictTransportSecurity()` in https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/annotation/web/configurers/HeadersConfigurer.java#L239 (added by SEC-2116), and update documentation to reflect that this is an opt-in header, not opt-out.

**Comment by TinCongHuynh** [comment]
It seems that we could not disable HSTS header in default end point /oauth/token of spring oauth2 with the below source code.

@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
        @Override
        protected void configure(HttpSecurity http) throws Exception {
            http
            // ...
            .headers()
                .httpStrictTransportSecurity().disable();
        }
}
Anyone can help me ?

**Comment by dvdckl** [comment]
We just experienced a self-inflicted DoS because of this issue.  Again.  One of our teams wasn't aware of this default Spring Security behavior after an upgrade.  Our CS reps now need to educate users on how to get out of this state when trying to navigate to properties that aren't HTTPS compatible yet.

The documentation update and warning on startup for same-app mixing of HTTP and HTTPS isn't sufficient to handle the multi-webapp case using a shared host.  @rwinch I hope you'll reconsider your stance on this.

**Comment by dvdckl** [comment]
@rwinch We discovered another team and webapp on our shared domain has fallen victim to accidentally setting the HSTS header via Spring Security.  And this is a team made up of Spring and appsec experts that are well aware of how HSTS works, they just didn't catch this side effect of the headers() call.  A warning in documentation is insufficient to prevent outages due to this.

While we are trying to move more web pages to HTTPS, external dependencies that don't support HTTPS yet are getting in the way.  We also have use cases where we do not want to move some content to HTTPS because we want to take advantage of HTTP transparent caching proxies, especially for mobile and in developing countries.

I understand the aversion to opt-in security, and the philosophy of promoting HTTPS.  But I hope everyone can see that HSTS by default is causing more damage than TLS stripping attacks.  It behaves very differently than other security headers, and warrants a different default behavior than other security headers.
