### ISSUE TITLE
SEC-2744: BasicAuthenticationFilter decodes the Passwords with UTF-8

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2969]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=robwinch) (Migrated from [SEC-2744](https://jira.spring.io/browse/SEC-2744?redirect=false)) said:

All browser encode the Password in BasicAuthentification in ISO-8859-1.

See: Stackoverflow Discussion http://stackoverflow.com/questions/7242316/what-encoding-should-i-use-for-http-basic-authentication

The [BasisAuthentificationFilter](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilter.java) explicitly decodes using UTF-8.

This broke Authentification with Umlauts in the password (example: passwordöäü) for me.

Further Analysis:
Chrome encodes the AuthentificationInfo with UTF-8
Firefox and IE use ISO8859-1

private String[] extractAndDecodeHeader(String header, HttpServletRequest request) throws IOException {

    byte[] base64Token = header.substring(6).getBytes("UTF-8");

**Comment by Martin-Wegner** [comment]
The bug is still present.
A password with umlauts works only in Chrome but not in Firefox or Internet Explorer.

But the problem is not `byte[] base64Token = header.substring(6).getBytes("UTF-8");` because a Base64 token only contains encoding independent characters (you can use every encoding you want). 

The problem is another and results in a draft:
https://tools.ietf.org/id/draft-reschke-basicauth-enc-00.html

So the solution should be:

> On the other hand, the strategy below may already improve the user-visible behavior today:
> 
> In the first authentication request, choose the character encoding based on the user's credentials: if they do not need any characters outside the ISO-8859-1 character set, default to ISO-8859-1, otherwise use UTF-8.
> If the first attempt failed and the encoding used was ISO-8859-1, retry once with UTF-8 encoding instead.

I created a PR:
https://github.com/spring-projects/spring-security/pull/3966

**Comment by Martin-Wegner** [comment]
@jgrandja can you close this issue please?

**Comment by jgrandja** [comment]
@Martin-Wegner For sure.

**Comment by jgrandja** [comment]
A solution to this Issue can be found [here](https://github.com/spring-projects/spring-security/pull/3966#issuecomment-242123838)
