### ISSUE TITLE
SEC-2799: Provide an easy way to configure HttpSecurity from another configuration

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3022]
[cemo koc](https://jira.spring.io/secure/ViewProfile.jspa?name=cemokoc) (Migrated from [SEC-2799](https://jira.spring.io/browse/SEC-2799?redirect=false)) said:

We are migrating our architecture to Spring Boot and we have some issues. I want to add some filters from autoconfiguration classes. However I could not find an easy way to add another security filter. I have to use reflection and the only solution I can do currently is something like this: 

```
@Configuration
public class Test implements  WebSecurityConfigurer<WebSecurity> {

   @Autowired
   WebSecurityConfigurerAdapter configurerAdapter;

   @Override
   public void configure(WebSecurity builder) throws Exception {
      //access by reflection
   }

   @Override
   public void init(WebSecurity builder) throws Exception {
   }

}

```

Please provide an easy way to configure filters.

**Comment by ghillert** [comment]
@rwinch Found the need for this requirement as well. For when Spring Cloud Data Flow runs inside Cloud Foundry, I have to make minor tweaks to the existing security setup from a secondary configuration class. It seems that right now reflection is the only way to retrieve the `HttpSecurity` object from the injected `WebSecurityConfigurerAdapter`.

**Comment by rwinch** [comment]
The `HttpSecurity` should not be accessed by other Configurations because it will cause ordering issues. We cannot force the external Configuration to be ran before Spring Security builds the `HttpSecurity` object.

Instead, you should use logic like this https://github.com/spring-projects/spring-security/issues/3022#issuecomment-180603538

Alternatively, you can encapsulate your logic in a DSL which has access to the entire Spring `ApplicationContext` using https://docs.spring.io/spring-security/site/docs/4.2.x/reference/html/jc.html#jc-custom-dsls
