### ISSUE TITLE
JavaConfig of AuthenticationProvider ignored

### ISSUE THREAD

**Issue by whittle** [spring-projects/spring-security#3698]
I have created a minimal application demonstrating what I believe to be a bug in Spring Security’s JavaConfig, where a custom AuthenticationProvider is explicitly configured on both the HttpSecurity and the AuthenticationManagerBuilder, but is ignored. The demonstration can be found at https://github.com/whittle/secbug.

**Comment by rwinch** [comment]
Thanks for the report @whittle! 

Can you explain why you think this is not working? The reason I ask is that when you use the protected method the AuthenticationManagerBuilder is not scoped so that Boot can see it. This means Spring Boot will expose a default AuthenticationManager still. However, authentication to your `HttpSecurity` endpoints should still be done using the configuration you provided. If you want Boot to be aware of your configuration you can use:

```java
@Autowired
public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
...
}
```

**Comment by whittle** [comment]
@rwinch Thank you for your response. I had thought there must be a bug because I couldn’t imagine a legitimate case where two different AuthenticationManagerBuilders would co-exist. Your solution worked for me, and your explanation made Spring scoping a little clearer to me. Thank you.
