### ISSUE TITLE
Spring security issue with credentials

### ISSUE THREAD

**Issue by Jayarammohan** [spring-projects/spring-security#3732]
I am able to reproduce the problem with a very simple java,spring, spring security application which practically does nothing except for authenticating.
user name = optus, password = candidates
in curl command,  --user optus:candidates works fine
But, instead with    the Base 64 equivalent, -H"Authorization: Basic b3B0dXM6Y2FuZGlkYXRlcw==", works fine too.
However, the last character, instead of "=", if I change it to any other alphanumeric character, still works, for instance, if I change that into   -H"Authorization: Basic b3B0dXM6Y2FuZGlkYXRlcw=1"   or-H"Authorization: Basic b3B0dXM6Y2FuZGlkYXRlcw=a",  it still works fine. But, it should not. It should say invalid credentials.

**Comment by shazin** [comment]
`=` in Base 64 is just padding, `b3B0dXM6Y2FuZGlkYXRlcw` what matters because it contains the String "optus:password".

Try decoding `b3B0dXM6Y2FuZGlkYXRlcw=1` and `b3B0dXM6Y2FuZGlkYXRlcw=a` at https://www.base64decode.org/ it will still return the correct String "optus:password". The String will be manupilated and the Spring Security will throw Bad Credentials exception only if `b3B0dXM6Y2FuZGlkYXRlcw` is changed. 

This is not an issue/

**Comment by Jayarammohan** [comment]
Ok, thank you very much,   Jaya

**Comment by rwinch** [comment]
Thanks for answering this so fast @shazin ! 

Per the previous comments, I'm closing as invalid
