### ISSUE TITLE
Fix Javadoc AbstractPreAuthenticatedProcessingFilter continueFilterChainOnUnsuccessfulAuthentication to state default as true

### ISSUE THREAD

**Issue by TheGreatYamcha** [spring-projects/spring-security#3760]
This is from AbstractPreAuthenticatedProcessingFilter:
`private boolean continueFilterChainOnUnsuccessfulAuthentication = true;`
however javadoc says it is false:
`/**
     * If set to {@code true}, any {@code AuthenticationException} raised by the
     * {@code AuthenticationManager} will be swallowed, and the request will be allowed to
     * proceed, potentially using alternative authentication mechanisms. If {@code false}
     * (the default), authentication failure will result in an immediate exception.
     *
     * @param shouldContinue set to {@code true} to allow the request to proceed after a
     * failed authentication.
     */
    public void setContinueFilterChainOnUnsuccessfulAuthentication(boolean shouldContinue) {
        continueFilterChainOnUnsuccessfulAuthentication = shouldContinue;
    }`

**Comment by rwinch** [comment]
@TheGreatYamcha Thanks for the report! Any chance you would be interested in sending a Pull Request fixing the javadoc?

**Comment by TheGreatYamcha** [comment]
Unfortunately not. But I would suggest fixing the code instead of the javadoc. Otherwise, you'll be technically breaking backwards compatibility.

**Comment by rwinch** [comment]
@TheGreatYamcha Thank you for the fast response and the suggestion.

Before I responded to you, I did a little investigation and found that the javadoc has been incorrect since it was added and the default value for `continueFilterChainOnUnsuccessfulAuthentication ` has always been true. Let me share my findings:

* the default value for `continueFilterChainOnUnsuccessfulAuthentication ` is true in [3.3.0.RELEASE](https://github.com/spring-projects/spring-security/blob/3.0.0.RELEASE/web/src/main/java/org/springframework/security/web/authentication/preauth/AbstractPreAuthenticatedProcessingFilter.java#L55).
* The javadoc was added incorrectly stating the default being false in [ee1fd1bc](https://github.com/spring-projects/spring-security/commit/ee1fd1bc50a7232617a4668c4fcd450958cab437). This was first released in 3.1.0.M1. So this means that the javadoc has always been inconsistent with the behavior.
* Prior to that `AbstractPreAuthenticatedProcessingFilter` was [moved](https://github.com/spring-projects/spring-security/commit/bec84f874a3d0dae963a47df62a4b554da29596e) from package `~.ui.preauth` to `~.web.authentication`. You will notice [the default value for continueFilterChainOnUnsuccessfulAuthentication](https://github.com/spring-projects/spring-security/commit/bec84f874a3d0dae963a47df62a4b554da29596e#diff-a960f0b8648613e74475b6bcaed07c3fR49) is true at this time too.
* Version 2.0.3 does not contain [continueFilterChainOnUnsuccessfulAuthentication](https://github.com/spring-projects/spring-security/blob/2.0.3/core/src/main/java/org/springframework/security/ui/preauth/AbstractPreAuthenticatedProcessingFilter.java) 
* Version 2.0.4 has [continueFilterChainOnUnsuccessfulAuthentication with a default value of true](https://github.com/spring-projects/spring-security/blob/2.0.4/core/src/main/java/org/springframework/security/ui/preauth/AbstractPreAuthenticatedProcessingFilter.java#L49). This means that the since the very first release `continueFilterChainOnUnsuccessfulAuthentication` has had a default of true.
* Commit [4bb3eb1](https://github.com/spring-projects/spring-security/commit/4bb3eb12c34781a08e76510b85ef09ec3c09e693) was performed on Jul 30, 2008 which added `continueFilterChainOnUnsuccessfulAuthentication` with the default value of `true`. This means the default value has always been true and has been so for nearly 8 years.

Based on these findings, we need to change the javadoc to remain passive and leave the default value as true.

**Comment by filiphr** [comment]
I bumped into this as well recently. The Javadoc of the class is correct, but the javadoc of the setter method is not. 

It would be good if the Javadoc can be changed

**Comment by eleftherias** [comment]
@filiphr I know this is an older issue, but are you interested in sending a PR for fixing the setter Javadoc?

**Comment by filiphr** [comment]
Sure @eleftherias. Just pushed https://github.com/spring-projects/spring-security/pull/7561. Not sure if this is what you expected
