### ISSUE TITLE
HttpServlet3RequestFactory creates a request wrapper that always has a non-null AsyncContext

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-security#3780]
I'm not sure what the spec says, but Tomcat (at least) makes an assumption that if the async context is not null then an async request is in process. Spring Security fools it into thinking this is the case and prevents the response from being rendered.

This line here is the culprit: https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/servletapi/HttpServlet3RequestFactory.java#L180. It should check for null and return that before wrapping.

**Comment by rwinch** [comment]
@dsyer Thanks for the report. This seems to be a bug in Tomcat. The [javadoc states](http://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getAsyncContext()):

> IllegalStateException - if this request has not been put into asynchronous mode

Since this is an easy workaround, I went ahead and pushed a workaround for this into master.

**Comment by nenaraab** [comment]
@rwinch 

Dear Rob,

could you downport this change to version 3.2.10 as well?
Affected branches might be: 3.2.x and 4.0.x .

Version 3.2.10 is used by the latest spring-security-oauth2 library version [2.3.3.RELEASE](https://mvnrepository.com/artifact/org.springframework.security.oauth/spring-security-oauth2/2.3.3.RELEASE).

And we would like to increase the version of Spring framework to 4.3.16 because of these security patches:
https://spring.io/blog/2018/04/05/multiple-cve-reports-published-for-the-spring-framework

Thank you!

**Comment by rwinch** [comment]
@nenaraab If you were to submit a PR for 3.2.x I would merge it. However, I'm not sure when (if) the next release will be made.

NOTE: You can safely using Spring Security 4.x and 5.x with Spring Security OAuth. I would recommend upgrading since Spring Security 3.2.x is no longer supported.

**Comment by nenaraab** [comment]
@rwinch 

in deed, you're right - I could detect and fix an incompatible use on my side.

This combination is working for me:
Spring Security `4.2.6` and spring Security OAuth2 `2.0.15`
