### ISSUE TITLE
Authentication required unexpectedly when send request to GET endpoint

### ISSUE THREAD

**Issue by keik** [spring-projects/spring-security#3783]
My security config is like following:

```java
	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
				.csrf().disable()

				.authorizeRequests()
				.antMatchers(HttpMethod.POST, "/authentication_test").authenticated()
				.anyRequest().permitAll();
	}
```

Reproduce order:

1. Make first request to `GET /authentication_test` and the request is not required authentication expectedly.
2. Make second request to `POST /authentication_test` and the request is required authentication expectedly.
3. Make third request to `GET /authentication_test` and the request is **required authentication unexpectedly**.

According to my analysis, second request make `SavedRequest` on `RequestCache` and `RequestCacheAwareFilter` become active. But `RequestCacheAwareFilter` regard third request with GET method as same as `SavedRequest` with POST method which created from second request,
because of the implementation of [`DefaultSavedRequest#doesRequestMatch`](https://github.com/spring-projects/spring-security/blob/4.0.4.RELEASE/web/src/main/java/org/springframework/security/web/savedrequest/DefaultSavedRequest.java#L197-L200).

I tried to change implementation of [`DefaultSavedRequest#doesRequestMatch`](https://github.com/spring-projects/spring-security/blob/4.0.4.RELEASE/web/src/main/java/org/springframework/security/web/savedrequest/DefaultSavedRequest.java#L197-L200) like:

```diff
-       if (!"GET".equals(request.getMethod()) && "GET".equals(method)) {
+       if (!propertyEquals("method", this.method, request.getMethod())) {
            return false;
        }
```
but the above fix cannot handling redirect request from  `SavedRequestAwareAuthenticationSuccessHandler` correctly because redirect request is used GET method.

I think we must distinguish GET request from (*normal request* | *redirect request*), but I don't know how to. Any ideas? Or this behavior is in design?

Thanks.

**Comment by rwinch** [comment]
@keik Thanks for reaching out! This is due to Spring Security's [RequestCache](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#request-caching). 

The intention is this:

* A user is unauthenticated but requires authentication and submits a POST form
* Spring Security saves the request to "replay" later after the user authenticates.
* The user authenticates. After authentication, Spring Security will redirect the user to the URL of the original request.
* `RequestCacheAwareFilter` will see that the URL matches and "replay" the original request of a POST even though the browser submitted a GET.

If you do not want this to happen you have a few options:

Configure the `RequestCache` to only happen for GET's

```java
requestCache.setRequestMatcher(new AntPathRequestMatcher("/**", "GET"));
http
	.requestCache()
		.requestCache(requestCache)
		.and()	...
```

Disable the request cache

```java
http
	.requestCache()
		.requestCache(new NullRequestCache())
		.and()
	...
```

Write a custom `RequestCache` and configure it as shown above.

**Comment by rwinch** [comment]
Closing this as resolved. If you disagree, feel free to reopen

**Comment by keik** [comment]
I accepted the behavior is in design.
Thanks your tips and please excuse my poorly understanding :flushed:

**Comment by rwinch** [comment]
Not a problem. Thanks for the detailed question :)
