### ISSUE TITLE
Inconsistent default logout behavior

### ISSUE THREAD

**Issue by pedrosans** [spring-projects/spring-security#3902]
### Summary

According to spring security guide at [1], the default logout behavior should be a redirect to /login?logout, but the default behavior is currently a "no content" HTTP response, registered at HttpBasicConfigurer#registerDefaultLogoutSuccessHandler  

1 - http://docs.spring.io/spring-security/site/docs/current/guides/html5//form.html
  Snippet: "when we successfully logout, redirect the browser to /login?logout (since we have not specified otherwise)"

### Actual Behavior

the behavior described in the guide and the actual default one don't match

### Expected Behavior

that the guide and the actual default logout behavior are consistent

### Configuration

all default configurations in the guide

### Version

4.1.0.RELEASE

### Sample

not included

**Comment by rwinch** [comment]
@pedrosans Thanks for reporting this issue.

How are you reproducing the issue? Depending on how you are reproducing it, this might be a documentation issue rather than a bug in the code.

Spring Security does content negotiation with the log out. If it looks like a REST request a "no content" response is provided. This is because most REST clients will not want a redirect.

**Comment by pedrosans** [comment]
Got it, it looks like a documentation issue indeed.

Can be reproduced sending a POST request to logout URL as described at [1], while using the default HttpSecurity configuration at [2]. 

On a side note, as I intended/expected the default behavior described at [2] "redirect the browser to /login?logout", I set SimpleUrlLogoutSuccessHandler to handle the success logouts and my app is OK.

e.g.
...
          .logout().logoutSuccessHandler(new SimpleUrlLogoutSuccessHandler()).permitAll().and()
...


1 - http://docs.spring.io/spring-security/site/docs/current/guides/html5//helloworld-javaconfig.html

    <c:url var="logoutUrl" value="/logout"/>
    <form class="form-inline" action="${logoutUrl}" method="post">
      <input type="submit" value="Log out" />
      <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
    </form>

2 - http://docs.spring.io/spring-security/site/docs/current/guides/html5//form.html

**Comment by rwinch** [comment]
@pedrosans Thanks again for the report and the additional details! This was a bug. A browser (unless you were sending custom Accept header) should get a 302 not the 204.

This should be fixed in master now. The fix is to ensure that if the request matches text/html that a 204 will not be sent when using the default configuration.
