### ISSUE TITLE
Secure defaults for password length

### ISSUE THREAD

**Issue by javabeanz** [spring-projects/spring-security#3914]
### Summary

Implementors of AuthenticationProvider should apply secure defaults for password validation, such as minimal and maximal length, and perhaps complexity or entropy. the UserDetailsChecker is not the right place to do this, this only checks persistent information.

### Actual Behavior

There is no default check on password length, possibly leading to insecurity by default, and possibly
Denial Of Service because of the systems in the backend involved (with extremely long passwords or normal length passwrods authentication request flooding).

### Expected Behavior

Applying solid secure defaults to prevent backend systems overload. Shouldnt the principle of Secure Defaults be mandatory for all Spring Security components ?

**Comment by rwinch** [comment]
@javabeanz Thanks for the report!

`AuthenticationProvider` is not the correct place to do this. The problem is that `AuthenticationProvider` is validating the password that is set and we do not know what the value is at this point. If the password is set to `password` and `AuthenticationProvider` rejects authentication because the user typed `password` (which is the correct password), then how would the user authenticate?

Instead, password strength needs to be done at the time of password creation.

A difficulty for this is that password strength is notoriously difficult, error prone, and organization specific. Without an industry standard on this, I don't think Spring Security can provide value.

For all of these reasons I'm going to close this as won't fix.

**Comment by rwinch** [comment]
Thanks for following up. How does the attack work?

**Comment by javabeanz** [comment]
The authentication service is flooded with authentication requests; because they are not filtered, they all go to the backend, draining resources.

**Comment by rwinch** [comment]
If you are writing a custom authentication service that gets flooded it is really up to that service to determine if it is flooded. You can always mark the UserDetails as locked and Spring Security will handle that appropriately.

**Comment by javabeanz** [comment]
Hi Rob,

Authentication services are usually a remote service, so relying on that
service to validate the length of a password is too late. this is my last
attempt to get some serious attention to this issue.

**Comment by rwinch** [comment]
@javabeanz Thanks for the response. Without some sort of standard this sort of logic does not belong in the framework. Instead this is a case where you should extend the framework to meet your needs.
