### ISSUE TITLE
SessionInformation add constructor

### ISSUE THREAD

**Issue by AndreyOsadchuk** [spring-projects/spring-security#3967]
Good day!
Could you add to this class (org.springframework.security.core.session.SessionInformation) constructor by default or better write a interface and work throw interface in new release?
Cause: I want use my own Session entity and storing it in pool & DB (Hibernate).
Thanks a lot.

**Comment by rwinch** [comment]
@AndreyOsadchuk Thank you for the question.

I don't think this is necessary and we don't want to compromise the design because of an ORM.

You can always do something like this:

```java
@Entity
public class JpaSessionInformation {

    public SessionInformation toSessionInformation() {
        ...
    }
}
```

Your `SessionRegistry` would use the `JpaSessionInformation` to save to the database and then convert it into the `SessionInformation` used by Spring Security's API.

I'm closing this as it appears answered. If you have follow up questions, feel free to respond, re-open, or create a new ticket
