### ISSUE TITLE
Please provide a built in method to retrieve the currently logged in user id

### ISSUE THREAD

**Issue by acrolink** [spring-projects/spring-security#4025]
It is possible to get the user name using:

```
Object principal = SecurityContextHolder.getContext().getAuthentication().getPrincipal();
String username = ((UserDetails)principal).getUsername();
```

But there is no direct way to get the user id of the authenticated user. Please consider adding that.

**Comment by KyleMoser** [comment]
There is no direct way to get a username because the Authentication interface doesn't even require that there _is_ a username. It's only possible to get the username the way you did it because your `Authentication` principal is a UserDetails object. But the principal isn't required to be any specific type, so how would you suggest that the framework implement your requirement?

**Comment by eleftherias** [comment]
Thank for reaching out.
As the poster above mentions, the authentication principal can be any object and is not required to have a username.

Spring Security does provide an [`@AuthenticationPrincipal` annotation](https://docs.spring.io/spring-security/reference/servlet/integrations/mvc.html#mvc-authentication-principal), which might be what you're looking for.
It can take a SpEL expression as a parameter to resolve the principal.

For example, the code you shared could be rewritten as follows:
```java
@GetMapping("/test")
public String test(@AuthenticationPrincipal(expression = "username") String name) {
	return name;
}
```
