### ISSUE TITLE
support rest api authentication based on username and password

### ISSUE THREAD

**Issue by magicalne** [spring-projects/spring-security#4075]
After watching "the State of Securing RESTful APIs with Spring", I'm thinking that is securing rest api with username and password based authentication good, or good enough?  I did consider make rest api stateful was bad thing. But after watching this video, I realize stateful is good.
I understand I can use form-login and implement success/failure handler to make it work. But it's still not convenient.  Also I know I can just use basic auth directly, but I don't want to store the token in my frontend and set it into my header in every request. 
So, my question is, is it a really bad idea to use "username and password" in rest api? Would you please tell me the reason? I really want to know. If not, would you please consider to support this function or anything make it more convenient. And I don't find anything about it in the doc, so maybe the doc needs to be updated.
Thanks.

**Comment by BGligorijevic** [comment]
Hi magicalne,

Using basic auth - username and password is bad, in my opinion.

You have basically two options:
1. Keep back-end stateless (e.g. using JWT Token)
2. Keep back-end stateful - keeping session of the user somewhere in memory (REDIS or whatever)

The problem with using basic auth (username and password) is you have to send it with every request, if you want your back-end to remain stateless. That is basically the same principle as when sending the token, but only worse - because you are sending password with every request, meaning you need to store the password on the front-end somewhere all the time - and this is bad, even if you encrypt it. You certainly do not want user typing password for every post request - do you?

I would advise you to read a bit about JWT (https://jwt.io) - this way you get the stateless back-end and only have to store the token in the front-end (e.g. local storage of HTML5).

The idea behind is simple:
You authenticate once using username and password and get the token generated for you back from the server. No token is saved on the back-end.
This token is saved in the front-end and is basically like a temporary key for the user. Whenever you want to "unlock" some REST API function, you must hand the key in the header. When the back-end receives the key, he knows exactly who the user is.

Hope it helps you, good luck!

Cheers,
Boris

**Comment by magicalne** [comment]
Hi BGligorijevic,
I think I make you misunderstand. Actually I'm not talking about basic authentication. I'm talking about form-login with rest api. After login successfully, the API requests can use valid jsessionId. So I don't need to set the header for every request. 
Suppose your spring boot config looks like:
```java
@Override
protected void configure(HttpSecurity auth) throws Exception {
    auth.formLogin().successHandler(return200Handler).failureHandler(return401Handler);
}
```
I just want to know is it a right way to do that? Since form-login can be used in jsp, so does it mean that it makes sense to use form-login in stateful rest api?

**Comment by BGligorijevic** [comment]
Hi magicalne,

If I understand you right - you are only asking if using form submit to send the data to the back-end is all right when you already have stateful REST API in place? Of course it is all right, you do not have to have REST method for login, you can use form submit for that purpose, whether its written in JSP or HTML or whatever, the browser does the post to the server for you in the end.

**Comment by magicalne** [comment]
Thanks for your explanation. Now I just hope spring security could point it out in the docs.  And it will be great if there's a method to integret httpBasic and form-login.

**Comment by rwinch** [comment]
The key is that you should exchange your long term credentials (i.e. username / password) for a short term credential. This could be a session id or it could be a JWT token. I would consider using a session rather than JWT because session has state and JWT does not.

You can provide the username / password using Basic and then receive a session id for subsequent requests. Alternatively, you could do the same thing with Form Login. It is really up to you.

**Comment by magicalne** [comment]
That is exactly what I want to know! Thanks a lot.
