### ISSUE TITLE
WebSecurityConfiguration should autowire PermissionEvaluator the same way GlobalMethodSecurityConfiguration does

### ISSUE THREAD

**Issue by candrews** [spring-projects/spring-security#4077]
`GlobalMethodSecurityConfiguration` autowires `PermissionEvaluator` from the context:
https://github.com/spring-projects/spring-security/blob/4.1.3.RELEASE/config/src/main/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.java#L154

`WebSecurityConfiguration` should do the same thing.

Currently, it's surprising that when a `PermissionEvaluator` is set up, it just works (with no configuration other than declaring the `PermissionEvaluator` bean) when used from Java annotations but the same expression always returns denied (as that's what the default configuration does) when used from in a web context (such as in a JSP sec: expression).

**Comment by rwinch** [comment]
Thanks for creating the issue! Would you be interested in submitting a PR?

**Comment by candrews** [comment]
@rwinch PR submitted. Thanks in advance for working with me on this issue.

**Comment by candrews** [comment]
I've updated the PR to include testing.

Note that I've followed the style/approach of #4020

**Comment by rwinch** [comment]
@candrews Thanks!

**Comment by rwinch** [comment]
Thanks for your work on this! This has been merged via 3bf6bf10de959810c33ecbeaf68ded4f1dde53d0  I put polish on it in 8a66d0c78d9f51e2294229ff3c4038dfe5008c73 so that the actual object is not changed but the configuration is updated. This ensures the logic of looking up beans is kept within Configuration and the Bean is kept just a simple Bean.

**Comment by rwinch** [comment]
@candrews This issue is closed. Can you please create a new ticket with details of the issue you are experiencing?

**Comment by candrews** [comment]
> @candrews This issue is closed. Can you please create a new ticket with details of the issue you are experiencing?

I was thinking this issue should be reopened, as the reported issue was not fixed. :-)

**Comment by rwinch** [comment]
Thanks for creating the new ticket. I can understand why you might have thought that reopening this was what needed to be done. To clarify...Once a ticket is associated with a release and that release is performed we do not reopen the issue because the change log is considered immutable at that point. Instead we create a new ticket. Thanks again!
