### ISSUE TITLE
Make it easier to configure a UserCache for a UserDetailsService

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-security#4139]
When using the XML namespace to configure a `user-service` it was pretty easy to make it a caching one by adding a reference using the `cache-ref` attribute and point it to a `UserCache` implementation. 

With Java based configuration this option is only available for the `jdbcAuthentication` and not for a plain `UserDetailsService` or `LdapUserDetailsService`. 

It would be nice if it was possible to specify a `userCache` for each option available and that that would wrap the `UserDetailsService` in a `CachingUserDetailsService` when needed. 

Related: #2837

Stackoverflow: http://stackoverflow.com/questions/40766098/springcachebasedusercache-is-null/40782952?noredirect=1#comment68816495_40782952

**Comment by gpaul-idexx** [comment]
It looks to me like CachingUserDetailService is not intended for direct usage given the non-public constructor. I think the intent for caching is that we set a cache on a AbstractUserDetailsAuthenticationProvider. I believe the approach for java config would be for there to be a userCache method added to AbstractDaoAuthenticationConfigurer so that we can do:

```java
@Override
protected void configure(AuthenticationManagerBuilder auth) throws Exception {
    auth.userDetailsService(myUserDetailsService).userCache(myUserCache);
}
```

I'd be willing to take a crack at issuing a PR for this trivial change if the spring folks would like.

**Comment by ir73** [comment]
any updates on this? was this merged?

**Comment by ir73** [comment]
Sure, here we go https://github.com/spring-projects/spring-security/pull/6196
