### ISSUE TITLE
 How to enable Spring Security POST redirect after log in with CSRF?

### ISSUE THREAD

**Issue by sowmyadivyanand** [spring-projects/spring-security#4188]
CSRF Enabled 
When the user post data from unprotected to protected resource. The protected resource redirects the user to login page  for authentication. After authentication when it redirects back to protected resource the data that was posted by unprotected resource is lost in the process.  
 Spring Security does not save the request for a POST.  It only saves for a GET.  

Version of Spring Security:4.2.6.RELEASE

**Comment by rwinch** [comment]
You do not want to automatically replay a POST request after a user has authenticated.

The first issue is that the CSRF must change after log in to prevent from a type of session fixation attack. For example, a malicious user could establish a session in a shared computer and write down the CSRF token that was being used. When they see a user authenticate, they can now use the CSRF token to make CSRF attack against the user.

Since the CSRF token must change, this means replaying the original POST will result in a 4xx due to the fact that the original request had a different CSRF token. We cannot ignore the token, because a malicious user could submit a POST to the site and then request the user to log in. At that point the user would be tricked into performing the POST operation.

In general, automatically performing a POST after log in is a bad idea. This is especially true if the user is expecting to provide CSRF protection.

If you really want to do this and open your application up for exploits, you can change the `RequestCache` to be `HttpSessionRequestCache` without a `requestMatcher` set which is what skips caching the POST requests when CSRF is enabled. This is **NOT SECURE** though.
