### ISSUE TITLE
SwitchUserFilter should match on exact URLs

### ISSUE THREAD

**Issue by kicktipp** [spring-projects/spring-security#4249]
### Summary

SwitchUserFilter states in its doc that "This URL will be required to have appropriate security constraints configured so that only users of that role can access it (e.g. ROLE_ADMIN)". 

But SwitchUserFilter is not only triggered on this specific URL given with setSwitchUserUrl. It runs on every URL which "ends" with the string given as an URL. 

### Actual Behavior

Imagine you have /info/** configured without Security in your FilterSecurityInterceptor and you have SwitchUserFilter configured. Of course you deny access to "/login/impersonate" as this URL needs to be secured.

But SwitchUserFilter switches User even on "/info//login/impersonate" and any other URL which endsWith /login/impersonate

### Expected Behavior

SwitchUserFilter should compare the actual URL and the given URL with equals not with "endsWith".

### Configuration

Any Configuration with SwitchUserFilter and an area of URLs which is accessable by Wildcard match

### Version

Version 4.2.2

### Sample

This bug is so obvious. I can provide a sample if you like.
Line 410 must be
   
     return uri.equals(request.getContextPath() + this.switchUserUrl);

instead of

      return uri.endsWith(request.getContextPath() + this.switchUserUrl);

**Comment by martin-g** [comment]
A workaround would be to use antMatchers with wildcards in your configuration, something like `.antMatchers("*/login/impersonate*").hasAuthority("ROLE_ADMIN")`

**Comment by kicktipp** [comment]
A workaround is easy but I think this is a really bad security issue. You do not expect this Filter to listen on every URL just ending with the switchUrl. Many sites can be hijacked with such a simple trick

**Comment by martin-g** [comment]
Fully agree!
I mention the workaround just so that users can protect their apps until the next release.

**Comment by svschouw-bb** [comment]
As far as I can see, this issue is still open.

**Comment by rwinch** [comment]
Thanks for the report! This is now fixed in master and backported to 5.0.x and 4.2.x I've also added a [setExitUserMatcher](https://github.com/spring-projects/spring-security/commit/9c749bf55611d992a5c762deba3e7da61157ffd1#diff-81c688d5f593658da4242cb3d49fd900R456) and [setSwitchUserMatcher](https://github.com/spring-projects/spring-security/commit/9c749bf55611d992a5c762deba3e7da61157ffd1#diff-81c688d5f593658da4242cb3d49fd900R478) which allows a custom `RequestMatcher` to be used in the event users want different behavior.
