### ISSUE TITLE
permitAll requests return 401 status for incorrect token

### ISSUE THREAD

**Issue by kiril-akshonau** [spring-projects/spring-security#4250]
### Summary
Hi guys. We have dedicated authorization server application and and rest application. I've noticed that insecure methods returns 401 in case of invalid credentials. Is this expected behavior? 

### Actual Behavior

1. Add header: `Authorization: Bearer <incorrect_token>`
2. URL http://localhost:8082/insecure/user returns 401

### Expected Behavior

I'm not sure, but is such behavior possible?

_For secure methods_:

- Correct token: returns principal
- Invalid or without token: 401

_For insecure methods_:

- Correct token: returns principal
-  Invalid or without token: anonymous user

### Version

Spring Security - 4.2.2.RELEASE

### Sample

Repository with sample: [link](https://github.com/kiril-akshonau/oauth-security-test)

_Steps to reproduce_:

1. Start authorization server: `gradlew bootRunSecurity`
2. Start application: `gradlew bootRunApp`
3. Generate new token: `POST: http://foo:foosecret@localhost:8081/oauth/token?grant_type=password&username=my_user&password=pass`
4. Make requests with/without/incorrect HTTP header `Authorization: Bearer <access_token>` for ULRs
`http://localhost:8082/secure/user` and `http://localhost:8082/insecure/user`

**Comment by BigTows** [comment]
Answer from [StackOverFlow](https://stackoverflow.com/questions/36296869/spring-security-permitall-still-considering-token-passed-in-authorization-header)

**Comment by jzheaux** [comment]
Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
