### ISSUE TITLE
Should set "javax.servlet.error.exception" request attribute when calling sendError

### ISSUE THREAD

**Issue by imgx64** [spring-projects/spring-security#4336]
### Summary
Whenever `HttpServletResponse.sendError()` is called and an exception is available, I think the `"javax.servlet.error.exception"` (`javax.servlet.RequestDispatcher.ERROR_EXCEPTION`) request attribute should be set alongside it, so that the error page (or in my case, Spring Boot's `DefaultErrorAttributes` class) can show more context on the error.

For example:
- https://github.com/spring-projects/spring-security/blob/22c1685d70e3df61a67113a42b446503427c189a/web/src/main/java/org/springframework/security/web/authentication/Http403ForbiddenEntryPoint.java#L59
- https://github.com/spring-projects/spring-security/blob/22c1685d70e3df61a67113a42b446503427c189a/web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationEntryPoint.java#L60
- https://github.com/spring-projects/spring-security/blob/22c1685d70e3df61a67113a42b446503427c189a/web/src/main/java/org/springframework/security/web/access/AccessDeniedHandlerImpl.java#L75
- https://github.com/spring-projects/spring-security/blob/22c1685d70e3df61a67113a42b446503427c189a/web/src/main/java/org/springframework/security/web/authentication/www/DigestAuthenticationEntryPoint.java#L112
- https://github.com/spring-projects/spring-security/blob/22c1685d70e3df61a67113a42b446503427c189a/web/src/main/java/org/springframework/security/web/authentication/SimpleUrlAuthenticationFailureHandler.java#L77
- https://github.com/spring-projects/spring-security/blob/22c1685d70e3df61a67113a42b446503427c189a/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/authentication/AuthorizationCodeRequestRedirectFilter.java#L145

**Comment by bcalmac** [comment]
@rwinch @jgrandja I think this is important, let me present a real use case for your consideration (I ran into this while upgrading to spring-boot 2):
- `CsrfFilter` generates an error and calls `accessDeniedHandler.handle(request, response,						new MissingCsrfTokenException(actualToken))`
- `AccessDeniedHandlerImpl` stores the exception in the request under `SPRING_SECURITY_403_EXCEPTION` and calls `response.sendError(HttpStatus.FORBIDDEN.value(),					HttpStatus.FORBIDDEN.getReasonPhrase())`
- Jetty `Response` (in my case) looks for the exception under the standard `javax.servlet.error.exception` and finds nothing. Instead of the specific `Could not verify the provided CSRF token because your session was not found.` the error message becomes a generic `forbidden` 

At this point there's absolutely no indication in the log (even on DEBUG level) and on the client I get:

```json
{
  "timestamp" : "2018-09-26T18:01:48.639+0000",
  "status" : 403,
  "error" : "Forbidden",
  "message" : "Forbidden",
  "path" : "/api/v1/products"
}
```

With no indication of the root cause, it took me one day of struggle to pinpoint this error to the CsrfFilter. Do you think it's reasonable to also store the exception under the standard attribute `javax.servlet.error.exception` so that the detail message makes it into the client response? Thanks for looking onto this.

**Comment by rwinch** [comment]
This sounds quite reasonable. Would someone be interested in submitting a PR?

**Comment by bcalmac** [comment]
I'd be happy to.

**Comment by bcalmac** [comment]
Actually, `CsrfFilter` does log on DEBUG:

```java
this.logger.debug("Invalid CSRF token found for "
		+ UrlUtils.buildFullRequestUrl(request));
```
If there's no intention to include the message in the response, my problem could have been solved by paying more attention to the DEBUG logs.

**Comment by rwinch** [comment]
We don't want to include the original exception in the error response as this has caused issues with security scanners because it reflects the HTTP request in the response. The scanner gets upset because it is worried that the HTML response won't be properly encoded.

**Comment by bcalmac** [comment]
Makes sense.

While here, do you still want a PR for exposing the exception under `javax.servlet.error.exception`? In the case of `AccessDeniedHandlerImpl` it makes sense, because the existing code is already exposing it under a non-standard attribute. However, the other 5 occurrences are either in `AuthenticationEntryPoint#commence` or just after the exception is logged, so I don't think it's needed, the exception has already been accounted for.

Let me know how you want to proceed.

**Comment by rwinch** [comment]
If you want we could add a member variable for the attribute name in AccessDeniedHandlerImpl with the default being WebAttributes.ACCESS_DENIED_403. Users could then set it to a different value if they wish.

**Comment by bcalmac** [comment]
Time is a good advisor. I've been away for a while and at this point I wouldn't make any change. The member variable is a good idea, but it seems to me like a one-off piece of functionality and I would wait for a request from someone that actually needs it. 

On the other hand, if you think it's worth implementing it now then I can create a PR.

**Comment by rwinch** [comment]
Given the length of time this has behaved this way, I don't think too many people are desparate for this functionally. I'll close this. If someone feels this is necessary, they can create a new ticket.

Thanks for taking the time to contribute to Spring Security!
