### ISSUE TITLE
How can I use digest authentication and LDAP?   

### ISSUE THREAD

**Issue by momo159** [spring-projects/spring-security#4376]
For digest authentication, if I set PasswordAlreadyEncoded to true, I can store the password -
 MD5(password:realm:password) or verify it with database. But if I want to  verify it with LDAP server, how can I implement it?

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
