### ISSUE TITLE
@EnableGlobalMethodSecurity triggers component scan, breaks testing and convention

### ISSUE THREAD

**Issue by slu-it** [spring-projects/spring-security#4426]
### Summary

The `@EnableGlobalMethodSecurity` annotation is annotated with `@Configuration` which makes every class annotated with `@EnableGlobalMethodSecurity` a configuration class which in turn is picked up by `@ComponentScan`.

_This breaks my integration tests._

Each of my (Spring Boot) integration tests has it's own configuration class within the test class. In order to prevent other test configurations (which might use component scan for certain packages) _none_ of these are annotated with `@Configuration`. For my security integration tests the configuration class is _only_ annotated with `@EnableGlobalMethodSecurity`. The existence of this configuration class however breaks all my other integration tests which rely on component scanning.

_Why is `@EnableGlobalMethodSecurity` an alias for `@Configuration`?_

Other `@Enable${SomeThing}` annotations provided by spring:
- `EnableAsync`
- `EnableCaching`
- `EnableAspectJAutoProxy`
- `EnableWebMvc`
- etc.

None of these are aliases for `@Configuration`! (And the list goes on..)

### Actual Behavior

Classes annotated with `@EnableGlobalMethodSecurity` are found as configurations when scanning for components.

### Expected Behavior

Classes annotated with `@EnableGlobalMethodSecurity` are _not_ found when scanning for component.

### Version

`spring-security-config` version `4.2.2.RELEASE`

### Sample

[Example as GitHub Repository](https://github.com/slu-it/example-spring-security-component-scan-issue)

As you can see here, the `FooServiceIntTest` fails because it's component scan finds the `FooServiceSecurityTest`'s configuration and there are two beans for the same class in the test context.

**Comment by rwinch** [comment]
Thanks for the report. This is expected behavior because Spring Security wants the `@Enable*` annotations to be picked up automatically to minimize configuration. Practically speaking, classes with `@Enable*` annotations are all configuration classes anyways.

For your testing scenarios, there are plenty of ways to limit your component scan to avoid the error.

- Move the Security Configuration to a package that won't be picked up by the `@ComponentScan`
- Use [excludeFilters](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/ComponentScan.html#excludeFilters--). For example `excludeFilters = @ComponentScan.Filter(classes = EnableGlobalMethodSecurity.class))`
- If you find that verbose, you can create a [Composed Annotation](https://github.com/spring-projects/spring-framework/wiki/Spring-Annotation-Programming-Model#composed-annotations)

**Comment by slu-it** [comment]
While it is true that `@Enable*` annotations are usually present on `@Configuration` classes, it is also true that there is usually just 1 security related `@Configuration` class, while there are a lot more test `@Configuration` classes. These you generally don't want to have picked up by mechanics like component scan.
I can understand why someone wanted this feature in the first place. But I don't quite understand why it was implemented. The usefulness (-1 line of code) - in my mind - is minimal and the consequences can be seen here. But yeah, it is too late to change it now...
