### ISSUE TITLE
Revisit handling of `iss` claim in `IdToken`

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-security#4538]
See #4511.

**Comment by jgrandja** [comment]
As per spec,

> iss
> REQUIRED. Issuer Identifier for the Issuer of the response. The iss value is a case sensitive URL using the https scheme that contains scheme, host, and optionally, port number and path components and no query or fragment components.

The expectation is that the `iss` claim is a valid `URL` so we should not provide any special handling for cases where a provider returns the `iss` claim that is not a valid `URL`, e.g. missing scheme. It must be a valid `URL` or should fail otherwise.

Given this, the current behaviour works as expected so will leave things as is.

**Comment by vpavic** [comment]
Agreed - with Google now having a valid value in their `issuer` I don't think there's any other action needed on this.
