### ISSUE TITLE
ClientRegistration.Builder constructor should be private

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4656]
### Summary

We should have static factory methods on ClientRegistration as apposed to exposing the Builder constructor. The constructor `Bulder(String)` can be confusing with so many different string properties. Something like `ClientRegistration.withRegistrationId` and `ClientRegistration.from(ClientRegistration)`

**Comment by jgrandja** [comment]
`Builder` was intentionally exposed as public to allow for extension - as well a couple of `protected` methods within. A user may want to extend a `ClientRegistration` with additional custom attributes that may be used at the various plug-in points.

However, it would be easier to expose this later if need be instead of right out of the gate. What do you think @rwinch ?

**Comment by rwinch** [comment]
I would keep it private for now. We could open it up to being protected later if necessary.
