### ISSUE TITLE
DelegatingServerLogoutHandler

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4839]
### Summary

Create a `ServerLogoutHandler` which delegates to a group of `ServerLogoutHandler` implementations. We should also update the configuration to leverage `DelegatingServerLogoutHandler`

**Comment by edeandrea** [comment]
@rwinch - the 2nd part of the summary in this ticket reads

   > We should also update the configuration to leverage `DelegatingServerLogoutHandler`

Does that mean within `LogoutWebFilter` we should change

```java
public void setLogoutHandler(ServerLogoutHandler logoutHandler) {
  Assert.notNull(logoutHandler, "logoutHandler must not be null");
  this.logoutHandler = logoutHandler;
}
```

to be something more like 

```java
public void setLogoutHandler(ServerLogoutHandler logoutHandler) {
  Assert.notNull(logoutHandler, "logoutHandler must not be null");
  this.logoutHandler = new DelegatingServerLogoutHandler(this.logoutHandler, logoutHandler);
}
```

IMO I'm not a big fan of creating new instances of things on the fly - the main reason is it isn't thread safe, since the `filter` method uses the `logoutHandler`.

Would it be better to do something like this?

```java
private final ServerLogoutHandler logoutHandler = new DelegatingServerLogoutHandler(new SecurityContextServerLogoutHandler());

public void setLogoutHandler(ServerLogoutHandler logoutHandler) {
  Assert.notNull(logoutHandler, "logoutHandler must not be null");
  this.logoutHandler.addLogoutHandler(logoutHandler));
}
```

We'd have to add an `addLogoutHandler` method to the new `DelegatingServerLogoutHandler` class. This seems to go against the structure of some of the other `Delegating...` classes though where new instances are created on the fly.
