### ISSUE TITLE
Set default value on ClientRegistration#redirectUriTemplate

### ISSUE THREAD

**Issue by kazuki43zoo** [spring-projects/spring-security#4862]
### Summary

I hope to define the same value with `CommonOAuth2Provider#DEFAULT_LOGIN_REDIRECT_URL` as public constants because I want to refer from new provider(e.g. Yahoo Japan) definition.

https://github.com/spring-projects/spring-security/blob/86824030f293838acbfe05bbf3072101d914d89c/config/src/main/java/org/springframework/security/config/oauth2/client/CommonOAuth2Provider.java#L96

WDYT?

### Version

* 5.0.0.RC1

**Comment by kazuki43zoo** [comment]
or Set to it as default value on `CleintRegistration$Builder#redirectUriTemplate`.

**Comment by jgrandja** [comment]
Thanks for your feedback @kazuki43zoo.

`CommonOAuth2Provider` sole purpose is to set default values for a `ClientRegistration` via the `ClientRegistration.Builder` for a well-known provider. So the preference is to keep `DEFAULT_LOGIN_REDIRECT_URL` in `CommonOAuth2Provider` and as `private`.

As an FYI, you can override the default redirect URL using the [`redirect-uri-template`](https://docs.spring.io/spring-security/site/docs/5.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#jc-oauth2login-boot-property-mappings) property and define new provider properties using the [`provider`](https://docs.spring.io/spring-security/site/docs/5.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#jc-oauth2login-custom-provider-properties) base property.

I'm going to close this but if have any questions around this than we can look at it further.

**Comment by kazuki43zoo** [comment]
Thanks for your reply!!
I think reasonable that sets the default value for the `redirectUriTemplate` because I think we will set the same value with the default value in most cases.

**Comment by jgrandja** [comment]
@kazuki43zoo The default redirect url for **OAuth 2.0 Login** feature is `{baseUrl}/login/oauth2/code/{registrationId}`.

However, when we provide the ability/feature to obtain an `OAuth2AccessToken` using the standard _Authorization Code Grant_ flow (after login) than the default redirect url for the `ClientRegistration` **will not** be `{baseUrl}/login/oauth2/code/{registrationId}`. This is only the default for **OAuth 2.0 Login**. So we do not want to tie this default to `ClientRegistration`. That's why it's in `CommonOAuth2Provider ` as `private`.

**Comment by kazuki43zoo** [comment]
Thank you for your detail explanation. I understood it!!
