### ISSUE TITLE
High traffic leads to very high CPU usage with spring security 5.0.0.RELEASE

### ISSUE THREAD

**Issue by jan-schumacher** [spring-projects/spring-security#4959]
### Summary

Moderate to high traffic leads to very high CPU usage with Spring Security version 5.0.0.RELEASE.

After trying things out and looking into the changelist of 5.0.0.RELEASE I found out that the new default password encryption logic is the reason for the high CPU usage.
When I use NoOpPasswordEncryption (old default) the CPU usage is normal, while using PasswordEncoderFactories.createDelegatingPasswordEncoder() produces very high CPU usage again.
Which is obvious though but should somehow be fixed.

[highcpuusagesetup.zip](https://github.com/spring-projects/spring-security/files/1622751/highcpuusagesetup.zip)

This is basically just a default spring boot 2.0.0.M7 application with basic authentication (user:test) and 1 request mapping.

When I send ~7000 requests per 30 sek. I observed very high cpu usage of around 140% of the machines it is running on. (10 instances parralel)

<img width="955" alt="highcpuusagetest" src="https://user-images.githubusercontent.com/9511748/34828198-128146ae-f6dd-11e7-9903-e61182425c80.png">

After downgrading to the last spring security release 4.2.3.RELEASE the cpu usage drops drastically by ~120%

<img width="955" alt="lowcpuusagetest" src="https://user-images.githubusercontent.com/9511748/34828278-543926fc-f6dd-11e7-91dc-c81ddef1ca56.png">

I have tested this with tomcat 8 and tomcat 8.5 as packaged war deployments.

The requests are all authorized with basic auth

### Actual Behavior

High CPU usage due to high traffic

### Expected Behavior

Normal CPU usage allthough high traffic

### Configuration

[highcpuusagesetup.zip](https://github.com/spring-projects/spring-security/files/1622751/highcpuusagesetup.zip)

### Version

5.0.0.RELEASE

### Sample

[highcpuusagesetup.zip](https://github.com/spring-projects/spring-security/files/1622751/highcpuusagesetup.zip)

**Comment by jan-schumacher** [comment]
After trying things out and looking into the changelist of 5.0.0.RELEASE I found out that the new default password encryption logic is the reason for the high CPU usage. 
When I use NoOpPasswordEncryption (old default) the CPU usage is normal, while using PasswordEncoderFactories.createDelegatingPasswordEncoder() produces very high CPU usage again.
Which is obvious though but should somehow be fixed, because with this high load the current state is unusable for high traffic applications.

**Comment by rwinch** [comment]
Thank you for the report.

Because adaptive one-way functions are intentionally resource intensive, validating a username and password for every request will degrade performance of an application significantly. There is nothing Spring Security (or any other library) can do to speed up the validation of the password since security is gained by making the validation resource intensive. Users are encouraged to exchange the long term credentials (i.e. username and password) for a short term credential (i.e. session, OAuth Token, etc). The short term credential can be validated quickly without any loss in security.

I have updated the documentation to include the information above. Thanks again for the report!
