### ISSUE TITLE
Reactive method security return types support

### ISSUE THREAD

**Issue by Nialit** [spring-projects/spring-security#4988]
Currently `PrePostAdviceReactiveMethodInterceptor` class wrappes annotated method with checking for `Mono` and `Flux` return types. If none of them matches, it attempts to invoke returning `MonoFlatMapMany` type, which is supposed to be assignable from actual return type.
https://github.com/spring-projects/spring-security/blob/747473257f813eb23161db4138e36f561e154a87/core/src/main/java/org/springframework/security/access/prepost/PrePostAdviceReactiveMethodInterceptor.java#L95-L98

Hence WebFlux with method security fails to support any return types but Flux and Mono, `ClassCastException` arises.

**Comment by rwinch** [comment]
@Nialit Thanks for the report. What return type are you trying to leverage? The return type must be something that Spring Security can extract Reactor's `Context` from otherwise we will not be able to obtain the currently logged in user to make an authorization decision.

**Comment by Nialit** [comment]
@rwinch I see, so obviously there is no option to maintain method security with non-reactive return type. WebFlux by itself support besides Reactor, RxJava2 and any other Object return types. It seems that it's incompatible by design with Reactor on contexts security checks approach. Not sure, but probably reactive security could go with some kind of AOP wrapping and unwrapping having target method  around pointcut?
At least it seems worth to mention somewhere in docs about return types restriction when using webflux security.

**Comment by rwinch** [comment]
@Nialit Thanks for the feedback. The reason that Spring MVC can support the other types is because it is not necessarily assuming you will be using the Reactor `Context`. Spring Security method security requires this in order to populate the current `Authentication` to make the authorization decision.

I updated the docs and ensured that a better error message would be provided when the return type was not a `Publisher`. See 964a14b  for the changes

Thanks again for the report!

**Comment by Nialit** [comment]
@rwinch Yep, I see now. Thanks you much, Rob. You're doing great work!
