### ISSUE TITLE
UserInfo request performed with no URI set

### ISSUE THREAD

**Issue by bberto** [spring-projects/spring-security#4992]
### Summary

In a simple app with OAuth2 login (not OIDC) I get this exception:

```
java.lang.NullPointerException: null
	at java.net.URI$Parser.parse(URI.java:3042) ~[na:1.8.0_131]
	at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_131]
	at java.net.URI.create(URI.java:850) ~[na:1.8.0_131]
	at org.springframework.security.oauth2.client.userinfo.NimbusUserInfoResponseClient.getUserInfoResponse(NimbusUserInfoResponseClient.java:79) ~[spring-security-oauth2-client-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.security.oauth2.client.userinfo.NimbusUserInfoResponseClient.getUserInfoResponse(NimbusUserInfoResponseClient.java:66) ~[spring-security-oauth2-client-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.security.oauth2.client.userinfo.DefaultOAuth2UserService.loadUser(DefaultOAuth2UserService.java:69) ~[spring-security-oauth2-client-5.0.1.RELEASE.jar:5.0.1.RELEASE]
```
### Actual Behavior

DefaultOAuth2UserService.loadUser tries to perform a UserInfo Request, but no URI is set and it fails.

### Expected Behavior

UserInfo should not be requested for OAuth2 login, when user-info-uri is not set / is null

### Configuration

```
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id:  <hidden>
            client-secret: <hidden>
            scope: custom
        provider:
          okta:
            authorization-uri: https://<hidden>.oktapreview.com/oauth2/default/v1/authorize
            token-uri: https://<hidden>.oktapreview.com/oauth2/default/v1/token
            jwk-set-uri: https://<hidden>.oktapreview.com/oauth2/default/v1/keys
```

### Version
Spring Boot 2.0.0.RC1
Spring Security 5.0.1.RELEASE

**Comment by jgrandja** [comment]
Thanks for the report @bberto. As an FYI, the UserInfo resource call is required for OAuth 2.0 clients, however, it's not required for OIDC clients since the ID Token can be leveraged for authentication.
I've added an assertion for the UserInfo Uri in `DefaultOAuth2UserService` for this update.
This is now merged in master and is scheduled for the upcoming 5.0.2 release.
Thanks!

**Comment by bberto** [comment]
You're welcome @jgrandja. Could you provide further details about why UserInfo call is required? References to RFC would be appreciated. Does it relates with RFC 7662 - Token Introspection?

**Comment by jgrandja** [comment]
In order to log in the user, we need to obtain user attributes of the user so we can create a `Principal` in the form of an `OAuth2User` and associate it with the `Authentication`. At minimum we need the user's name. Without any user info (attributes) we cannot create a `Principal` or complete the OAuth 2.0 Login.

**Comment by ogeisser** [comment]
The deeper issue here is that there is no such thing as "OAuth2 login without OIDC".

At least not when you rephrase "login" as "authentication".

OAuth2 alone gives you only "authorization", e.g. an access token to access a service.

But this does NOT prove the identity of the user.

The reason for this is that a malicious service could "fake" (impersonate) a user by providing it's access token to another service.

This is the reason why Open ID Connect exists.

OIDC sits on top of OAuth2 and adds the "id token" to the game.

Only by verifying this "id token" a service can assure the identity of the user, e.g. authenticate (="login") the user.

A more detailed explanation can be found here: [The deeper issue here is that there is no such thing as "OAuth2 login without OIDC".

At least not when you rephrase "login" as "authentication".

OAuth2 alone gives you only "authorization", e.g. an access token to access a service.

But this does NOT prove the identity of the user.

The reason for this is that a malicious service could "fake" (impersonate) a user by providing it's access token to another service.

This is the reason why Open ID Connect exists.

OIDC sits on top of OAuth2 and adds the "id token" to the game.

Only by verifying this "id token" a service can assure the identity of the user, e.g. authenticate (="login") the user.

A more detailed explanation can be found here: https://oauth.net/articles/authentication/](https://oauth.net/articles/authentication/)

**Comment by jgrandja** [comment]
@ogeisser Thanks for sharing the resource [User Authentication with OAuth 2.0](https://oauth.net/articles/authentication/). 

However, can you please be more specific as to what you are suggesting? Are you suggesting that the current implementation of the OAuth 2.0 Login feature is potentially exposed to a vulnerability? If so, can you please be more specific and provide a detailed scenario?

Based on my analysis, reading the article, the only topic that may be relevant is the section _"Access of a protected API as proof of authentication"_.

It states the following:

> Since the access token can be traded for a set of user attributes, it is tempting to think that possession of a valid access token is enough to prove that a user is authenticated. This assumption turns out to be true in some cases, where the token was freshly minted in the context of a user being authenticated at the authorization server. However, that's not the only way to get an access token in OAuth. Refresh tokens and assertions can be used to get access tokens without the user being present, and in some cases access grants can occur without the user having to authenticate at all.

For OAuth Providers that DO NOT support OpenID Connect 1.0, for example, GitHub and Facebook, we achieve login by requesting information from the configured "UserInfo" endpoint. Let me explain via a sample flow:

1) User clicks on "Login with GitHub" in the application that has OAuth 2.0 Login enabled.
2) User is redirected to GitHub for authentication via the Authorization Code flow
3) User authenticates with GitHub and is then presented with the Consent screen, saying something like, "Do you authorize OAuth 2.0 Login Sample App to access your User information?"
4) User approves the authorization request and than GitHub sends an Authorization Code back to the application (the OAuth client)
5) The OAuth client obtains the authorization code and sends this along to the Token Endpoint to obtain an access token.
6) GitHub issues an access token after it validates the authorization code.
7) At this point the OAuth client has an access token that is capable of accessing the user's information at the protected resource at GitHub. In OpenID Connect world, this is called the UserInfo endpoint and is standardized. However, since GitHub is not OpenID Connect compliant, it's UserInfo endpoint is non-standard and therefore the application MUST BE explicitly configured by the engineer to allow this to work.
8) Next the OAuth client calls the GitHub "UserInfo" endpoint to obtain attributes of the user. One of  those attributes represents the name or some unique identifier of the user registered at GitHub. This is ultimately what is used to represent the `Authentication.getPrincipal().getName()` to finally achieve OAuth 2.0 login.

So based on the previous statement in the reference:

> Since the access token can be traded for a set of user attributes, it is tempting to think that possession of a valid access token is enough to prove that a user is authenticated. This assumption turns out to be true in some cases, where the token was freshly minted in the context of a user being authenticated at the authorization server.

The flow above is exactly what is stated here and is valid.

However, the statement that follows:

> However, that's not the only way to get an access token in OAuth. Refresh tokens and assertions can be used to get access tokens without the user being present, and in some cases access grants can occur without the user having to authenticate at all.

...is where the issue can occur. At this point, we do not provide support for the `refresh_token` grant so this is not applicable to the OAuth 2.0 Login feature. However, our plan is to provide support for the `refresh_token` grant in an upcoming release but this will NOT be supported for OAuth 2.0 Login. To be clear, the access token that is used to fetch user information will only be used the one-time during login/authentication to the application and at that point it's done.

A key point I want to stress here is that it's up to the application developer to configure the UserInfo Endpoint URL and the attribute name returned in the UserInfo response that represents the `Principal.name`. So it's ultimately in the control of the application engineer to correctly configure the GitHub UserInfo endpoint URL and the attribute name of the User Name. We do not and cannot guess this given that the UserInfo response is not standardized for OAuth Providers. For OpenID Connect Providers, we know it's the combination of `iss` and `sub`. Please take a look at the GitHub sample if you would like more details [sample](https://github.com/spring-projects/spring-security/tree/master/samples/boot/oauth2login#github-login)

The other key point I want to stress here is the User Information is not passed along to external resources. The application that is configured with OAuth 2.0 Login is the only resource that is aware of the Principal name. This information is never passed to external resources (Resource Servers) in order to provide User Information.

I hope I have explained things here in detail and have clarified things. If there is something I have missed and you still foresee a potential issue than please let me know and provide details so I can further analyze. Thanks.

**Comment by ogeisser** [comment]
Thank you @jgrandja for taking the time to consider my feedback.

### RFC 6819 - Why it is a bad idea to use plain oauth2 for authentication

To answer your question what I suggest: Yes, I'm suggesting that the current implementation of the OAuth 2.0 Login feature is potentially exposed to a vulnerability. And more than that. I'm suggesting that OAuth 2.0 in general is not sufficient as an authentication (e.g. login) mechanism.

And this is not my personal opinion but the official statement of the OAuth 2 working group documented in an RFC: "OAuth 2.0 Threat Model and Security Considerations" (RFC 6819)

See chapter 4.4.1.13 <https://tools.ietf.org/html/rfc6819#section-4.4.1.13>

### Stack Exchange Security explanation
The RFC is a little bit hard to grasp. So in addition I've found the following article on Stack Exchange Security helpful: <https://security.stackexchange.com/questions/133065/why-is-it-a-bad-idea-to-use-plain-oauth2-for-authentication>

### Flawed GitHub Sample

In your GitHub sample the step 8 is flawed. You state that the client calls GitHub "*to obtain attributes of the user [...] to finally achieve OAuth 2.0 login*". And this assumption is the flaw.
You assume that you get attributes of the user when you really get attributes related to the authorization code from step 2. And this can be abused by a malicious service to "fake" (impersonate) a user.

### Summary
- OAuth 2.0 alone is not an authentication (e.g.) login mechanism.
- Also the fact that you have an access token to read some user information from a service (e.g. a kind of UserInfo endpoint) is not a valid authentication mechanism.
- Can you implement an authentication mechanism on top of OAuth 2.0?
Yes, of couse. This is what Open ID Connect has done. But this is not an easy task and in 99% of all cases you should not do this.

**Comment by jgrandja** [comment]
@ogeisser Thank you for providing more details around the potential exposure you see as this helps me to understand your concerns.

First off, I want to be clear that we are not recommended OAuth 2.0 authentication over OpenID Connect 1.0. It's an obvious choice to use OpenID Connect 1.0 for authentication as this is the primary goal it was designed for - authentication built on top of OAuth 2.0.

However, not all Providers implement/support OIDC (e.g. GitHub, Facebook) but we still want to be able provide support for OAuth 2.0 based login for applications that do not provide a login option for an OpenID Connect 1.0 provider. As I'm sure you are aware, we strive to be flexible and provide as much support as possible to our user's so they have options to choose from. It's up to the user of the application which provider's they will offer for login in their application. If we only provide support for OpenID Connect 1.0 Provider's than we are limiting the options to our user's and that's not going to motivate user's to use this feature.

Ok, now let's go over your main concern, which is the **Authorization Code Substitution** attack as defined in [Section 4.4.1.13.  Threat: Code Substitution (OAuth Login)](https://tools.ietf.org/html/rfc6819#section-4.4.1.13).

Per your statement:

> Yes, I'm suggesting that the current implementation of the OAuth 2.0 Login feature is potentially exposed to a vulnerability. 

This in fact is not the case, as the current implementation is not exposed to an **Authorization Code Substitution** attack. Details to follow below.

> And more than that. I'm suggesting that OAuth 2.0 in general is not sufficient as an authentication (e.g. login) mechanism.

RFC6819 does not explicitly state NOT to use OAuth 2.0 as an authentication mechanism. If it explicitly states this somewhere that I'm missing than please point me to the exact statement.
However, it does specifically recommend to use OpenID or SAML based on Bullet 2 in the _Countermeasures_ of Section 4.4.1.13. But if OpenID or SAML is not an option based on the fact that the Provider does not support those authentication protocols than it provides the Countermeasure to be implemented as stated in Bullet 1 in Section 4.4.1.13.

Let's go into the implementation details of OAuth 2.0 Login so I can explain it is not exposed to the **Authorization Code Substitution** attack. You specifically pointed out that there is a Security Hole in the GitHub Sample

Here is the scenario you have drawn out:

> If all goes as planned, the authorization_code is, indeed, from the user you redirected to GitHub for authentication. But: there is no guarantee that is the case. In fact, any malicious website that the user has previously granted the right to access the user's data (using OAuth2 with GitHub), can get a valid authorization_code from GitHub and send it to you, in step 4.

Based on this scenario, we have the following actors:

* Malicious App (`client-id` -> _evil-client-1234_)
* OAuth 2.0 Login App (`client-id` -> _github-login-5678_)
* GitHub as the OAuth 2.0 Authorization Server
* GitHub as the OAuth 2.0 Resource Server which provides the "Identity API" via the [Get the authenticated user](https://developer.github.com/v3/users/#get-the-authenticated-user) endpoint
* John Smith (the victim) being the User registered at GitHub

The pre-requisite to your scenario is that John Smith has previously authorized Malicious App and  OAuth 2.0 Login App to access it's protected user info resource. It doesn't matter how John Smith was tricked into authorizing Malicious App to access it's protected user info resource but it is an assumption to this scenario and is a valid situation that can happen.

Given the pre-requisite as per above, and as per your statement: 

> In fact, any malicious website that the user has previously granted the right to access the user's data (using OAuth2 with GitHub), can get a valid authorization_code from GitHub and send it to you, in step 4.

The following steps would need to be executed:

1. Malicious App requests an `authorization_code` from GitHub by initiating an Authorization Request. Given that John Smith has already authorized Malicious App based on our pre-requisite, the `authorization_code` will be returned in the Authorization Response from GitHub. The one important thing to note is that `client_id` is REQUIRED  for the [Authorization Request](https://tools.ietf.org/html/rfc6749#section-4.1.1) so this would be _"evil-client-1234"_. The other point to note is the `state` parameter being RECOMMENDED.

2. Malicious App receives the `authorization_code` from GitHub in the Authorization Response and now sends it to OAuth 2.0 Login App to trigger the login process. For this to work, the client _"evil-client-1234"_ will need to exchange the `authorization_code` for an access token at the token endpoint, which would ultimately result in John Smith being logged into OAuth 2.0 Login App but under the identity of the client _"evil-client-1234"_.

Step 2 would never succeed based on the current implementation of OAuth 2.0 Login, based on these reasons:
1. `OAuth2LoginAuthenticationFilter` uses the `AuthorizationRequestRepository` to find the Authorization Request that was previously initiated to GitHub, by checking in the `HttpSession` (by default). Given that the Authorization Request was initially triggered by Malicious App, there is no Authorization Request stored in HttpSession of OAuth 2.0 Login App so it will fail.
2. The `state` parameter is used by the OAuth 2.0 Login feature so this would need to be provided in the Authorization Response. The `code` is not sufficient enough for the attacker to trigger this attack. The `state` is initially created by the client in the Authorization Request and sent back in the Authorization Response so it can correlate and protected itself against attacks like [10.12.  Cross-Site Request Forgery](https://tools.ietf.org/html/rfc6749#section-10.12). Given the fact that the Authorization Request and associated `state` parameter is never created by client _"github-login-5678"_, this check will fail.
3. The malicious app will need to know what the registered `redirect_uri` is for OAuth 2.0 Login App (client _"github-login-5678"_) as this is where the Authorization Response needs to be redirected to. If invalid, it will fail.
4. Now assuming all previous steps pass, now is the point where the Token Request is initiated. Given that client _"github-login-5678"_ is a confidential client and therefore must authenticate itself at the Token Endpoint using it's credentials. After the client authenticates, the Authorization Server validates the `authorization_code` as per [Section 4.1.3.  Access Token Request](https://tools.ietf.org/html/rfc6749#section-4.1.3):

> ensure that the authorization code was issued to the authenticated  confidential client, or if the client is public, ensure that the code was issued to "client_id" in the request,

This check would fail as well given that the authenticated  confidential client is _"github-login-5678"_, however, the `authorization_code` was granted to client _"evil-client-1234"_.

Based on all the details I have provided here, there is no exposure. If you still disagree with my explanation here than the next step would be for you to provide a working sample that proves this exposure. You can use the GitHub sample as a starting point and produce a test or scenario that re-produces the **Authorization Code Substitution** attack. Please note, this next step is required in order to continue with further analysis.

**Comment by ogeisser** [comment]
Thank you @jgrandja for the detailed response.

I've read it and I've also re-read the Threat Model RFC.

After that I've come to the conclusion that there is indeed no exposure.

But during this thought process I've reflected about the root cause of my reaction/confusion about this whole topic.

And I think a big part of it is the current documentation structure.

Currently the documentation emphasizes the term "OAuth 2.0 Login"

For example the whole chapter 5.7. is named "OAuth 2.0 Login" and only in the introduction paragraph OpenID Connect gets mentioned.

But as you have explained above "It's an obvious choice to use OpenID Connect 1.0" and "we [do] not recommended OAuth 2.0 authentication over OpenID Connect".

Therefor I propose to emphasize more that Open ID Connect is the recommended approach.

And then go on to explain, that there are some providers like GitHub and Facebook wihtout proper OIDC support and for these cases there is also the option of an "OAuth 2.0 login". But that in this case one needs to implement the part corresponding to the OIDC UserinfoEndpoint in a provider specific way.

**Comment by jgrandja** [comment]
@ogeisser Section 5.7 OAuth 2.0 Login starts off with:

> The OAuth 2.0 Login feature provides an application with the capability to have users log in to the application by using their existing account at an OAuth 2.0 Provider (e.g. GitHub) or OpenID Connect 1.0 Provider (such as Google)

It follows with instructions on setting up the Google sample, which is an OpenID Connect provider and states:

> Google’s OAuth 2.0 implementation for authentication conforms to the OpenID Connect 1.0 specification and is OpenID Certified.

There are other mentions throughout the doc of OpenID Connect 1.0. Granted there is no mention that we recommend the use of OpenID Connect provider over a standard OAuth 2.0 provider.

At this point I feel the documentation states all the relevant information. However, we are always open to improvement. If you would be interested in submitting a PR than I will definitely take a look at it. You can also log a new issue as this issue is un-related to this discussion.
Thanks for your feedback.
