### ISSUE TITLE
Missing org.springframework.security.authentication.encoding.PasswordEncoder

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-security#5018]
### Summary

Migration from 4.x to 5.0.x

### Actual Behavior

Missing class `org.springframework.security.authentication.encoding.PasswordEncoder` in Spring Security. 

### Expected Behavior

Workaround for old users. 

### Version

5.0.1

### Sample
see

https://github.com/spring-projects/spring-security/blob/1517e9b2221d8b3f4a86bd71db77cb10fadfaaf0/core/src/main/java/org/springframework/security/authentication/dao/DaoAuthenticationProvider.java#L136-L148

I am expecting an easy way to migrate our applications to new PasswordEncoders but could not find yet.

**Comment by cemo** [comment]
I can see that this comment has forgotten to be deleted. However I can seriously see missing sections in the documentation about migrating from 4.x to 5.x. It would be awesome to address common issues.

**Comment by rwinch** [comment]
@cemo Thanks for the report

> However I can seriously see missing sections in the documentation about migrating from 4.x to 5.x. It would be awesome to address common issues.

I very much agree. There is an issue for migration already. See #4874 

In the meantime, please refer to [PasswordEncoder javadoc](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/crypto/password/PasswordEncoder.html]. It refers to other implementations that will discuss migration strategies. For example, you can refer to [MessageDigestPasswordEncoder javadoc](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/crypto/password/MessageDigestPasswordEncoder.html) if you used `DigestPasswordEncoder`.

Let me know if you are having any specific problems with any of the previous password encoders

> I can see that this comment has forgotten to be deleted.

Thanks that is now fixed in master See 7063a9e

**Comment by cemo** [comment]
Hi @rwinch, you are helpful as always. :) 

The problem is that we are storing salt on user on database. I had difficulties to grab necessary implementation at first glance actually. For those who wants additional details and using Spring Boot, there is also a [post] about that.

I will dive into details soon and I will let you know. 

[post]: https://spring.io/blog/2017/09/15/security-changes-in-spring-boot-2-0-m4
