### ISSUE TITLE
Multiple HTTP security for multiple form login

### ISSUE THREAD

**Issue by GiritharanR** [spring-projects/spring-security#5059]
Based on `Multiple HTTP security` (https://docs.spring.io/spring-security/site/docs/5.0.0.RELEASE/reference/htmlsingle/#multiple-httpsecurity), I am trying to implement multiple form login.

Following are the expectations by handling multiple form login,

 1. Should redirect to the form login page based on the pattern match. **It is working as expected**.
 2. I want the second form login to be redirected for any request other than the pattern used in the first form login. I have tried below configurations.
 ```
@EnableWebSecurity
public class MultiHttpSecurityConfig {
	@Bean                                                             
	public UserDetailsService userDetailsService() throws Exception {
		// ensure the passwords are encoded properly
		UserBuilder users = User.withDefaultPasswordEncoder();
		InMemoryUserDetailsManager manager = new InMemoryUserDetailsManager();
		manager.createUser(users.username("user").password("password").roles("USER").build());
		manager.createUser(users.username("admin").password("password").roles("USER","ADMIN").build());
		return manager;
	}

	@Configuration
	@Order(1)                                                        
	public static class ApiWebSecurityConfigurationAdapter extends WebSecurityConfigurerAdapter {
		protected void configure(HttpSecurity http) throws Exception {
			http
				.antMatcher("/api/**")                               
				.authorizeRequests()
					.anyRequest().hasRole("ADMIN")
					.and()
				.formLogin().loginPage("/apiLoginForm");
		}
	}

	@Configuration                                                   
	public static class FormLoginWebSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {

		@Override
		protected void configure(HttpSecurity http) throws Exception {
			http
				.authorizeRequests()
					.anyRequest().authenticated()
					.and()
				.formLogin();
		}
	}
}
```

Instead of redirecting to the first form login page, it is always taking to the second login page.

Any suggestions to achieve this?

**Comment by xingfudeshi** [comment]
any updates?

**Comment by eleftherias** [comment]
Your first login page `/apiLoginForm` is protected by your second security configuration. If you navigate to `/api/home` for example, the first configuration will redirect you to `/apiLoginForm` because your request matches `/api/**` and then the second configuration will redirect you to `/login` because `/apiLoginForm` does not match `/api/**`.    

One option is to change your first login URL to match the pattern, e.g `.loginPage("/api/loginForm")` and then you will not be redirected to `/login`.  

Alternatively, you can specify in your second configuration that `/apiLoginForm` is not secured.
```
http
   .authorizeRequests()
       	.antMatchers("/apiLoginForm").permitAll()
   	.anyRequest().authenticated()
  	.and()
   .formLogin();
```
