### ISSUE TITLE
ant matcher is not allowing all HTTP methods

### ISSUE THREAD

**Issue by odin-delrio** [spring-projects/spring-security#5070]
### Summary
Configuring an antMatcher to allow all requests for a certain path is not allowing me to do PUT requests while GET requests are reaching my controller as expected.

### Actual Behavior
My GET request is allowed as expected but the PUT one is returning a 401.

### Expected Behavior
Both request should be allowed.

### Configuration
```kotlin
@Configuration
class SecurityConfig : WebSecurityConfigurerAdapter() {
    override fun configure(http: HttpSecurity) {
        http
            .authorizeRequests()
                .antMatchers("/v1/**").permitAll()
                .anyRequest().authenticated()
            .and()
                .httpBasic()
    }
}
```
https://github.com/odin-delrio/spring-security-put-401-issue/blob/master/src/main/kotlin/org/odin/springsecurity/Application.kt

My application setup is there.

### Version
The version that is coming with the Spring Boot 2.0.0.RELEASE, which is the 5.0.3.RELEASE.

### Sample
A full example here: https://github.com/odin-delrio/spring-security-put-401-issue/
Travis is enabled on my repository and tests were executed.
You can see writen [tests here](https://github.com/odin-delrio/spring-security-put-401-issue/blob/master/src/test/kotlin/org/odin/springsecurity/ApplicationTests.kt)

And the failing test log [is here](https://travis-ci.org/odin-delrio/spring-security-put-401-issue/builds/349032133#L8252)

![image](https://user-images.githubusercontent.com/9112748/36950483-c3b431f6-1ff6-11e8-8410-df887c53db9a.png)

thanks in advance!

**Comment by rwinch** [comment]
The 401 response is due to [CSRF Protection](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#csrf) properly rejecting the `PUT` request because there is no CSRF token in the request. You need to https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#when-to-use-csrf-protection[evaluate if you need CSRF Protection]. If you don't, you can disable [CSRF protection](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#csrf-configure). If you need CSRF protection, then you need to [include the CSRF Token in the request](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#csrf-include-csrf-token).

**Comment by odin-delrio** [comment]
I supposed that I missed something ;)
Thanks for answering!
