### ISSUE TITLE
Multiple Http Configurations with Multiple Basic Auth

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-security#5104]
### Summary

BasicAuthenticationFilter is not checking basic auths configurations per http. A user can easily bypass second url's basic auth after being logged to first one. 

### Actual Behavior

1. Two different http configuration with different basic auth. 
2. User is logged in to basic auth first one.
3. When user try to logged in second one, BasicAuthenticationFilter does not require authentication. Since it is using a valid authentication from first one, it skips it.  

### Expected Behavior

For each configuration, an authentication must be required.

### Version

5.0.3

**Comment by cemo** [comment]
I have noticed that I did not cancelled session creation by:
```
   sessionManagement()
         .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
```

This is causing a session creation and subsequent requests using this information from session. 

I think that an info log might be related to basic auth with session creation policy might be helpful. Since whole point of basic auth is letting browser to save credentials and storing in the session may be forbidden?

**Comment by rwinch** [comment]
HTTP Basic is often used with a session because if you are storing your credentials correctly (i.e. using [BCrypt tuned for a workfactor of 1/2-1 second](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#pe-bcpe)) the application will not perform unless you exchange the password for a short term credential (i.e. session).
