### ISSUE TITLE
Client id in tokenrequest object is null when tokenrequest is constructed with clientid passed in

### ISSUE THREAD

**Issue by blackcat1944** [spring-projects/spring-security#5228]
### Summary

I have setup instagramClientRegistration after following facebook and google client registration sample code on https://github.com/jgrandja/springone2017-demo,

I get {"error_type": "OAuthException", "code": 400, "error_message": "You must provide a client_id"}
when I debug to the step httpRequest.send() in NimbusAuthorizationCodeTokenResponseClient class,
I have found the client id is null after TokenRequest object is constructed, but the client id has already been passed into clientAuthentication which is passed into tokenrequest construct.
### Actual Behavior

I checked out code from https://github.com/jgrandja/springone2017-demo demo-1 branch.

Put Instagram client registration in OAuth2LoginConfig file

private ClientRegistration instagramClientRegistration() {
		return ClientRegistration.withRegistrationId("instagram")
				.clientId("499c9d6ff96e4d1c8b95a7f55b1cfd1f")
				.clientSecret("df904273efbe4609b7c5dcd455f446c4")
				.clientAuthenticationMethod(ClientAuthenticationMethod.BASIC)
				.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
				.redirectUriTemplate("{baseUrl}/login/oauth2/code/{registrationId}")
				.scope("basic", "comments")
				.authorizationUri("https://api.instagram.com/oauth/authorize")
				.tokenUri("https://api.instagram.com/oauth/access_token")
				.userInfoUri("https://api.instagram.com/v1/users/self")
				.clientName("Instagram")
				.build();
	}

The error happens at the token request step after authorization code is obtained.

### Expected Behavior
should get the response like the response from making following call
 curl -F 'client_id=499c9d6ff96e4d1c8b95a7f55b1cfd1f' \
    -F 'client_secret=df904273efbe4609b7c5dcd455f446c4' \
    -F 'grant_type=authorization_code' \
    -F 'redirect_uri=http://localhost:8080/login/oauth2/code/instagram' \
    -F 'code=2a05e2a88d4f4002b48ed7dfbb6332c3' \
    https://api.instagram.com/oauth/access_token
	

### Configuration

application.yml

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false

Spring boot 2.0.1.RELEASE
### Sample

I simply use the code from https://github.com/jgrandja/springone2017-demo
and replace the googleClientRegistration with instagramClientRegistration

**Comment by jgrandja** [comment]
@blackcat1944 This issue is related to your configuration:

`.clientAuthenticationMethod(ClientAuthenticationMethod.BASIC)`

If you look at the [Instagram reference](https://www.instagram.com/developer/authentication/), in the section **Step Three: Request the access_token**, **ALL** parameters must be in the `POST` body including `client_id` and `client_secret`.

So what you need to do is change:

`.clientAuthenticationMethod(ClientAuthenticationMethod.BASIC)`

to

`.clientAuthenticationMethod(ClientAuthenticationMethod.POST)`

This will allow the code to progress with the `access_token` being returned but then this error will occur:

> [invalid_token_response] An error occurred parsing the Access Token response: Missing JSON object member with key "token_type"

Unfortunately, Instagram **does not conform** to the OAuth 2.0 spec for a [Successful Access Token Response](https://tools.ietf.org/html/rfc6749#section-5.1). You will notice in the Instagram reference that the Access Token response follows this structure:

```
{
    "access_token": "fb2e77d.47a0479900504cb3ab4a1f626d174d2d",
    "user": {
        "id": "1574083",
        "username": "snoopdogg",
        "full_name": "Snoop Dogg",
        "profile_picture": "..."
    }
}
```
And the OAuth 2.0 spec requires the `token_type` in the response:

> token_type
  REQUIRED.  The type of the token issued as described in Section 7.1.  Value is case insensitive.

You can work around this issue by providing your own implementation of `OAuth2AccessTokenResponseClient`. See the [reference](https://docs.spring.io/spring-security/site/docs/5.0.4.RELEASE/reference/htmlsingle/#oauth2login-advanced-token-client) on how to configure this.

Also, I want to point out that **Spring Security's goal is to be spec compliant** and any deviations from the spec would be custom implementations that the user would need to implement. However, we do provide the hooks to allow users to do so if required as is such in this case.

**Comment by blackcat1944** [comment]
@jgrandja Thanks for the explanation.

**Comment by rwinch** [comment]
@blackcat1944 It would be great if you could post back your findings and share your code if you come up with an `OAuth2AccessTokenResponseClient` that works with Instagram

**Comment by nseb** [comment]
No Workaround ?
even if instagram does not support the protocol completely, it would be interesting that spring proposes the integration, because it is only Instagram finally ;-)
