### ISSUE TITLE
StrictHttpFirewall causes lots of exception from tomcat url rewriting

### ISSUE THREAD

**Issue by g3ek** [spring-projects/spring-security#5267]
We lately get a lot of errors in our logs from the spring security firewall which was changed to a stricter version:
https://spring.io/blog/2018/01/30/cve-2018-1199-spring-security-5-0-1-4-2-4-4-1-5-released

It appears StricHttpFirewall does not know how to handle standard url rewriting from tomcat which appends the jsessionid (for clients not allowing cookies I guess).

The firewall gets a GET request like this:
/js/ours.js;jsessionid=XXXXXXXXXXXXXXXXXXXXXX?v=1.0

and rejects it:
The request was rejected because the URL contained a potentially malicious String ";"
Stacktrace
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String ";"
	at org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlacklistedUrls(StrictHttpFirewall.java:140)

I expect the firewall to properly recognise this url as normal.

spring-security-web v4.2.5 RELEASE
tomcat v8.5.29
Thymeleaf version: v3.0.9 RELEASE
Spring-boot: v1.5.12 RELEASE

**Comment by rwinch** [comment]
Thank you for your feedback.

You should not use jsessionid in your URLs because it is not secure. Among other things it can lead to session fixation attacks and leak sensitive (session ids) data.

[OWASP's Session Management Cheat sheet states](https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Session_Management_Implementation):

> The usage of specific session ID exchange mechanisms, such as those where the ID is included in the URL, might disclose the session ID (in web links and logs, web browser history and bookmarks, the Referer header or search engines), as well as facilitate other attacks, such as the manipulation of the ID or session fixation attacks [3].

The OWASP's Session Management Cheat sheet [goes on to say](https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Used_vs._Accepted_Session_ID_Exchange_Mechanisms):

> A web application should make use of cookies for session ID exchange management. If a user submits a session ID through a different exchange mechanism, such as a URL parameter, the web application should avoid accepting it as part of a defensive strategy to stop session fixation.
>
> NOTE: Even if a web application makes use of cookies as its default session ID exchange mechanism, it might accept other exchange mechanisms too. It is therefore required to confirm via thorough testing all the different mechanisms currently accepted by the web application when processing and managing session IDs, and limit the accepted session ID tracking mechanisms to just cookies. In the past, some web applications used URL parameters, or even switched from cookies to URL parameters (via automatic URL rewriting), if certain conditions are met (for example, the identification of web clients without support for cookies or not accepting cookies due to user privacy concerns).

What's more is that allowing path parameters (i.e. `;`) in your URL has a history of allowing URL based security bypasses, Reflected Download Attacks, and more. In general, path parameters of any sort are not a risk that you should take. You can find additional information within the [Javadoc of StrictHttpFirewall](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/web/firewall/StrictHttpFirewall.html#setAllowSemicolon-boolean-)

You can [disable the feature](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#request-matching) if you like, but it is not recommended for the reasons listed above.

**Comment by g3ek** [comment]
This is only the first time when a client connects to our site.
So BEFORE the server can establish if a client accepts cookies or not.

I raised the same issue with the thymeleaf dev:
https://github.com/thymeleaf/thymeleaf/issues/684

"The addition of the ;jsessionid=... path parameter is a normal and (usually) desirable part of the standard URL Rewriting mechanism in Java web applications. The idea is that, when an application has already expressed its need to create a user Session, the ID for such user session has to be passed along to the browser somehow. And until the browser demonstrates that it has the capability of using (and permission to use) cookies by means of an HTTP header in the following request after receiving that jsessionid, the ;jsessionid=... path parameter is how this is done in most Java Servlet-based web servers like e.g. Tomcat."

**Comment by rwinch** [comment]
@g3ek I'm interested how you are coming across including the JSESSIONID in your URL in the first place. Spring Security's default is to explicitly avoid including the jsessionid in the URL. This means to run into the problem the application would have to explicitly provide a Spring Security configuration like:

```java
http
  .sessionManagement()
    .enableSessionUrlRewriting(true);
```

If you configure spring security to ignore parts of your application the above setting is not going to have an impact for them. Instead of ignoring the application, you should configure it to `permitAll`.

As an additional or alternative measure, you can also configure the tracking mode of Tomcat within Spring Boot using something like this:

```
server.servlet.session.tracking-modes=cookie
```
Either mechanism will ensure the jsessionid is not appended to the URL.

**Comment by g3ek** [comment]
That's a good question (about how the JSESSIONID happens to be appended).
However, if you read the thymeleaf issue and read the response of the dev it is perfectly normal (for clients not able to demonstrate they accept cookies).

This also happens the first time a user accesses our site (via the root path).
User should be redirected to /user/login which is defined in our configuration to 'permitAll'.
User gets a 500 page. User then reports redirects normally a refresh to the login page.

**Comment by rwinch** [comment]
> However, if you read the thymeleaf issue and read the response of the dev it is perfectly normal (for clients not able to demonstrate they accept cookies).

You are right it is normal, but it is also insecure. By default Spring Security disables the container from including the jsessionid in the URL because it is insecure.  You have two options:

1) Prevent the jsessionid from being added to the URL as I described in https://github.com/spring-projects/spring-security/issues/5267#issuecomment-386339274

2) NOTE: This option is not considered secure. Allow the jsessionid to be in the URL and then modify the firewall to allow semicolons.

**Comment by g3ek** [comment]
Oh dear we use spring-boot with a yml config file and, just for future references it should be:
server:session:tracking-modes:cookie
