### ISSUE TITLE
Add HttpServletResponse parameter to AuthorizationRequestRepository.removeAuthorizationRequest

### ISSUE THREAD

**Issue by naturalprogrammer** [spring-projects/spring-security#5313]
Issue discussed at https://stackoverflow.com/questions/49095383/spring-security-5-stateless-oauth2-login-how-to-implement-cookies-based-author

Spring Security version: 5.0

**Comment by jgrandja** [comment]
@naturalprogrammer Thanks for the report. I see the issue here. For your `HttpCookieOAuth2AuthorizationRequestRepository` you do need the `HttpServletResponse` in the `removeAuthorizationRequest()` operation.

Would you be interested in submitting a PR for this along with your Cookie-based implementation?

**Comment by naturalprogrammer** [comment]
Yes @jgrandja, I'll be happy to. I guess I'll need to fork the repo, do the change, test it locally, and then create a pull request. Not done this before -- do you have any exact guidelines somewhere?

**Comment by jgrandja** [comment]
@naturalprogrammer Please see [Contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md) as well as the [main page]( https://github.com/spring-projects/spring-security) for other information, e.g. Building from Source.

Please let me know if you have any other questions.
Thanks!

**Comment by naturalprogrammer** [comment]
Thank you @jgrandja. Gave a closer look. Seems like setting my development environment is going to need some time, which I could plan at a cooler time. Meanwhile, let me just share my idea in case anyone jumps to it before I can:

1. For supporting existing as well as new implementations, in `AuthorizationRequestRepository`, change the existing `removeAuthorizationRequest` method to provide a default empty implementation, and code a new default method in as below
   ```java
   default T removeAuthorizationRequest(HttpServletRequest request, HttpServletResponse response) {
            removeAuthorizationRequest(request)
   }
    ```
1. Change `OAuth2LoginAuthenticationFilter.attemptAuthentication` to call this new method instead of the old one.

An HttpCookieOAuth2AuthorizationRequestRepository similar to [this one](https://github.com/naturalprogrammer/spring-lemon/blob/master/src/main/java/com/naturalprogrammer/spring/lemon/security/HttpCookieOAuth2AuthorizationRequestRepository.java) can also be coded, but if we can push the above two changes earlier, that would enable supporting cookie based implementations.

**Comment by jgrandja** [comment]
@naturalprogrammer Makes sense. Let me know if your time free's up to work on this or I'll get to it at some point.

**Comment by jgrandja** [comment]
@naturalprogrammer I just got this merged to master in time for the M2 release tomorrow.

**Comment by alexander00001** [comment]
Hi @jgrandja, using cookies instead of sessions to use oauth2 with a stateless backend is exactly what I was looking for. Is there any plan when the solution from @naturalprogrammer can be incorporated into the standard spring-security library? This would definitly be very helpful. Thanks!

**Comment by jgrandja** [comment]
@alexander00001 There is no current plan to add a cookie-based implementation of `AuthorizationRequestRepository`. If the user required such an implementation, it would be fairly trivial to implement and than they can configure it as per the [ref doc](https://docs.spring.io/spring-security/site/docs/5.1.2.RELEASE/reference/htmlsingle/#oauth2Client-authorization-request-repository). I'm not sure if much value would be added if we housed this in Spring Security. Let me give this some thought.

**Comment by alexander00001** [comment]
Hi @jgrandja, thank you for your answer! Maybe your right. I thougt that this would be the only thing to do to achive a stateless server but this seems to be wrong. I Implemented the cookie based  AuthorizationRequestRepository and this part seems to work well but if i set SessionCreationPolicy to stateless it seems to me that SecurityContextHolder will loose nessesary informations after redirects with the next request. I think I have to do more than the AuthorizationRequestRepository  stuff. Right now I'm experimenting with additional JWT Tokens which I try to set in the success handler and read again in a filter. But this is not working by now. I'm a little supprised that it is so complicated to find tutorials and examples for such a common use case like using stateless servers with REST services behind a load balancer without using sticky sessions or clustered caches for session replication. 
But please don't get me wrong. I'm very pleased about your answer and this is no accusation ;-)

**Comment by jgrandja** [comment]
@alexander00001 

> I thougt that this would be the only thing to do to achive a stateless server but this seems to be wrong

I can appreciate the benefits of having a stateless application but that cannot be applied in all scenarios. If your app requires authentication, eg. `oauth2Login()`, than after the user successfully authenticates the `SecurityContext` and associated `OAuth2AuthenticationToken` is established and must be persisted across requests in order to prevent re-login. By default, it's stored in `HttpSession`. So you are right when you say 

> I think I have to do more than the AuthorizationRequestRepository stuff

Have you taken a look at [Spring Session](https://spring.io/projects/spring-session)? You can leverage this to store session attributes to an external store, eg. Redis, instead of the default Servlet container. This might be what you are looking for?

Resource Servers that accept JWT's can easily be stateless but client applications that require authentication need to store the authentication context information somewhere. I hope this helps?

**Comment by jgrandja** [comment]
@alexander00001 I added this ticket #6374. Feel free to upvote.
