### ISSUE TITLE
OAuth2ClientWebMvcSecurityConfiguration fails unless there is a single Bean

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#5321]
### Summary

`OAuth2ClientWebMvcSecurityConfiguration` fails unless there are exactly one Bean of type `ClientRegistrationRepository` and exactly one bean of type `OAuth2AuthorizedClientService` with no simple way to resolve the failure. This might be important since `ClientRegistrationRepository` might not be a Bean. Additionally, there might be multiple `ClientRegistrationRepository` if there are multiple `WebSecurityConfigurerAdapter` instances.

**Comment by jgrandja** [comment]
@rwinch Yes, if there are 2 or more `ClientRegistrationRepository` and/or `OAuth2AuthorizedClientService` registered in the context than `OAuth2ClientWebMvcSecurityConfiguration` will fail.

I can get around this by defining an `ObjectProvider<ClientRegistrationRepository>` and `ObjectProvider<OAuth2AuthorizedClientService>`. However, it would still fail in `OAuth2LoginConfigurer` and `OAuth2ClientConfigurer`, which both leverage `OAuth2ClientConfigurerUtils` to lookup the `ClientRegistrationRepository` and `OAuth2AuthorizedClientService` in the context.

Furthermore, it would also fail in Boot's `OAuth2WebSecurityConfiguration` since it expects 1 `ClientRegistrationRepository`.

If you recall, the original design intent is to only allow for 1 `ClientRegistrationRepository` and `OAuth2AuthorizedClientService`. Do you see a need where the user may want 2+ of each?

The one comment you made:

> This might be important since ClientRegistrationRepository might not be a Bean

...needs to be addressed since `ClientRegistrationRepository` and/or `OAuth2AuthorizedClientService` might not be registered as a `@Bean` and will not be  consumed by `OAuth2ClientWebMvcSecurityConfiguration` resulting in unexpected behaviour and a bug. I can resolve this by auto bean registration when the user configures via the `SecurityConfigurer`.

**Comment by rwinch** [comment]
I agree there are other places where it will fail if there isn't a single Bean. This behavior within the OAuth code is unique. For example, we guard against multiple beans when selecting a AuthenticationManager, AuthenticationProvider, UserDetailsService, etc. Why can't this be fixed within OAuth as well?
