### ISSUE TITLE
Add additional parameters to OAuth2UserRequest

### ISSUE THREAD

**Issue by XYUU** [spring-projects/spring-security#5368]
### Summary
Add additional parameters to OAuth2UserRequest, some third-party OAuth2.0 service UserInfoService must have additional parameters in OAuth2AccessTokenResponse.

### Actual Behavior
Cannot be used now because of missing parameters.

### Expected Behavior
Expect to implement additional parameters by configuring userInfoUri.

### Configuration

user-info-uri: https://api.weibo.com/2/users/show.json?uid={uid}

**Comment by jgrandja** [comment]
@XYUU This is not clear to me:

> some third-party OAuth2.0 service UserInfoService must have additional parameters in OAuth2AccessTokenResponse

How is the `UserInfoService` related to a `OAuth2AccessTokenResponse`? Please provide more detail.

**Comment by XYUU** [comment]
Some third-party OAuth2.0 service UserInfoService needs to add the additional parameters in OAuth2AccessTokenResponse to OAuth2UserRequest in order to use these parameters in UserInfoService.

Such as OAuth2 AccessToken Response:
```javascript
{
    "access_token": "1.a6b7dbd428f731035f771b8d15063f61.86400.1292922000-2346678-124328",
    "expires_in": 86400,
    "refresh_token": "2.385d55f8615fdfd9edb7c4b5ebdc3e39.604800.1293440400-2346678-124328",
    "scope": "basic email",
    "uid": "90090909",
}
```

user-info-uri: https://api.weibo.com/2/users/show.json?uid={uid}

UserInfoService expects to expand to：

```
https://api.weibo.com/2/users/show.json?uid=90090909&access_token=1.a6b7dbd428f731035f771b8d15063f61.86400.1292922000-2346678-124328
```

**Comment by jgrandja** [comment]
I understand. Let me see what I can do and I'll get back to you shortly.

**Comment by jgrandja** [comment]
@XYUU This issue has been resolved. You will now have access to `OAuth2AccessTokenResponse.additionalParameters` in `OAuth2UserRequest.additionalParameters`.

Also, take a look at #5641 which will provide you the capability to customize the UserInfo request by overriding `DefaultOAuth2UserService.buildRequest()`. Alternatively, instead of extending/overriding, you can provide a `RestOperations` via `DefaultOAuth2UserService.setRestOperations()` and modify the outgoing request however you like using a `ClientHttpRequestInterceptor`.

This should give you the flexibility you need.
