### ISSUE TITLE
Throughput performance of schedulers in UserDetailsRepositoryReactiveAuthenticationManager

### ISSUE THREAD

**Issue by PhilHardwick** [spring-projects/spring-security#5406]
### Summary

When using basic auth and UserDetailsRepositoryReactiveAuthenticationManager, the throughput of the application is hampered by using `.publishOn(Schedulers.parallel())` in the authenticate method.  `Schedulers.parallel()` assigns a fixed thread pool based on the number of CPUs. It means that password encoding, if it takes a long time (which is generally the case with a good encoder), blocks the processing of other requests.

### Actual Behavior

Under high loads the application takes a long time to process requests - causing timeouts and connection refusals - essentially causing back pressure as the assigned thread pool cannot cope with the incoming requests.

### Expected Behavior

There should be higher throughput. Under high loads the application processes requests with basic auth in the background and responds quicker to higher loads. 

### Version

5.0.5.RELEASE

### Sample

https://github.com/PhilHardwick/spring-security-reactive-schedulers

### Possible fixes
If you believe there to be an issue there's a few possible fixes. My fix was to change the scheduler to an elastic thread pool. This makes the application slightly slower at lower loads (I assume because of the cost of switching threads) but enables better throughput at higher loads.

1. Make the scheduler configurable
2. Change the default scheduler to an elastic thread pool
3. Just document it so people can choose to override the whole ReactiveAuthenticationManager if they want

**Comment by rwinch** [comment]
@PhilHardwick Thanks for the ticket.

Password validation is a CPU intensive task. If the the thread validating a password yields to another thread then there will be no progress in the validation. This differs from something like blocking IO which would be able to continue as the CPU processes another thread. Since adding more threads and managing more threads adds more overhead, we should stick with `Schedulers.parallel()` as the default and advise this for modern password encoders which are CPU intensive.

I tried running the tests you provided. On my machine running with `Schedulers.parallel()` there are no timeouts. Running using `Schedulers.elastic()` about 1% of the tests fail. This result supports the use of `Schedulers.parallel()` being better and seems to contradict what your findings were.

All that said, there are likely times where the user may want to customize the scheduler. For example, if they are using `NoOpPasswordEncoder` they may want to use `Schedulers.immediate()`. For that reason, I have added created #5417 Given this meets one of your asks, I will be closing this in favor of previously mentioned ticket.

It is probably worth highlighting this point in [the reference](https://docs.spring.io/spring-security/site/docs/5.0.x/reference/htmlsingle/#core-services-password-encoding):

> Because adaptive one-way functions are intentionally resource intensive, validating a username and password for every request will degrade performance of an application significantly. There is nothing Spring Security (or any other library) can do to speed up the validation of the password since security is gained by making the validation resource intensive. Users are encouraged to exchange the long term credentials (i.e. username and password) for a short term credential (i.e. session, OAuth Token, etc). The short term credential can be validated quickly without any loss in security.
