### ISSUE TITLE
Support OAuth2AuthorizationRequestCustomizer for DefaultOAuth2AuthorizationRequestResolver

### ISSUE THREAD

**Issue by mhyeon-lee** [spring-projects/spring-security#5525]
### Summary

I know project will support configurable OAuth2AuthorizationRequestResolver. (#5521)
but, It would be nice to provide a customizer to reuse the DefaultOAuth2AuthorizationRequestResolver.

### Sample

``` java
public final class DefaultOAuth2AuthorizationRequestResolver implements OAuth2AuthorizationRequestResolver {
     private OAuth2AuthorizationRequestCustomizer authorizationRequestCustomizer;
     ...
     ...
     @Override
     public OAuth2AuthorizationRequest resolve(HttpServletRequest request) {
          ...
          ...
          OAuth2AuthorizationRequest.Builder authorizationRequestBuilder = builder
				.clientId(clientRegistration.getClientId())
				.authorizationUri(clientRegistration.getProviderDetails().getAuthorizationUri())
				.redirectUri(redirectUriStr)
				.scopes(clientRegistration.getScopes())
				.state(this.stateGenerator.generateKey())
				.additionalParameters(additionalParameters);
          this.authorizationRequestCustomizer.customize(request, authorizationRequestBuilder);
          return authorizationRequestBuilder.build();
      }
}
```

java config
``` java
http
     .oauth2Login()
     .authorizationEndpoint()
     .authorizationRequestCustomizer(customizer);
```

**Comment by mhyeon-lee** [comment]
this issue related: #5466

**Comment by jgrandja** [comment]
Thank you for your feedback and suggestion @mhyeon-lee.

Please take a look at the tests below as they show you how to customize the `OAuth2AuthorizationRequest` :

[Test 1](https://github.com/spring-projects/spring-security/blob/master/oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/OAuth2AuthorizationRequestRedirectFilterTests.java#L306)
[Test 2](https://github.com/spring-projects/spring-security/blob/master/oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/OAuth2AuthorizationRequestRedirectFilterTests.java#L337)

I understand your main goal is to **reuse** instead of **copy** (as is the case with the current implementation scenario), however, I would prefer to avoid creating a new API if possible.

What are your thoughts on removing the `final` on `DefaultOAuth2AuthorizationRequestResolver` and providing a `protected` method that allows for this customization?

**Comment by mhyeon-lee** [comment]
Yes. What I want is to extract the desired value from the HttpServletRequest information(queryParam, Header ....) and apply it in the OAuth2AuthorizationRequest.

It will be enough to decorate and add information like Test Sample.

**Comment by jgrandja** [comment]
@mhyeon-lee 
> It will be enough to decorate and add information like Test Sample

Sounds like the tests I provided will work for your use case? Would you mind closing this issue if this suits your needs?

**Comment by mhyeon-lee** [comment]
@jgrandja 
Yes, this is enough for now.
Thank you for your guidance.
