### ISSUE TITLE
BearerTokenRequestMatcher hides exception

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#5566]
The `BearerTokenRequestMatcher` hides an exception.

```java
public boolean matches(HttpServletRequest request) {
	try {
		return this.bearerTokenResolver.resolve(request) != null;
	} catch ( OAuth2AuthenticationException e ) {
		return false;
	}
}
```

Hiding an exception can be difficult when the user is troubleshooting an issue.
We should either throw the exception or log it or a combination of these?

**Comment by jzheaux** [comment]
@jgrandja if you don't mind, I'll assign this when I'm working on it. That way it will allow the community to come in, if they get to it before me.

**Comment by jzheaux** [comment]
Yes, I think we could log it at a debug level, and while I typically prefer to do this so that debug information isn't lost, I'm not convinced that loss happens in this specific case.

This precise method (resolver.resolve) is also called by the BearerTokenAuthenticationFilter. The filter does transmit the result of this exception through the WWW-Authenticate header, so I don't believe that the error information will be lost (since the same exception thrown here will be thrown in BearerTokenAuthenticationFilter a few microseconds after).

If we added a debug statement here, I'm not really sure what we would say that wouldn't slightly mislead the user. For example, if we said "Failed to match this request as a bearer token request", it is a little bit out of context since it is really the CsrfFilter that is executing this. A more correct message would be "Failed to establish this request as containing a bearer token; cannot exclude it from CSRF checks on these grounds, then".

Looking at the whole picture, I think a log message in BearerTokenAuthenticationFilter would be more informative to the user from a debugging standpoint:

```java
try {
    token = this.bearerTokenResolver.resolve(request);
} catch ( OAuth2AuthenticationException invalid ) {
    log.info("Bearer token request failed when extracting bearer token", invalid);
    this.authenticationEntryPoint.commmence(request, response, invalid);
    return;
}
```

**Comment by jgrandja** [comment]
@jzheaux After coming back to this and reviewing it again, I think what we have now is correct. I also agree that it doesn't make sense to log a message if an exception is thrown by the `CsrfFilter`. If it's thrown by `CsrfFilter` (e.g. token is in header and body) than it will get thrown by `BearerTokenAuthenticationFilter` on subsequent filter processing and the error message will get communicated via the `BearerTokenAuthenticationEntryPoint` which is exactly where the error message should get communicated.

I'm going to close this issue as the current behaviour is what is expected.
