### ISSUE TITLE
Add org.springframework.security.oauth libs to BOM file

### ISSUE THREAD

**Issue by Alexuy** [spring-projects/spring-security#5722]
Hi!

I'm trying to use org.springframework.security.oauth2.client.OAuth2RestTemplate class from spring-security-oauth2 lib, but found that this library is not included in any of the BOM-files.

I looked at the following BOM files:

org.springframework:spring-framework-bom,
org.springframework.security:spring-security-bom
org.springframework.boot:spring-boot-dependencies
org.springframework.cloud:spring-cloud-dependencies

but none of them contain information about this library.

The only thing I managed to find - is the library "org.springframework.cloud:spring-cloud-starter-oauth2", but it provides too much functionality and pulls for itself a bunch of different libraries.

Can you add org.springframework.security.oauth:* libs to BOM file or create BOM-file for that package?

**Comment by rwinch** [comment]
Thanks for the report @Alexuy! First which bom file are you speaking about? Spring Security does not have "org.springframework.cloud:spring-cloud-starter-oauth2" in its bom because that is a Spring Cloud dependency. We would also not have org.springframework.security.oauth:* libs in our BOM because it is a [separate project](https://github.com/spring-projects/spring-security-oauth).

NOTE: You might also read about [Next Generation OAuth 2.0 Support with Spring Security](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security)

**Comment by Alexuy** [comment]
@rwinch thank for information!

Oh, i didn't know that! As i understand, now you migrating functionality from old org.springframework.security.oauth libraries to new spring-security-oauth-client and spring-security-oauth-server libraries.

Could you add to your new spring-security-oauth-client OAuth2RestTemplate ? Because now, i can't use your client library for using OAuth for third party systems,.

**Comment by rwinch** [comment]
If you want to continue using the old mechanism it will be supported until at least 1 year after we have feature parody with the old OAuth support. You can integrate using https://github.com/spring-projects/spring-security-oauth2-boot/

In Spring Security 5.1 we are adding support for using Spring Security OAuth + WebClient which is a bit different, but the preferred way going forward.

**Comment by rwinch** [comment]
Closing this as invalid
