### ISSUE TITLE
Auto detection/registration of filter does not ignore defined paths

### ISSUE THREAD

**Issue by simplier** [spring-projects/spring-security#5764]
### Summary
I have a filter which is an extension of OncePerRequestFilter and with @Component annotation. I would like to ignore some paths with `web.ignoring().antMatchers(...);` completely even from the filter. But the request with those ignoring paths still go through the filter. It will not if I add the filter manually under `protected void configure(HttpSecurity http) throws Exception`

### Actual Behavior
The auto registration of filter does not ignore defined paths

### Expected Behavior
The auto registration of filter should ignore defined paths defined as `web.ignoring().antMatchers(...);`

### Version
Spring Boot 1.5.7.RELEASE, Spring security 4.2.3.RELEASE

**Comment by rwinch** [comment]
If you register the custom Filter directly with the container (this is done automatically in Spring Boot), then ignoring will not help.

One thing you can do is to wrap the Filter in an instance of FilterChainProxy so that the Filter is only performed for certain URLs. Another option is to only register the Filter for certain URLs. In Spring Boot this is done with a FilterRegistrationBean. If you are working with the container directly, you can modify the web.xml or the equivalent to only perform on certain URLs.

Also keep in mind that ignoring will disable ALL of security for those URLs (which is likely not what you want). Even if you are ignoring static resources this can disable important security features (i.e. HSTS headers) that are important to have on static resources.

I'm going to close this, but please reopen with more details if this does not answer your question.

**Comment by simplier** [comment]
I could be able to define the FilterRegistrationBean, however my use case is not to include path patterns but to exclude those patterns that defined as ignored. I don’t need requests to those paths going though any security filter at all. One of my path is, for example, health indicator REST resource.

**Comment by simplier** [comment]
the thing is, there is a difference: when Spring detects and adds the filter automatically, it includes also defined ignored paths. Adding the filter manually with HttpSecurity, the ignored paths are excluded.

**Comment by rwinch** [comment]
> I could be able to define the FilterRegistrationBean, however my use case is not to include path patterns but to exclude those patterns that defined as ignored. I don’t need requests to those paths going though any security filter at all.

This doesn't sound security related then.

If you want you can leverage FilterChainProxy to wrap your Filter to determine if it should be invoked. If not, then add conditional logic in your Filter to determine if it should add additional logic or just invoke the original FilterChain.
