### ISSUE TITLE
context path used in oauth2

### ISSUE THREAD

**Issue by xuchang-x** [spring-projects/spring-security#5765]
### Summary
when i delete the 'server servlet context-path' attribute in both server and client it sink into the login page in server.

### Actual Behavior
situation 1: 
Keep the server servlet context-path' attribute in both server and client, or one of them.
The app can work smoothly;

situation 2: 
Delete the server servlet context-path' attribute in both server and client.
The app with sink into the login page inserver .

situation 3:
Delete the attribute in both side, expose the "/login" endpoint in client side.
It comes to find the "/error" model straitly .

### Expected Behavior
It can work well when i delete the context-path attribute.

### Configuration

spring-boot-starter-security 2.0.4.RELEASE
spring-boot-starter-web 2.0.4.RELEASE
spring-security-oauth2-autoconfigure 2.0.0.RELEASE

### Sample
git@github.com:xuchang-x/spring-oauth2-issue.git

**Comment by rwinch** [comment]
I'm not sure I understand, but I am going to take stab at answering this.

If you use the same host (even if it is a different port) then the cookie will get overridden unless the cookie path is different. This means deleting the context path attribute for both client and server and interacting through the same host (even if it is a different) port, you will not get expected behavior. This is not a limitation within Spring Security, but is how browsers work.

If this does not answer your question, please ask in https://github.com/spring-projects/spring-security-oauth since that is a separate project from Spring Security itself.
