### ISSUE TITLE
idToken certificate auto reload in OidcAuthorizationCodeAuthenticationProvider

### ISSUE THREAD

**Issue by zcwang3** [spring-projects/spring-security#5840]
### Summary

In current implementation of spring security, openID provider's **jwk certificate is loaded by NimbusJwtDecoderJwkSupport** and stored in ConcurrentHashMap of **jwtDecoders** properties in OidcAuthorizationCodeAuthenticationProvider. The certificate will never expired and reload from openID provider web site. It may cause problem because openID provider may rotate key pairs for ID token generate and validate.

For example, from the following description copied from [Azure Active Directory v2.0 tokens reference
](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-id-and-access-tokens#validating-tokens),  Microsoft may rotate keys and it will cause **id token generated by latest jwk certificate can not be verified by jwtDecoders which loaded from app start up with old jwk certificate**.
    The v2.0 endpoint signs ID and access tokens by using any one of a specific set of public-private key pairs. The **v2.0 endpoint periodically rotates the possible set of keys**, so your app should be written to handle those key changes automatically. A reasonable frequency to check for **updates to the public keys used by the v2.0 endpoint is every 24 hours**.

Could we add **auto reload openID provider's **jwk certificate every day** in OidcAuthorizationCodeAuthenticationProvider?

[zcwang3] 
I saw the logic in RemoteJWKSet which will automatically handle new key from OpenID provider, so it should can **handle the case I mentioned**. 
We can mark the issue as Junk.

**Comment by jzheaux** [comment]
@zcwang3, thanks for the report!

Key rotation should be triggered whenever a new, unrecognized key is presented in a JWT, should handle most rotation use cases. The limitation here is that if no new key ever comes in, then old keys may continue to be accepted (since there is nothing to trigger the refresh).

I've logged a ticket to Nimbus to [add support for actively expiring the cached key set](https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/278/remotejwkset-should-proactively-refresh), which you are welcome to follow.

Have you seen any issues during rotation? e.g. the client application accepting JWTs that are signed by expired keys.

**Comment by zcwang3** [comment]
@jzheaux thanks for you follow up.

i have met a case:
a Google ID token is generated about a month ago, and write the id token together with id token verification script.

about a month later, i rerun the script, key error is populated instead of id token is expired.
it shows that the original key is rotated and not supported any more.

In previous case, if a server in running up a month, it may have issue to verify id token if key is rotated in Google.

To fix previous issue, I think in most case, auto reload key certificate every day (configurable) should be fine.
Auto reload key if key does not exist in latest JWT should be even better for performance.

**Comment by rwinch** [comment]
@zcwang3 So the issue you are running into is that the error being reported is that the key was missing rather than the token was expired?

If that is the case, I don't think there is anything we can do for that. We cannot and should not keep track of all of the old keys. Trying to keep track of all the keys means that we would potentially run out of space. What is more, there is a chance that the authorization server had keys that we have never seen before.. We could potentially allow you to map the missing key to a custom error though.

**Comment by jgrandja** [comment]
@zcwang3 I'd like to clarify one of your statements so we're on the same page.

> In current implementation of spring security, openID provider's jwk certificate is loaded by NimbusJwtDecoderJwkSupport and stored in ConcurrentHashMap of jwtDecoders properties in OidcAuthorizationCodeAuthenticationProvider. **The certificate will never expired and reload from openID provider web site.**

`NimbusJwtDecoderJwkSupport` which uses Nimbus's `RemoteJWKSet` automatically handles the refreshing of the `JWKSet` (the `PublicKey`'s) if the `kid` from the JWT Header is not found in it's `Set`.

If you look deeper into the call stack on where the Key matching happens, you would follow this association chain:

`NimbusJwtDecoderJwkSupport` -> `ConfigurableJWTProcessor` -> `JWSKeySelector` -> `JWKSource` (`RemoteJWKSet`)

Then look at the implementation of `RemoteJWKSet.get(...)`, you will see that it handles a re-fetch of the `JWKSet` if the `kid` in the JWT Header is not found in the `JWKSet`.

So the `PublicKey`(s) are ultimately cached in `RemoteJWKSet.cachedJWKSet`, which holds each `JWK` and therefore can be translated to a `PublicKey`.

Can you please double-check on your test scenario again where the ID Token validation fails and provide a detailed stack trace? I'm wondering if the Provider (Microsoft?) is reusing the same `kid` after they rotate the keys? Hopefully not because I'm not sure what we can do about this scenario.

The Provider should use a new `kid` for each new (rotated) key. If this is the case, then when the ID Token verification happens, the `RemoteJWKSet` will re-fetch the `JWKSet` because the new `kid` would not be found in the `RemoteJWKSet.cachedJWKSet`.

Does this make sense?

**Comment by zcwang3** [comment]
@jgrandja Thanks for replying.

Yes, you are right.
I saw the logic in RemoteJWKSet which will **automatically handle new key from OpenID provider**, so it should can handle the case I mentioned. Sorry for the confusion.

@rwinch Thanks
We should not keep track of all old keys, instead we should catch up with new keys, and current implement already has the ability. Sorry for the confusion.

We can mark the issue as Junk.

**Comment by jgrandja** [comment]
@zcwang3 No worries about the confusion. I'm glad that you see the auto-refresh of keys is handled within Nimbus.

**Comment by jgrandja** [comment]
Let's leave this open so we can track the progress on [RemoteJWKSet should proactively refresh its cache](https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/278/remotejwkset-should-proactively-refresh)

**Comment by jgrandja** [comment]
@jzheaux Feel free to create a new issue to track against the issue you logged with Nimbus and close this one?

**Comment by jzheaux** [comment]
Done - https://github.com/spring-projects/spring-security/issues/5853
