### ISSUE TITLE
NimbusReactiveJwtDecoder should accept a Nimbus JWTProcessor

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#5937]
The Nimbus JwtDecoders, both servlet and reactive, simplify Nimbus configuration by exposing some basic use cases like using a JWK Set Uri or by using a single public key.

Many scenarios are more complex than this, and Nimbus is a full-featured API that allows users to configure for these more complex scenarios.

#5648 proposes addressing this on the servlet side by introducing a constructor that accepts a `JWTProcessor` instance.

Because of certain preprocessing that `NimbusJwtReactiveDecoder` does in order to maintain its non-blocking nature as it interacts with Nimbus, it is not yet clear how we might expose the `JWTProcessor` there; though coordinating with the Nimbus team may bear some fruit.

**Comment by jzheaux** [comment]
I'm not sure that exposing `NimbusReactiveJwtDecoder`'s context-creating is a good idea. This is definitely a workaround for Nimbus lacking a non-blocking JWK retrieval API.

Ideally, Nimbus would add a non-blocking API, and perhaps there is an opportunity for the community to help with that.

Another possibility might be to introduce `ReactiveJWTProcessor` into Spring Security:

```java
public interface ReactiveJWTProcessor<C extends SecurityContext> {
    Mono<JWTClaimSet> process(SignedJWT signedJWT, C context);
}
```

with a default implementation that performs the same workaround that `NimbusReactiveJwtDecoder` does today. Then, `NimbusReactiveJwtDecoder` could take `ReactiveJWTProcessor` as a constructor parameter.

It would help to know what particular problem you are trying to solve, @GregoireW. What is your specific need for passing in your own `JWTProcessor` to `NimbusReactiveJwtDecoder`?

**Comment by GregoireW** [comment]
I write in my previous message that I saw 2 way of solving the issue. First is like you say with the interface. 
Note that the context is not required in this case as it is linked to the processor and will be hidden in the implementation (else we need to get a context from somewhere so it is like the implementation I wrote)

```java
public interface ReactiveJWTProcessor {
    Mono<JWTClaimSet> process(SignedJWT signedJWT);
}
```

or the one I write in the PR   with a processor and a initializer. In this use case, processor and initializer are coupled a little bit (not so great yes but ...) 

I choose the processor + initializer only because 
  - sometime initializer is not needed 
  - I guess we can have a key selection business much more complex than the default code (what happens if I got a JWKS that reference RS256 key, then RS512 key then ECDSA-P256) followed by a simple processor.   

But It is clearly a pure tail/head choice.
If you prefer an interface with
>    Mono<JWTClaimSet> process(SignedJWT signedJWT);

it is a simple refactoring. I can do it. ( who validate? )


Now going back to my usecase: 
- I'm not sure my identity provider will stay on the RS256 signature mode. 
- Most of the application we wrote in my organization are behind corporate proxy. I need to push the key to the context in a reactive way, then call the nimbus processor. Today, the RemoteSource is not so great to setup. I add a small "WebClient" parameter to be able to fix that.


PS: I just saw that I got 2 errors in the build, I will check that...

**Comment by jzheaux** [comment]
I've opened a ticket with Nimbus and we'll see where that goes: https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/296/consider-having-jwtprocessor-accept-key

**Comment by jzheaux** [comment]
My point in the ticket was to highlight how Spring Security solves the problem today, via a custom `SecurityContext`, and to gauge whether or not that was contrary to its intended use.

Vladimir confirmed in his reply that this kind of scenario is what `SecurityContext` was meant for, which actually was contrary to my expectations.

**Comment by jzheaux** [comment]
@GregoireW I think the next step is to work with Nimbus to see if we can get some of the Spring Security code accepted there, in order to legitimize and clarify the approach. Since it's Nimbus's position that it's okay, let's see if we can get a stronger API definition on that side of things.

At the very least, `JWKContext` or something similar should live in Nimbus. I'll submit a PR to Nimbus as report back here.

In the meantime, the work that `NimbusReactiveJwtDecoder` does is pretty minimal. You should be able to roll your own implementation of `ReactiveJwtDecoder` that hits your corporate proxy as you described. Let me know if you run into problems with that.

**Comment by GregoireW** [comment]
I already do something on my projects to make it works (and it is ok), 

My main issue is that some "common" classes are protected, it means I need to copy a lot of code (or create a beautiful package org.springframework.security.oauth2.jwt in my applications ) to be able to make this work. 

It is why I'm so motivated to upgrade this on spring side to drop those things as soon as possible ;)

**Comment by GregoireW** [comment]
Anyway I refactor stuff to be cleaner with somehow what I use on my project now
