### ISSUE TITLE
Obtain Users Password in Plain Text during authentication

### ISSUE THREAD

**Issue by garrit-schroeder** [spring-projects/spring-security#5953]
Hello,
i would like to get the users password in plain text just during authentication.
All passwords are hashed in the database with BCryptPasswordEncoder.class.
But i need the password in plain text so i can encode and decode other data with the users password.

Is there a good way?

**Comment by rwinch** [comment]
> But i need the password in plain text so i can encode and decode other data with the users password.

I'm not sure this is a good idea since user's passwords are often quite weak. It is better to create a secure random key and use that instead.

> Is there a good way?

You can validate the password at time of authentication. Then you can use the password that the user typed (plain text) instead of the one that was stored (hashed).

PS: Please post questions to StackOverflow where there are more people that can help answer them.

**Comment by rwinch** [comment]
Closing as answered. If you have additional questions, please use StackOverflow
