### ISSUE TITLE
WebClient client_credentials Question

### ISSUE THREAD

**Issue by dlesnef1** [spring-projects/spring-security#5974]
I have a question regarding the client credentials flow for OAuth 2. I will outline the question below, but a more detailed version I wrote can be found on [StackOverflow](https://stackoverflow.com/questions/52614683/spring-webclient-and-client-credentials-grant) (Apologies if linking to SO is not allowed).

I am trying to upgrade my Spring Security version to 5.1.0 and move from RestTemplate to WebClient. In doing so I would like to have the WebClient Bean always send my Bearer token (and refresh it if it is expired).

I have read over many documents on the 5.1 release, including numerous issues claiming to have added client_credentials but I just cannot seem to get it to work. I know I am just overlooking something right in front of me, can someone show me how to get this working? If you respond here I will update the SO, or you're welcome to yourself for future people.

**Comment by rwinch** [comment]
Thanks for the question. I actually appreciate that you tried StackOverflow before you asked here since there are more people on StackOverflow that can help. So thank you for that.

Spring Security's Client Credentials support does not yet perform a refresh. See https://github.com/spring-projects/spring-security/issues/5893

Would you be interested in submitting a PR for this? If so, can you comment on the linked issue. Also I'd be happy go guide you.

**Comment by rwinch** [comment]
I'm closing this since it is a duplicate of https://github.com/spring-projects/spring-security/issues/5893
