### ISSUE TITLE
Support For RequestedMeTokenResolver and RememberMeRequestedResolver

### ISSUE THREAD

**Issue by ankurpathak** [spring-projects/spring-security#5978]
Rember me authentication can be made more user friendly by using a strategey to write and read rmber me token instead of hard coded methods:
   1.  protected void setCookie(String[] tokens, int maxAge, HttpServletRequest request, HttpServletResponse response) 
  2.   protected String extractRememberMeCookie(HttpServletRequest request) 
It will be very similar to HttpSessionIdResolver and we can have RemberMeTokenResolver which
based on some strategy either read and write the token as header or cookie. This will make it
rest friendly.
Similar is the case with RemberMeRequestedResolver which instead of reading it from body will 
read it based on the strategy.

**Comment by rwinch** [comment]
Thanks for the feedback. Going forward we generally recommend using Spring Session remember me support. For users that still need the old support overriding the methods should suffice as we don't want to introduce too many public APIs (especially on ones that we are moving away from).

**Comment by ankurpathak** [comment]
Can I provide a pull request for it. As I have alreday done this for my project.

**Comment by rwinch** [comment]
I'm not sure what you are wanting to provide a PR for. I do not want a new API for a strategy to write/read remember me tokens as it increases the number of APIs in security which means more complexity to understand for users and for us to maintain. This decision is emphasized by the fact that we don't typically recommend old style remember me support since Spring Session offloads sessions already.
