### ISSUE TITLE
redirectUrl dont work

### ISSUE THREAD

**Issue by bentenzheng** [spring-projects/spring-security#6021]
authorizedGrantTypes use authorization_code pattern，and save session in redis, when user login success，redirectUrl dont work. (redirectUrl get from user)
Can you help me with my doubts?
http://localhost:8080/oauth/authorize?
the paramters:
client_id=apaas&response_type=code&redirect_uri=http://139.199.65.149:8081/

**Comment by jgrandja** [comment]
@bentenzheng Have you looked at these samples:
- [OAuth 2.0 WebClient](https://github.com/spring-projects/spring-security/tree/master/samples/boot/oauth2webclient) (uses `authorization_code`)
- [OAuth 2.0 Login](https://github.com/spring-projects/spring-security/tree/master/samples/boot/oauth2login) (uses `authorization_code`)

My guess is that you haven't setup the correct `redirect_uri` with either the client at the Provider or the `ClientRegistration`.

The instructions in both of those samples guide you through setting up the client and `redirect_uri`.

I'm going to close this issue but we can re-open if you're still having issues after going over those samples and replicating the configuration in your app.

For future reference, a minimal sample that re-produces the issues would be very helpful in troubleshooting. Otherwise, it's pretty difficult with minimal details provided.
