### ISSUE TITLE
Principle Object is null is controller After successfully login.

### ISSUE THREAD

**Issue by abhishekhbd** [spring-projects/spring-security#6044]
I am using spring boot 1.5X.

In my application I am using third party authorization provider (Authorization-Code flow) using JWT(like facebook). I am not using any userinfouri to get user details. I am getting everything from JWT.

After creating OAuth2Authentication Object property I am not able to get any secure pages.

Even I am unable to get Principles.

SecurityContextHolder.getContext().getAuthentication() returning annonemous user.

**Comment by jgrandja** [comment]
@abhishekhbd This issue should be logged with [Spring Security OAuth](https://github.com/spring-projects/spring-security-oauth/issues).

Also, please provide more details as it wasn't totally clear to me what issue you are having. A minimal sample the reproduces the issue would be very helpful.

**Comment by jzheaux** [comment]
Also, I'll just add for @abhishekhbd's benefit that support questions are typically better suited for Stack Overflow. If you have posted a question there already and didn't get what you needed, then post to the project @jgrandja mentioned, with a link to the SO question.

The reason for this is so that folks who have the same problem as you can discover the answer more readily in the future.
