### ISSUE TITLE
Reactive OAuthResourceServerSpec should allow custom error handling

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6052]
Servlet-based Spring Security allows for custom error handling via the DSL:

```java
http
    .oauth2ResourceServer()
        .accessDeniedHandler(...)
        .authenticationEntryPoint(...)
        ....
```

It would be nice if Spring Security WebFlux Resource Server could do the same.

**Comment by sepanniemi** [comment]
Should it be possible to customize the error handling via ExceptionHandlingSpec in ServerHttpSecurity? 

It seems that currently defining access denied handler like this has an effect

```
serverHttpSecurity
            .exceptionHandling()
                .accessDeniedHandler(accessDeniedHandler)
```

but defining authentication entry point in a similar way does not have an effect.
``` 
serverHttpSecurity
            .exceptionHandling()
                .authenticationEntryPoint(authEntryPoint)
```

and that's because AuthWebFilter is getting a hardcoded authentication entry point in the configuration?

https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java#L988
