### ISSUE TITLE
Update webflux-form sample to use Thymeleaf Built in CSRF Support

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#6061]
### Summary

Thymeleaf provides [automatic integration with Spring Security's CSRF](https://github.com/spring-projects/spring-security/issues/5867#issuecomment-423327852) support. We should update the [webflux-form](https://github.com/spring-projects/spring-security/tree/5.1.1.RELEASE/samples/boot/webflux-form) sample to demonstrate it.

* Update the dependencies to include both org.springframework.boot:spring-boot-starter-thymeleaf org.thymeleaf.extras:thymeleaf-extras-springsecurity5
* Remove the [CsrfControllerAdvice](https://github.com/spring-projects/spring-security/blob/5.1.1.RELEASE/samples/boot/webflux-form/src/main/java/sample/CsrfControllerAdvice.java)
* Ensure the tests still pass by running `../../../gradlew check`

**Comment by Daniel69** [comment]
I'd like to take this one 😁

**Comment by rwinch** [comment]
Thanks @Daniel69 The issue is all yours! If you need any help, please don't hesitate to reach out to me

**Comment by Daniel69** [comment]
Thank @rwinch, I'll start by reading https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md

**Comment by Daniel69** [comment]
@rwinch I removed the CsrfControllerAdvice and added a dependency to org.thymeleaf.extras:thymeleaf-extras-springsecurity5:3.0.4.RELEASE because  'org.thymeleaf.extras:thymeleaf-extras-springsecurity' alone does not resolve, but two tests fail once I remove the Controller Advice (loginWhenInvalidUsernameThenError and loginAndLogout).
When I run the example alone after these changes and attempt to login, the only message that I can see is : 'CSRF Token has been associated to this client',  no matter I use 'user' or 'invalid' as username.

**Comment by rwinch** [comment]
@Daniel69 Sorry for the delay getting back to you. The problem is that we aren't using Spring Boot 2.1.0.RELEASE yet. I created #6082 which will resolve this. Once it is updated to Boot 2.1.0.RELEASE you should be able to remove the version from `org.thymeleaf.extras:thymeleaf-extras-springsecurity5` too

**Comment by rwinch** [comment]
Thanks again for your patience. Now that #6082 has been resolved, you should be able to rebase off of master and remove the version from thymeleaf-extras-springsecurity5
