### ISSUE TITLE
Passing a expired token causes BOTH unsecured and secured endpoints to throw a 401 Unauthorized

### ISSUE THREAD

**Issue by cmreigrut** [spring-projects/spring-security#6067]
### Summary

Passing a expired token causes BOTH unsecured and secured endpoints to throw a 401 Unauthorized

### Actual Behavior

Create two endpoints secured by oauth, one secured and one unsecured.
With no token:
  Going to /secured throws a 401 Unauthorized (correct)
  Going to /unsecured returns the endpoint contents (correct)
With a valid token:
  Going to /secured returns the endpoint contents (correct)
  Going to /unsecured returns the endpoint contents (correct)
Allow the token to expire.  Using an invalid token:
  Going to /secured returns a 401 Unauthorized (correct)
  Going to /unsecured returns a 401 Unauthorized (incorrect)

### Expected Behavior

For unsecured endpoints, it should not matter whether or not I am providing a valid token, and invalid token, or no token at all

### Configuration

    // Security
    compile('org.springframework.boot:spring-boot-starter-security')
    compile('org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure')
    compile('org.springframework.security:spring-security-jwt')

### Version

2.0.3.RELEASE

### Sample

If needed I can try to create a non-proprietary example

**Comment by jzheaux** [comment]
@cmreigrut thanks for the report!

This is expected behavior. It's consistent with how HTTP Basic authentication works in Spring Security:

With no authentication:
Going to /secured throws a 401 Unauthorized
Going to /unsecured returns the endpoint contents
With valid authentication:
Going to /secured returns the endpoint contents
Going to /unsecured returns the endpoint contents
With invalid authentication:
Going to /secured returns a 401 Unauthorized
Going to /unsecured returns a 401 Unauthorized

Do you see any inconsistency with how Bearer token auth works compared to Basic auth? Primarily, we want these to behave the same.
