### ISSUE TITLE
Introduce ReactiveJwtAuthenticationConverter

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6273]
Users often need to consult external resources in a non-blocking way to collect granted authorities in Resource Server.

This is currently possible by implementing a `Converter<Jwt, ? extends Mono<? extends AbstractAuthenticationToken>>`.

On the Servlet stack, this task can be accomplished more easily by extending `JwtAuthenticationConverter`:

```java
public class MyAuthenticationConverter
        extends JwtAuthenticationConverter {

    @Override
    public Collection<GrantedAuthority> extractAuthorities(Jwt jwt) {
        // ... extract
    }
}
```

It would be nice to have the same simplicity on the reactive side:

```java
public class MyReactiveAuthenticationConverter 
        extends ReactiveJwtAuthenticationConverter {

    @Override
    public Flux<GrantedAuthority> extractAuthorities(Jwt jwt) {
        // ... extract in a non-blocking way
    }
}
```

**Comment by jzheaux** [comment]
Have I told you have lucky we are to have great contributors like you, @edeandrea? 

Yes, a PR would be much appreciated, thank you.

I'm actually thinking that `ReactiveJwtAuthenticationConverter` would be abstract, and not have a default implementation for `extractAuthorities`. 

The reason for this is that the user already gets the default scope-extraction logic by using `JwtAuthenticationConverter`, which they are already getting by default. The reason they'd use `ReactiveJwtAuthenticationConverter` is that they want to change that behavior.

**Comment by edeandrea** [comment]
That would be fine if I wanted to completely alter the authorities, but what if I want to merge the default behavior with my own set of authorities (which is actually my use case for bringing this up in the first place). Then I'd have to re-write that default logic myself rather than just calling super.

My thought would be to refactor JwtAuthenticationConverter and remove the logic that creates the authorities into it's own Converter<Jwt, Collection<Granted authority>> and have JwtAuthenticationConverter use that. Then Reactive JwtAuthenticationConverter can use it too by wrapping in a Flux.fromIterable.

I can code it out so you can see.

**Comment by edeandrea** [comment]
I opened #6277 for this. We can take the discussion over there if any re-factoring is needed.
