### ISSUE TITLE
BearerTokenAccessDeniedHandler should return missing scope

### ISSUE THREAD

**Issue by ohr** [spring-projects/spring-security#6280]
### Summary

In case of insufficient scopes with OAuth2 authorization, the 403 response does not contain the missing scope(s) although https://tools.ietf.org/html/rfc6750#section-3.1 would allow so. For evaluating authorization problems on the client-side, this would be very valuable.

### Actual Behavior

Currently, the contained scopes are returned in the WWWAuthenticate header (it is btw. not mentioned in the RFC that these scopes shall be returned at all)

### Expected Behavior

The missing scope(s) should be returned in the WWWAuthenticate header

### Configuration

Although the OAuth2 AccessDeniedHandler is configurable, the information about the missing scope can apparently not be transported in the AccessDeniedException.

### Version

5.1.2

**Comment by jzheaux** [comment]
@ohr, you are correct that the scope information is not part of the exception. In fact, an `AccessDeniedException` has only a `String` message.

The behavior you are describing is actually by design. It's not great security to inform an attacker what scopes they are missing in order to get access to a resource, and for this reason, Spring Security leaves them out.

That said, this, too, is customizable. You can, for example, create your own exception and change your authorization expressions to use a bean that throws this custom exception. This approach is demonstrated in [the following commit](https://github.com/jzheaux/messaging-app/commit/385fc2d6276978868c64b9732a8ef73c864838d0).
