### ISSUE TITLE
[Suggestion] Make oauth2-resource-server independant of spring.security.web

### ISSUE THREAD

**Issue by GregorEeckels** [spring-projects/spring-security#6381]
### Summary
In [spring-security-oauth2-resource-server.gradle](https://github.com/spring-projects/spring-security/blob/master/oauth2/oauth2-resource-server/spring-security-oauth2-resource-server.gradle) should contain Spring Security Web only as an optional dependency, as it is possible to use classes from [here](https://github.com/spring-projects/spring-security/tree/master/oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource) without requiring spring security web.

### Actual Behavior

Not a bug report.

### Expected Behavior

Not a bug report.

### Configuration

Not required.

### Version

Not required.

### Sample

Not required.

**Comment by ST-DDT** [comment]
The same issue applies to other parts of spring-security as well.
(Lately) there is a rich influx of new technologies that mirror similar behavior as web does (having headers along with the actual data). Examples for such technologies are gRPC and many message brokers such as kafka. These are totally independent of web, but would still benefit from the features offered by spring-security such as BasicAuth, Certificate Authentication, OAuth2...
However due to the strict usage of the servlet API it is impossible to reuse most of the code; the issue becomes even more difficult to overcome due to auth extraction, auth validation and response generation happening in the same class (everything except for the actual authentication).

**Comment by rwinch** [comment]
@ST-DDT Thanks for the comment. Can you please create a new issue to discuss more specifics on your concerns?

**Comment by jzheaux** [comment]
I like where this idea is headed, @GregorEeckels, but I think that the 95% use case is that users want the `web` dependency, so it makes the most sense to include it for them and ask the 5% to exclude it (instead of the inverse).

Down the road, maybe we could look at creating a new non-web oauth2 module that `spring-security-oauth2-resource-server` depends on; as concrete use cases for other protocols materialize, it will be clearer how to formulate the appropriate abstractions.
