### ISSUE TITLE
Change header name to extract authorization token

### ISSUE THREAD

**Issue by micd** [spring-projects/spring-security#6420]
### Summary

Hi! I want to configure Web flux security to use different header name to retrieve token from http request. By default "Authorization" is used. I would like to define my own name. Is it possible to provide such configuration? I know for older version of Spring security I could write my own token extractor. Is there anything like for Spring Security 5+? 

I would be grateful for your help. God bless you!

**Comment by jzheaux** [comment]
Hi, @micd, please have a look at [`ServerAuthenticationConverter`](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/server/authentication/ServerAuthenticationConverter.java). It takes a `ServerWebExchange` and returns an `Authentication`, which could be used to extract a header like so:

```java
exchange -> {
    String header = exchange.getRequest().getHeaders().getFirst("X-My-Custom-Header");
    // ... etc.
    return Mono.just(new BearerTokenAuthenticationToken(token));
}
```

Also, thank you for the question! In the future, would you please post questions to StackOverflow. Each member of the team dedicates time to answering questions there since that is a more mature Q&A platform.

**Comment by micd** [comment]
@jzheaux , thank you, I appreciate that! 

Sure, I will try to move there (hopefully I will remember about that).

God bless you!
