### ISSUE TITLE
enableAuthorities=false in JdbcDaoImpl should not throw UsernameNotFoundException

### ISSUE THREAD

**Issue by clevertension** [spring-projects/spring-security#6567]
### Summary
when user set `enableAuthorities=false` manually in `org.springframework.security.core.userdetails.jdbc.JdbcDaoImp`, it should also load UserDetails with method `UserDetails loadUserByUsername(String username)`

### Actual Behavior
it will always throw `UsernameNotFoundException`

### Expected Behavior
it should also load UserDetails with method `UserDetails loadUserByUsername(String username)`

### Version
5.2.0.BUILD-SNAPSHOT

**Comment by clevertension** [comment]
![image](https://user-images.githubusercontent.com/346723/53491454-6e066700-3ad1-11e9-966e-9e52edfb69b5.png)

it should be

```java
if (this.enableAuthorities && dbAuths.size() == 0) {
...
}
```

**Comment by eleftherias** [comment]
If you are setting `enableAuthorities` to `false`, then it is expected that you will be using group based authorities.

From the `JdbcDaoImpl` [Javadoc](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/core/userdetails/jdbc/JdbcDaoImpl.html):
> Support for group-based authorities can be enabled by setting the enableGroups property to true (you may also then wish to set enableAuthorities to false to disable loading of authorities directly). With this approach, authorities are allocated to groups and a user's authorities are determined based on the groups they are a member of. The net result is the same (a UserDetails containing a set of GrantedAuthoritys is loaded), but the different persistence strategy may be more suitable for the administration of some applications.

In either case it is expected that the user's authorities are not empty, which is why a `UsernameNotFoundException` is thrown, since a user with no authorities are treated as not found.

I'm going to close this issue because this is intended behavior, but feel free to comment below if it's unclear.
