### ISSUE TITLE
What's method that I should read the spring-security documentation right? 

### ISSUE THREAD

**Issue by zero9005** [spring-projects/spring-security#6596]
When I read the section about oauth2 in the spring security documetation, I find that i can not understand it.

**Comment by jzheaux** [comment]
Hey, @zero9005, sorry you are having trouble. Do you have a specific question I can help you with? 

Or, there is typically a Spring Security member hanging out on Gitter, if you feel like you don't know what questions to ask: http://gitter.im/spring-projects/spring-security

**Comment by jzheaux** [comment]
Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
