### ISSUE TITLE
remove final from convert method in JwtAuthenticationConverter

### ISSUE THREAD

**Issue by ajmalch** [spring-projects/spring-security#6744]
### Summary

I wanted to extend JwtAuthenticationConverter in the resource server and override convert method to return my own implementation of  AbstractAuthenticationToken from the Jwt.

### Actual Behavior

Currently the method in JwtAuthenticationConverter is final as  below 
```
public final AbstractAuthenticationToken convert(Jwt jwt) {
		Collection<GrantedAuthority> authorities = extractAuthorities(jwt);
		return new JwtAuthenticationToken(jwt, authorities);
	}
```

### Expected Behavior

I am thinking that final could be removed so that I can override convert method as below in MyJwtAuthenticationConverter which extends JwtAuthenticationConverter .

```
public AbstractAuthenticationToken convert(Jwt jwt) {
		Collection<GrantedAuthority> authorities = extractAuthorities(jwt);
		return new MyJwtAuthenticationToken(jwt, authorities);
	}
```

I am planning to extend JwtAuthenticationToken for MyJwtAuthenticationToken

@jzheaux , was there a reason you made the method public? If yes and that should be final, I will implement  MyJwtAuthenticationConverter without extending JwtAuthenticationConverter, but very similar to it. Please let me know your comments.

**Comment by jzheaux** [comment]
Good question, @ajmalch, thanks for reaching out. I think you have the right idea in implementing the `Converter` interface yourself.

The reason is that it's good to favor composition over inheritance. The existing construct encourages that approach.

Note also that this converter does very little, largely delegating to a granted authorities converter, which means that making that method extensible really wouldn't accomplish anything.
