### ISSUE TITLE
Jwt converters small improvements

### ISSUE THREAD

**Issue by ch4mpy** [spring-projects/spring-security#6797]
Proposed `JwtAuthenticationConverter` modifications:
  * have granted-authorities converter injected from constructor
  * mark default constructor deprecated so that users get notified they really should consider providing their own granted-authorities converter (or intentionally use default one)

Proposed `JwtGrantedAuthoritiesConverter` modifications (which currently is both a granted-authority and a scope converter.):
  * extract a `TokenAttributesScopesConverter` and use it as collaborator
  * add a constructor to inject scopes converter
  * modify default constructor so that it uses a `TokenAttributesScopesConverter` extracting scopes from "scope" and "scp" claims and adding "SCOPE_" prefix (keep current behavior)
  * deprecate default constructor

Proposed `TokenAttributesScopesConverter` behavior modification: scan both "scope" and "scp" if both are present (strange to assume "scope" is better than "scp" if both are present).

**Comment by jzheaux** [comment]
Thanks for the improvement proposals, @ch4mpy.

> have granted-authorities converter injected... mark default constructor deprecated

I don't see this as beneficial since the defaults are reasonable. Intentionally specifying every dependency is certainly one way to approach configuration, but I don't see a reason to push developers down that path (they can still certainly do that if they wish by intentionally calling the setter). Generally speaking, if a class needs the application to specify something, then that goes in a constructor.

> extract a `TokenAttributesScopeConverter`

This is certainly a tricky spot since various implementations treat this as an array or space-delimited string in addition to what are you calling out about different attribute names. And it's further complicated by the fact that the JWT spec doesn't include details about any authority claims.

It's not yet clear how to best treat scopes, and so I'd prefer to continue to hide this implementation detail (that is, the implementation detail that granted authorities are derived from OAuth 2.0 scopes).

Currently, an application can configure a `MappedJwtClaimSetConverter` to coerce attribute values, and that may be a more reasonable place for the application to do this work, like in complex cases where  JWTs are coming from many issuers using disparate representations:

```java
MappedJwtClaimSetConverter claimSetConverter = MappedJwtClaimSetConverter
        .withDefaults(singletonMap("scp", new MyScopeConverter()));
jwtDecoder.setClaimSetConverter(claimSetConverter);
```

As it is, though, it's pretty simple for the application to customize the granted-authorities converter:

```java
jwtAuthenticationConverter.setGrantedAuthoritiesConverter(jwt -> {
        List<String> scopes = (List<String>) jwt.getClaim("authorities");
        return scopes.stream().map(SimpleGrantedAuthority::new).collect(toList());
});
```

The nice thing about both of these is that the public API for JWT support remains agnostic of scopes.

I don't see most users needing to copy-paste the `getScopes()` method since the sole reason for its complexity is the lack of a clear spec. The typical application won't need all of that complexity -- they'll know what their claim is named and what format it's in, and go from there.

> scan both "scope" and "scp"

The point isn't to support the "both" use case, as that seems pretty uncommon, it's simply to look for which one exists. This seems to be well within 95% of applications. If an application accepts requests that contain both "scope" and "scp" in the same JWT, then they can customize.

**Comment by ch4mpy** [comment]
@jzheaux thanks for your detailed explanations. I might have additional questions, thought.

I had started to prepare a PR to illustrate my point, but it stilled required some polish when I last connected. I submit it now, but just for illustration purpose as I understand this not the kind of change you'd like to introduce in a second milestone.

> It's not yet clear how to best treat scopes, and so I'd prefer to continue to hide this implementation detail

My understanding of current Spring stack, even before getting into implementation details, was that "scope" and "scp" claims are the only place you can define authorities (unless re-implementing a few components, as usual).
Additionally, if there is no clear spec for JWT, opaque token seam better defined on that point. As current "hiden" Spring implementation for Jwt better implements Opaque spec than Introspection one (`OAuth2IntrospectionAuthenticationProvider` expects "scope" claim to be a collection when RFC specifies a single space separated String), extracting a `TokenClaimsScopeConverter` (which could be re-used for opaque tokens) seemed not a so bad idea.
Quote from https://tools.ietf.org/html/rfc6749#page-23:
> scope parameter is expressed as a list of space-delimited, case-sensitive strings

> I don't see this as beneficial since the defaults are reasonable

Searching for authorities in common scope claims seems the best default. But is the systematic "SCOPE_" prefix added when translating to authorities the only way to go?
Wouldn't it be better if that was configurable ?
For instance, if migrating an app (with existing security expressions based on roles and authorities) to Oauth2, I guess I'd be happy to get authorities without any prefix, so that things keep working.

> Generally speaking, if a class needs the application to specify something, then that goes in a constructor

I use an other rule of thumb, but maybe just a code style matter: if property doesn't need to be mutated at runtime, it should be final and set from from constructor, otherwise, setters must be exposed.

I've taken your comment about defaults in the PR I join to this (already closed) issue and removed the deprecations.
