### ISSUE TITLE
Default login page's css "https://getbootstrap.com/docs/4.0/examples/signin/signin.css" is too slow in china.

### ISSUE THREAD

**Issue by andyzhaozhao** [spring-projects/spring-security#6824]
"https://getbootstrap.com/docs/4.0/examples/signin/signin.css " always cost about 15 seconds in chinese network.

**Comment by jzheaux** [comment]
@andyzhaozhao Sorry to hear that's slow for you. While this page is not intended for production use, we do want developers to have a pleasant experience with it.

> always cost about 15 seconds

Just double-checking - I'm supposing that the response gets cached? I'd imagine that after the first request, its snappy for a certain period of time after. Also, does this affect your ability to use the page at all?

You might consider taking this up with the bootstrap folks to see if there is anything that can be done about the latency.

Otherwise, do you have any recommendations on how you'd like the Spring Security code to change? Ideally, we wouldn't inline the CSS.

**Comment by jzheaux** [comment]
@andyzhaozhao, fyi, we're waiting for some feedback on you in order to move forward on this ticket. If we haven't heard from you by next week, then we'll close the ticket.

**Comment by taijitdf** [comment]
OK.thank you very much!

**Comment by Kevin-Buntrock** [comment]
Hello,

Just found this closed issue which correspond to a problem I have on my project.

This default page is pretty nice because it adapts itself depending on configuration. I want in production to be connected to an SAML provider. But for some testing use cases, I have a username/password form configuration.

I would like to keep the benefice of an already coded default page just for my non production use cases.
On a closed network, accessing theses resources is just not possible.

Could we consider putting the two urls as default in two configuration variables? For the ones who want to self host the files?

**Comment by jzheaux** [comment]
Hi, @Kevin-Buntrock! I'm glad you are liking the default login page. 

However, it's not intended for production use, so I'm not inclined to add features to it targeted at simplifying use in production.
During development, I imagine that having CSS is not critical since the page is just a placeholder for an application's production login page.

If it sounds like I've misunderstood what you are saying or you feel you'd like to pursue further discussion, please open a separate ticket to make your proposal easier for folks to find.
