### ISSUE TITLE
Add constructor to JwtAuthenticationToken that takes a principal name

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6865]
`OAuth2IntrospectionAuthenticationToken` takes a name as a constructor parameter and otherwise defaults to the token's SUB claim for the principal name.

`JwtAuthenticationToken`, on the other hand, provides no way to customize this.

It'd be nice to do the same for `JwtAuthenticationToken`:

```java
public JwtAuthenticationToken(Jwt jwt, Collection<? extends GrantedAuthority> authorities, String name) {
    // ...
```

This encourages composition over inheritance while also keeping the application from having to create a custom class to override this default behavior.

**Comment by HaydenMeloche** [comment]
I'd like to submit a PR for this issue. Taking a look at `JwtAuthenticationToken` it doesn't currently have a `name` value like `JwtAuthenticationToken` does. I also noticed that currently `getName` returns the tokens subject. Should I be creating a new name variable or setting something somewhere else?

Sorry if silly question, first time around here :)

**Comment by rhamedy** [comment]
@HaydenMeloche if I understand correctly, you will be mimicking the `OAuth2IntrospectionAuthenticationToken` by adding `name` and introducing the suggested `constructor`. 

As far the `getName` question, if you look at  `OAuth2IntrospectionAuthenticationToken` constructor the line `this.name = name == null ? (String) attributes.get(SUBJECT) : name;` does the trick of either setting the provided name (if not null) or defaulting to `attributes.get(SUBJECT)` so when the `getName()` returns `this.name` it is either of the two hence, functioning the same way as `OAuth2IntrospectionAuthenticationToken`. 

You might be able to provide a PR for this since it is tagged with `first-timers-only` and no one has claimed it yet 👍

I am not part of `Spring team` but, I felt like I could answer your questions and I hope I did not confused you 🙂

**Comment by jzheaux** [comment]
@HaydenMeloche welcome! Yes, @rhamedy's analysis is correct, and yes, it'd be great to see a PR from you.

**Comment by HaydenMeloche** [comment]
I believe this issue can be closed now.
https://github.com/spring-projects/spring-security/pull/6893

**Comment by jzheaux** [comment]
Closed via https://github.com/spring-projects/spring-security/commit/f84ab3a2558d5258d99e169725c87c9ee37cd020
