### ISSUE TITLE
Consider reverting "Add custom parameters to token introspection requests"

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#6882]
### Summary

If a request needs modified it can be done by injecting a `RestTemplate` that has a `ClientHttpRequestInterceptor` that modifies the request before passing it to the `ClientHttpRequestExecution`.

**Comment by jgrandja** [comment]
@rwinch Yes, `ClientHttpRequestInterceptor` is another option but why can't we have a `RequestEntity` `Converter` as another option? Both these configuration options are currently available in:

```
DefaultAuthorizationCodeTokenResponseClient.setRequestEntityConverter()
DefaultAuthorizationCodeTokenResponseClient.setRestOperations()

DefaultClientCredentialsTokenResponseClient.setRequestEntityConverter()
DefaultClientCredentialsTokenResponseClient.setRestOperations()

DefaultOAuth2UserService.setRequestEntityConverter()
DefaultOAuth2UserService.setRestOperations()
```

I think consistency makes sense here.

**Comment by jzheaux** [comment]
I see @rwinch's point here that the application could simply add parameters in an interceptor, but the API seems rather cumbersome since the body is a serialized byte array:

```java
(request, body, execution) -> {
    // 0. body is something like `"token=mF_9.B5f-4.1JqM&token_type_hint=access_token".getBytes()`
    // 1. deserialize body
    // 2. add a new parameter
    // 3. reserialize body
    return execution.execute(request, withParameters);
}
```

Whereas with a converter, we get:

```java
token -> {
    // 1. Specify a `Map` as the body
    // 2. Specify an `HttpHeaders` as the headers
    return new RequestEntity<>(body, headers, HttpMethod.POST, uri);
}
```

It's not clear to me how the former is more effective than the latter since, with the former, I have to add the extra (de)serialization boilerplate.

I think an interceptor makes good sense for adding headers and maybe even for modifying the URI. Modifying the body, though, seems cumbersome. Am I missing something, @rwinch, or am I off-base in thinking that modifying the body like this is smelly?

I don't mind leaving the method out, for the sake of having less to support, though I'd imagine adding support eventually anyway, in the form of an interceptor that hides the byte-array boilerplate so the application can more easily modify or switch out the body.

**Comment by rwinch** [comment]
Thanks @jzheaux Closing as I agree with your analysis
