### ISSUE TITLE
Salt of specific length throws StringIndexOutOfBoundsException in BcryptPasswordEncoder

### ISSUE THREAD

**Issue by Daimanta** [spring-projects/spring-security#6907]
### Summary

When executing the function `public static String hashpw(byte passwordb[], String salt)` in BCrypt.java and entering a salt of exactly length 28, the line `real_salt = salt.substring(off + 3, off + 25);` throws an StringIndexOutOfBoundsException in some cases. This only occurs when the salt is length 2 as a salt of lesser length gets rejected while salts of greater length do not get the exception.

### Actual Behavior
1. Call the function hashPw with any password and a valid salt of length 28, e.g. "$2a$10$012345678901234567890"
2. Notice the StringIndexOutOfBoundsException 

### Expected Behavior
The StringIndexOutOfBoundsException should not be thrown. Most likely, salts of length 28 should not be allowed as the code basically fails on a one-off value.

### Configuration
No configuration required, plain old java function call.

### Version
5.1.5.RELEASE

**Comment by jzheaux** [comment]
Thanks for the report, @Daimanta.

Actually, isn't a salt length of 28 is valid in some cases?

`$2$10$` + 22 characters = 28 characters

I think the problem is that the check doesn't take into account when the salt version is `2` vs when it's `2a`, `2b`, or `2y`.

I'd probably add something after the offset has been determined like:

```java
if (off + 25 > saltLength) {
    throw new IllegalArgumentException("Invalid Salt");
}
```
Would you be interested in submitting a PR for this change, including a unit test?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Daimanta** [comment]
You are correct that there are cases that 28 characters is fine. An extra check for length >=29 when the version is 2a,2b or 2y would be appropriate. I will make a PR for it.
