### ISSUE TITLE
BearerTokenAuthenticationFilter should expose an AuthenticationFailureHandler

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#7009]
`BearerTokenAuthenticationFilter` uses an `AuthenticationEntryPoint` when authentication fails. However, an `AuthenticationFailureHandler` is a better fit.

From the JavaDoc for `AuthenticationEntryPoint`:

> Used by {@link ExceptionTranslationFilter} to commence an authentication scheme.

And from `AuthenticationFailureHandler`:

> Strategy used to handle a failed authentication attempt.

It seems reasonable that `BearerTokenAuthenticationFilter` could use a failure handler that, by default, invokes an entry point.

This would give the filter the flexibility to, for example, return a 500 error in the event of an `InternalAuthenticationServiceException`.

**Comment by ThomasVitale** [comment]
Hi @jzheaux, I would be interested in working on this issue

**Comment by jzheaux** [comment]
It's yours, @ThomasVitale!

**Comment by ThomasVitale** [comment]
Thanks @jzheaux!

Before starting, I'd like to check the solution with you:
- `BearerTokenAuthenticationFilter` should expose an `AuthenticationFailureHandler` instead of an `AuthenticationEntryPoint`
- On authentication failure, `BearerTokenAuthenticationFilter` should call the `AuthenticationFailureHandler`
Correct?

Then, `OAuth2ResourceServerConfigurer` is currently calling `BearerTokenAuthenticationFilter` and setting a `BearerTokenAuthenticationEntryPoint` on it. Should I make `OAuth2ResourceServerConfigurer` use a new `BearerTokenAuthenticationFailureHandler` (which internally calls a `BearerTokenAuthenticationEntryPoint`) and set this one on the filter instead of the entry point?

**Comment by jzheaux** [comment]
Thanks for checking in, @ThomasVitale.

> BearerTokenAuthenticationFilter should expose an AuthenticationFailureHandler instead of an AuthenticationEntryPoint

Not instead of since `AuthenticationEntryPoint` still has its place. For example, if no token is provided at all, we should call the entry point. It's only when an attempted authentication fails that we'd use the failure handler.

> On authentication failure, BearerTokenAuthenticationFilter should call the AuthenticationFailureHandler. Correct?

Yes

> Should I make OAuth2ResourceServerConfigurer use a new BearerTokenAuthenticationFailureHandler (which internally calls a BearerTokenAuthenticationEntryPoint) and set this one on the filter instead of the entry point?

I like to try and leave callers of the API as is since it proves to me that it's truly backward compatible. Since there's no need for the configurer to specify a failure handler, I'd just leave it calling `setAuthenticationEntryPoint` as it already does.

We should definitely add tests, though, to ensure that the failure handler works.

**Comment by ThomasVitale** [comment]
Thanks for the details @jzheaux.

I started drafting a solution, but I'm still in doubt about how the `AuthenticationFailureHandler` should look like.

In the draft, I have used `AuthenticationFailureHandler` instead of `AuthenticationEntryPoint` on failed authentication and updated the test related to this specific scenario.

In the description, it's mentioned that the failure handler should call `AuthenticationEntryPoint` by default. And I guess, when available, we need to pass the entry point defined for the filter by the caller, right? So that the filter is backward compatible (in the draft it is not).

Also, apart from calling the entry point, what should the failure handler do?

The draft is here, I haven't made a formal PR yet since it's incomplete.
https://github.com/ThomasVitale/spring-security/commit/e5a5d3fb7e5621ab7d60dc781c296c4b55b70307

**Comment by jzheaux** [comment]
I've left a comment in your commit log. Other than that, you appear to be on the right track.

> apart from calling the entry point, what should the failure handler do?

At this point, just calling the entry point suffices. The intent here is to give the application a chance to customize failure handling differently from when a request is simply missing the bearer token.

**Comment by ThomasVitale** [comment]
Thanks @jzheaux, I completed the code after your suggestion and opened a PR.
