### ISSUE TITLE
@AuthenticationPrincipal  return empty after add custom intercepter

### ISSUE THREAD

**Issue by mmdsyl** [spring-projects/spring-security#7015]
spring boot & security version:
2.0.9.RELEASE

I added a custom interceptor for  logging, and I found @AuthenticationPrincipal  return empty.

With my limited experience with spring security, I don't know why.  Thanks in advance.

```
 @GetMapping("/info")
    public Result user(@AuthenticationPrincipal User user) {
        return Result.success(user);
    }


@Component
public class LogInterceptor implements HandlerInterceptor {


    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler)
            throws Exception {
//print some log 
}



@Configuration
public class MyWebAppConfigurer
        extends WebMvcConfigurationSupport {

    @Autowired
    LogInterceptor logInterceptor;



    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(logInterceptor).addPathPatterns("/**")
}
```

**Comment by rwinch** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
