### ISSUE TITLE
Reactive ServerAuthenticationEntryPoint not working if not subscribe

### ISSUE THREAD

**Issue by jittagornp** [spring-projects/spring-security#7164]
I try implement `ServerAuthenticationEntryPoint` for custom json response

But this not working
```java
    @Bean
    public ServerAuthenticationEntryPoint serverAuthenticationEntryPoint(final GlobalWebExceptionHandler exceptionHandler) {
        return (ServerWebExchange exchange, AuthenticationException e) -> {
            return exceptionHandler.handle(exchange, e); 
        };
    }
```
and this working (when i manual subscribed)
```java
    @Bean
    public ServerAuthenticationEntryPoint serverAuthenticationEntryPoint(final GlobalWebExceptionHandler exceptionHandler) {
        return (ServerWebExchange exchange, AuthenticationException e) -> {
            exceptionHandler.handle(exchange, e).subscribe();
            return Mono.empty();
        };
    }
```

`exceptionHandler.handle()` return `Mono<Void>` 

This is source code of [GlobalWebExceptionHandler](https://github.com/pamarin-official/core-error/blob/master/src/main/java/com/pamarin/core/error/handler/GlobalWebExceptionHandler.java)

**Comment by rwinch** [comment]
In this case a Bean is not intended to get picked up automatically (because there is quite likely multiple of them). Try using:

```
http
   .exceptionHandling()
      .authenticationEntryPoint(yourCustomEntryPoint)
```

**Comment by rwinch** [comment]
I answered this, but if yo uare still having problems, this feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by jittagornp** [comment]
i know but i think this is `BUG`, Please see this video [https://www.youtube.com/watch?v=3spnurowdQk ](https://www.youtube.com/watch?v=3spnurowdQk )

**Comment by jittagornp** [comment]
I know but i think this is `BUG`, Please watch this video [https://www.youtube.com/watch?v=3spnurowdQk](https://www.youtube.com/watch?v=3spnurowdQk)

**Comment by rwinch** [comment]
Please provide a minimal sample that reproduces the issue. It should use the DSL and not rely on exposing the AuthenticationEntryPoint as a Bean. Then provide instructions on how to reproduce, what output you expect, and what actually occurs.
