### ISSUE TITLE
Dynamic redirect-uri-template

### ISSUE THREAD

**Issue by ahmadi86** [spring-projects/spring-security#7247]
I want to allow a client to link his account with my server with his account with another provider, let's say Google. To do so, I should be able to send the client's token with my server to Google and receive it back after the client is successfully logged in with Google. One way is to have the token (the one for my server) as part of the redirect-uri-template. This way when Google calls back the redirect uri, I would get the token back. First, is it the right solution? second, if yes, how can I dynamically set redirect-uri-template?  

For example, the default value for redirect-uri-template is {baseUrl}/login/oauth2/code/{registrationId}

What I want is sth like {baseUrl}/login/oauth2/code/{registrationId}/{token} and I want to set the {token} part dynamically?

**Comment by rwinch** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
