### ISSUE TITLE
Integrating Digest Auth into WebFlux.

### ISSUE THREAD

**Issue by wangqinghuan** [spring-projects/spring-security#7248]
I want to secure Spring gateway with Digest Auth. However, I didn't find any way to make it. Does Spring security support Digest Auth for Weflux? If not, has any improvement plan for this feature?

**Comment by rwinch** [comment]
There are lots of [disadvantages](https://en.wikipedia.org/wiki/Digest_access_authentication#Disadvantages) to digest authentication which is why it isn't recommended anymore. For example, you cannot safely store the password with a modern password one way adaptive function like BCrypt. Since digest authentication is not considered secure, we don't plan on adding support for it.

If you need this support, you can create a custom ServerAuthenticationEntryPoint and AuthenticationConverter.
