### ISSUE TITLE
WebClient solution to take care of CSRF/XSRF tokens

### ISSUE THREAD

**Issue by skrzyneckik** [spring-projects/spring-security#7286]
### Summary

Spring Security doesn't provide any out-of-the-box solution for WebClient to handle CSRF/XSRF tokens (received cookie named XSRF-TOKEN passed in next request as header X-XSRF-TOKEN). ExchangeFilterFunction could be used to store the cookie and include header, but I guidance about handling it correctly in a multithread environment would be beneficial.

**Comment by rwinch** [comment]
CSRF protection is for requests made within the browser so WebClient is not expected to need to provide a CSRF token.

If you have additional questions, it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by skrzyneckik** [comment]
> CSRF protection is for requests made within the browser so WebClient is not expected to need to provide a CSRF token.

@rwinch that's true, but it isn't bad practice to expose one API to be used by a web browser and other external clients (and they may use WebClient), so API enforces using it and WebClient can be used to communicate with any API. Personally, I don't think that scenario differ a lot from e.g. providing basic authentication, because it is something that API enforces WebClient to provide - there may be a similar situation with CSRF tokens. Another example can be supporting OAuth2 - WebClient is expected to support it because that's something that API requires - and spring-security-oauth2-client does exist.

**Comment by skrzyneckik** [comment]
For reference: solution posted on [StackOverflow](https://stackoverflow.com/a/57611121/2004186)
