### ISSUE TITLE
IpAddressMatcher fails to validate Mapped address

### ISSUE THREAD

**Issue by ask4gilles** [spring-projects/spring-security#7475]
### Summary

IpAddressMatcher fails to validate Mapped address ::FFFF:0:0/96 (see https://tools.ietf.org/html/rfc5156)

Introduced by https://github.com/clementkng/spring-security/commit/ea46adc3479e3542ab9b900fb3f52323f23c5541

### Actual Behavior

```
java.lang.IllegalArgumentException: IP address ::FFFF:0:0 is too short for bitmask of length 96
```

### Expected Behavior

No exception

### Version
5.2.0.RC1

### Sample
```
@Test
  public void validate(){
    new IpAddressMatcher("::FFFF:0:0/96").matches("whatever");
  }
```

**Comment by jzheaux** [comment]
@ask4gilles Thanks for the report.

First, just to clarify, the introduction of that check is not the crux of the issue. Even removing that check from the constructor, such will throw an exception:

```java
new IpAddressMatcher("::FFFF:0:0/96").matches("::FFFF:0:0")
```

And the reason is that Java (correctly) converts `::FFFF:0:0/96` addresses to instances of `IPv4Address`, meaning that there are only 32 bits to parse once it comes to invoking `matches`. A mask of 96, then, causes an `ArrayIndexOutOfBoundsException`.

Can you explain a bit more about what you are wanting to accomplish? Doesn't `::FFFF:0:0/96` basically mean "any IPv4 address should match"?

As a workaround, I believe you can get the functionality you want by specifying the equivalent IPv4 address:

```java
new IpAddressMatcher("0.0.0.0/0").matches("whatever")
```

An appropriate improvement might be to introduce a more type-safe constructor like:

```java
public IpAddressMatcher(InetAddress address, int nMaskBits)
```

**Comment by ask4gilles** [comment]
@jzheaux Thanks for taking the time to look at this.
We need this exact IP format in order to forbid its usage...
In 5.1.6.RELEASE, it's working as intended and it does not throw an ```ArrayIndexOutOfBoundsException```
![screenshot](https://user-images.githubusercontent.com/12292890/65683090-b6343a80-e05c-11e9-9adb-b5e38e1c394b.png)

**Comment by jzheaux** [comment]
In 5.1.6.RELEASE, the following with throw an exception:

```java
new IpAddressMatcher("::FFFF:0:0/96").matches("0:0:0:0:0:FFFF:0:0")
```

When it ideally would return `true`.

Further, it would be my expectation that:

```java
new IpAddressMatcher("::FFFF:0:0/96").matches("0:0:0:0:0:FFFF:c0a8:1")
```

would return `true`, but in 5.1.6.RELEASE it returns `false` because it's trying to apply 96 bits of similarity to an `IPv4Address`, which only has 32 bits.

I believe the problem is with the way that the address is parsed by Java into an `IPv4Address`. Because of that, the constructor can't appropriately interpret the mask.

**Comment by jzheaux** [comment]
> We need this exact IP format in order to forbid its usage

The `IpAddressMatcher` doesn't validate format, it validates values.

For example, if you wanted to say "You can't use IPv4 addresses in IPv6 format", you couldn't verify this with `IpAddressMatcher`, but you could verify it with a `Pattern`.

What you could do is the following:

```java
IpAddressMatcher ipv4 = new IpAddressMatcher("0.0.0.0/0"); // any IPv4 address
```

This `ipv4` instance would return `true` for any IPv4 address, regardless of the format:

```java
0:0:0:0:0:FFFF:c0a8:1
::FFFF:c0a8:1
192.168.0.1
```
so this may not be what you want. 

If you are trying to do pattern-matching, though, `Pattern` is a better class.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by AnthonyRoelandts** [comment]
@ask4gilles coworker here :)

We actually found the issue on our side and fixed it, thanks for investigating.
