### ISSUE TITLE
Are there any OAuth2 Client Client_Credential login sample?

### ISSUE THREAD

**Issue by andyzhaozhao** [spring-projects/spring-security#7484]
like the title.

**Comment by jgrandja** [comment]
@andyzhaozhao Please post questions to StackOverflow. We use GitHub issues to track bugs and enhancements. Please review the [guidelines](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues).

This [sample](https://github.com/jgrandja/oauth2-protocol-patterns) uses `client_credentials`

**Comment by EXPEylazzari** [comment]
@jgrandja Can we reopen this issue and mark it as a documentation improvement to be done? I think it's a "bug" that this is not easier to find.

I tried the [Spring Security OAuth](https://projects.spring.io/spring-security-oauth/docs/Home.html) documentation homepage or the [Spring Boot OAuth 2](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-security-oauth2) documentation section or the [Spring Cloud Security](https://cloud.spring.io/spring-cloud-security/reference/html/) documentation and none of them seem to lead to that repo you just shared. That repo is under your name, not under the official Spring organization in Github, so it's hard to tell that this is a good example to follow, and not one of the million examples by random people that are just playing with this and uploading it to Github.

So maybe at least update the documentation so that when `client_crendentials` is mentioned, this sample is referenced? WDYT?

**Comment by jgrandja** [comment]
@EXPEylazzari The documentation has been updated just last week. It's in the [snapshot](https://docs.spring.io/spring-security/site/docs/5.2.0.BUILD-SNAPSHOT/reference/htmlsingle/#oauth2client) but will be available in in the 5.2.0 GA release this Monday.
