### ISSUE TITLE
BindAuthenticator with wrong password stalls instead of failing

### ISSUE THREAD

**Issue by heruan** [spring-projects/spring-security#7543]
### Summary

Using `BindAuthenticator` to authenticate against LDAP, works well with correct credentials but with a wrong password, it stalls instead of failing and ends up throwing a timeout exception.

### Actual Behavior

As explained above.

### Expected Behavior

The `BindAuthenticator` fails immediately if the password is wrong.

### Configuration

See sample below.

### Version

Spring Security 5.2.0.RELEASE

### Sample

```java
var contextSource = new LdapContextSource();
contextSource.setUrls(urls);
contextSource.afterPropertiesSet();

var authenticator = new BindAuthenticator(contextSource);
authenticator.setUserSearch(new FilterBasedLdapUserSearch(base, filter, contextSource));
authenticator.afterPropertiesSet();

var correct = new UsernamePasswordAuthenticationToken(username, "correct");
authenticator.authenticate(correct); // <- it succeeds immediately

var wrong = new UsernamePasswordAuthenticationToken(username, "wrong");
authenticator.authenticate(wrong); // <- it stalls and timeouts
```

**Comment by heruan** [comment]
Any feedback about this?

**Comment by rwinch** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by heruan** [comment]
Thank you @rwinch, here's the question: https://stackoverflow.com/questions/58726620
