### ISSUE TITLE
DelegatingReactiveAuthenticationManager signals error instead of continuing

### ISSUE THREAD

**Issue by DarrenForsythe** [spring-projects/spring-security#7548]
### Summary

The `DelegatingReactiveAuthenticationManager` should continue to the next authentication manger on error, rather than signalling an error and stopping the stream.

### Actual Behavior

Adding Opaque and JWT support to a WebFlux resource server via, 

```
    public class MultiTokenSupport
            implements ReactiveAuthenticationManagerResolver<ServerHttpRequest> {

        private final ReactiveAuthenticationManager authenticationManager;

        public MultiTokenSupport(
                JwtReactiveAuthenticationManager jwtAuthenticationProvider,
                OpaqueTokenReactiveAuthenticationManager opaqueTokenAuthenticationProvider) {
            authenticationManager = new DelegatingReactiveAuthenticationManager(jwtAuthenticationProvider,
                    opaqueTokenAuthenticationProvider);
        }

        @Override
        public Mono<ReactiveAuthenticationManager> resolve(ServerHttpRequest serverHttpRequest) {
            return Mono.just(authenticationManager);
        }
    }
```

JWT tokens will work as expected, however Opaque tokens will fail as the `JwtReactiveAuthenticationManager` creates an error for the Opaque token.

### Expected Behavior

The DelegatingReactiveAuthenticationManager should continue the flux instead of singnalling an error from an AuthenticationManager. Which would mirror the Servlet/Web implementation closer.

A rough impl. that does work, 

```
        authenticationManager = authentication -> Flux
                .fromIterable(Arrays.asList(jwtAuthenticationProvider,
                        opaqueTokenAuthenticationProvider))
                .concatMapDelayError(reactiveAuthenticationManager -> reactiveAuthenticationManager
                        .authenticate(authentication)
                .next();
```

This solution does introduce more complexities around the error handling as there maybe 0 to many errors to unwrap, which may be best to be wrapped in a custom exception that Spring Security would still return a 401. 

### Version

Spring Boot 2.2.0, Spring Security 5.2

**Comment by DarrenForsythe** [comment]
I also noted this in the test class, 

> // delay to try and force delegate2 to finish (i.e. make sure we didn't use flatMap)

If the second delegate was finishing an error would occur as it would return null instead of Mono.empty() causing an NPE to be throwing by reactor. Is there an expectation that all the elements would be applied async and the first one found returned?

**Comment by jzheaux** [comment]
I had a quick chat with @rwinch about this, and he confirmed that `DelegatingReactiveAuthenticationManager`'s current short-circuiting behavior is intentional -- if a delegate authentication manager returns `Mono.empty()`, then the class will move on to the next delegate authentication manager in the list.

Ideally, you'd have something in the request that would indicate which kind of authentication to do. Absent that, you can, of course, create your own publisher that behaves as you describe, or you can peek at the contents of the token to make the decision instead of looping through the two authentication managers.

Since the class you've indicated is behaving as designed, I'm going to close the ticket, but please feel free to post any follow-ups here.

**Comment by jzheaux** [comment]
> If the second delegate was finishing an error would occur as it would return null instead of Mono.empty() causing an NPE to be throwing by reactor.

You are correct - this is what the test is trying to confirm. Hypothetically, if `DelegatingReactiveAuthenticationManager` were using `flatMap`, then `delegate2` would run, causing the test to fail. Since it is using `concatMap`, even though `delegate1` is delayed, `concatMap` won't try and subscribe to `delegate2` until `delegate1` finishes.

**Comment by DarrenForsythe** [comment]
I figured that might have been the case after thinking more on it. I think I'm fine with the short circuit behavior and rolling my own impl. Perhaps some Java doc to the nature of this? 

It was a surprise for me as I would have assumed all managers would have been tried, given that you cannot assume that a manager will return empty on failure or error (as the JWT manager does).
