### ISSUE TITLE
@PreAuthorize on methods with generic parameter types

### ISSUE THREAD

**Issue by epictecch** [spring-projects/spring-security#7588]
### Summary

I encountered a problem with spring security and the @PreAuthorize annotation. When starting my application by executing the gradle task bootRun, everything works as expected. When starting my application from STS, some annotated methods can be called without passing the security check.

### Actual Behavior

When starting my application from STS, the PreAuthorize check is ignored and the method can be called without having permission.
See the sample project on github.
The class WebController offers three endpoints. When starting from STS, the endoint localhost:8080/restrictedWithParam can be called without authentication.
The endpoint localhost:8080/restrictedWithoutParam works fine, i.e. the authentication check is done.

### Expected Behavior

I expect that the endpoint localhost:8080/restrictedWithParam cannot be called without authentication.
I think there is a problem with the parameter type. When I completely remove the dummy implementation AbstractService.methodWithParameter(), then everything works fine.

### Configuration

Nothing to mention here. If I can provide more information, please let me know.

### Version

Spring Boot 2.2.0.RELEASE
Java 12 (jdk 12.0.2.10-hotspot)
STS Version: 4.4.1.RELEASE (Build Id: 201910232221)

### Sample

https://github.com/epictecch/securitydemo

**Comment by planitian** [comment]
I has checed you code ,that is my answer. you should add @PreAuthorize on your methed in controller that you want protect. because spring security  use cglib to accomplish authtication.  Note,shoul not use
@PreAuthorize  on service.

**Comment by ankurpathak** [comment]
> I has checed you code ,that is my answer. you should add @PreAuthorize on your methed in controller that you want protect. because spring security use cglib to accomplish authtication. Note,shoul not use
> @PreAuthorize on service.

@Pre/PostAuthorize/Filter will work with both controller and service. Cglib is not limited to web layer and will work with any layer.

**Comment by rwinch** [comment]
@epictecch Thanks for the report. When I first read through this it seems like it is an Eclipse issue since it works fine from the commandline.

I was able to reduce this down to [a sample](https://github.com/rwinch/gh-7588/blob/master/src/test/java/com/example/securitydemo/SecurityDemoApplicationTests.java) that does not even use Spring.

```java
Method method = IEntityService.class.getMethod("methodWithParameter", Object.class);
Class<?> targetClass = DemoService.class;
		
Method result = targetClass.getMethod(method.getName(), method.getParameterTypes());
		
assertThat(result.getDeclaringClass()).isEqualTo(DemoService.class);
```

If you run the sample in STS with `Run As -> JUnit Test`, then the test fails. Running from the CLI or using `Run As -> Gradle Test` it passes.

So why does Spring Security fail? The problem is that Spring Security's [PrePostAnnotationSecurityMetadataSource](https://github.com/spring-projects/spring-security/blob/5.2.0.RELEASE/core/src/main/java/org/springframework/security/access/prepost/PrePostAnnotationSecurityMetadataSource.java#L123) does not find the correct `specificMethod` which means the `@PreAuthorize` on `DemoService` is not found. The above test is a simplified version of how that fails using the Eclipse compiler.

**Comment by planitian** [comment]
@ankurpathak I learn,thank you very much

**Comment by epictecch** [comment]
Thank you very much, rwinch.
I opened a bug report for eclipse.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=552646
