### ISSUE TITLE
Allow configuring authenticationManagerResolver for SAML2

### ISSUE THREAD

**Issue by eleftherias** [spring-projects/spring-security#7654]
### Summary

It should be easier to configure the `authoritiesExtractor`, `authoritiesMapper` and `responseTimeValidationSkew` on the `OpenSamlAuthenticationProvider`. 
See gh-7642.

Allowing an `authenticationManagerResolver` for SAML2 login will allow customizing the `OpenSamlAuthenticationProvider`.

This should be similar to [OAuth2ResourceServerConfigurer.authenticationManagerResolver](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurer.html#authenticationManagerResolver-org.springframework.security.authentication.AuthenticationManagerResolver-).

**Comment by fhanik** [comment]
@eleftherias I've been reviewing this, and implemented a possible solution in [1d71a62](https://github.com/fhanik/spring-security/commit/1d71a62c44b3b25f170ea9e391ccc016811be573).

It does however become difficult to justify the use of a `AuthenticationManagerResolver` simply for the ability to configure setters on the authentication provider. 

The `AbstractAuthenticationFilterConfigurer` calls [`setAuthenticationManager`](https://github.com/spring-projects/spring-security/blob/f5f965b6aac76596e1745056d4b015b60a7cbd85/config/src/main/java/org/springframework/security/config/annotation/web/configurers/AbstractAuthenticationFilterConfigurer.java#L291-L292) making the end result of the configuration less obvious.

I will continue reviewing this, but may opt to just make the authentication provider configurable, or the options on it, rather than adding a resolver.

**Comment by eleftherias** [comment]
@fhanik The idea with having the `AuthenticationManagerResolver` configurable is that it would support multi-tenancy in the future.
For now, we only need the ability to set the options on the provider.
I will leave it up to you to decide which option is best.
