### ISSUE TITLE
Where should I find JdbcTokenStore script for OAuth2

### ISSUE THREAD

**Issue by qrqhuang** [spring-projects/spring-security#7672]
In spring security official docs home [oauth2.html](https://projects.spring.io/spring-security-oauth/docs/oauth2.html).  the link for  [JDBC version](https://projects.spring.io/spring-security-oauth/docs/JdbcTokenStore) page is not found.

So where can I find the  `JdbcTokenStore` script for OAuth2.

**Comment by eleftherias** [comment]
@qrqhuang Here is the [Javadoc for the `JdbcTokenStore`](https://docs.spring.io/spring-security/oauth/site/docs/2.4.0.RELEASE/apidocs/org/springframework/security/oauth2/provider/token/store/JdbcTokenStore.html).
Since this class is part of [spring-security-oauth](https://github.com/spring-projects/spring-security-oauth), can you please create an issue in that project reporting the broken link?
