### ISSUE TITLE
Customize login page

### ISSUE THREAD

**Issue by garrychnca** [spring-projects/spring-security#7692]
https://github.com/spring-projects/spring-security/blob/55f1c695e110387f344a21d72d44c3302f5879a9/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java#L3147

As the above line of code suggests, the `loginPage` is hardcode to a new instance of `LoginPageGeneratingFilter`.

In most of the cases this is sufficient. However, in my case, an extra `challenge` query parameter will come along with the request to be handled by the login page filter and I want to make use of that `challenge` value in some custom logic.

Hence I will want to set the `loginPage` to a custom login page generating web filter. I don't think it is currently possible unless I subclass `ServerHttpSecurity` class and do a lot of copy and paste as most of the configuration logic are in private methods.

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by garrychnca** [comment]
@eleftherias 

Thanks for the reply. 

However, I think this issue aims to ask for enhancement against more flexibility when configuring the `ServerRequestSecurity`. As mentioned in the description, and the code snipet, it is clear that for the current implementation one cannot configure the `loginPage` to use another class which provides more custom login page generation.

Given what I have said, do you agree it is an ask-for-enhancement?

**Comment by eleftherias** [comment]
@garrychnca Can you add some more details describing what you are trying to accomplish?
Would it be possible by setting a custom `authenticationEntryPoint`?
