### ISSUE TITLE
Force logout on access token expiry.

### ISSUE THREAD

**Issue by atoztoa** [spring-projects/spring-security#7718]
### Summary

When access token expires, I am calling `/authorize` endpoint and it returns a new `code` which in turn allows me to get a fresh token. What is the point of have `accessTokenValiditySeconds` if the user can keep getting fresh tokens without logging in again?

I know the ask is brief. I want to start a discussion to understand what the expected behavior is. When access token expires, should the user be shown the login screen?

**Comment by jgrandja** [comment]
@atoztoa Please ask questions on StackOverflow. GitHub issues are for bug reports and feature requests only. Thank you.

**Comment by jzheaux** [comment]
@atoztoa, access tokens expire so that clients are forced to request a renewal on a periodic basis. The authorization server may choose to grant or deny that request.

If the client calls `/authorize`, for example, the authorization server may choose to show a login page instead of issuing a new `code`.

As @jgrandja said, StackOverflow is probably a better place for questions - feel free to add a link to your SO question here, so that folks with the same question can find what you learned.
