### ISSUE TITLE
Discoverable Oauth2 provider for Spring Security

### ISSUE THREAD

**Issue by allw0rth** [spring-projects/spring-security#7763]
My goal is to have a spring boot application utilize a discoverable Oauth2 provider that can be started from any hostname/port in the network. Instead of relying on hardcoded properties such as spring.security.oauth2.client.provider.provider.authorization-uri, the url would be dynamically configured at runtime.

Originally I was looking into providing a custom configuration for InMemoryClientRegistrationRepository and then extending the ClientRegistration class to provide my own ProviderDetails based on the host/port of the Oauth2 provider. However, due to the constructor of ProviderDetails being private, this approach will not work.

Has anyone implemented this through another method? Or are there any best practices that can be used to create this configuration?

**Comment by jzheaux** [comment]
@allw0rth have you already looked into [OIDC Discovery](https://openid.net/specs/openid-connect-discovery-1_0.html) or [OAuth 2.0 Metadata](https://tools.ietf.org/html/rfc8414)? The reason I ask is because this is [already](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#webflux-oauth2-login-openid-provider-configuration) [supported](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#specifying-the-authorization-server) and might address your needs.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
