### ISSUE TITLE
Could I config HTTP method of requesting refresh token?

### ISSUE THREAD

**Issue by Koprvhdix** [spring-projects/spring-security#7767]
### Summary
When I developed, I hoped use json to post the refresh token request. Is there any selution?

**Comment by jzheaux** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.

**Comment by Koprvhdix** [comment]
> Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.

Thank you. I'm sorry for openning this issues, and I will ask this question in Stack Overflow.
