### ISSUE TITLE
SEC-517: TokenBasedRememberMeServices to support refreshing of cookie expiration time

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#778]
["Kalle Korhonen":https://jira.spring.io/secure/ViewProfile.jspa?name=kaosko](Migrated from ["SEC-517":https://jira.spring.io/browse/SEC-517?redirect=false]) said:

The TokenBasedRememberMeServices should support renewal of the cookie at auto login time. At present the cookie will expire in the tokenValiditySeconds (which defaults to 14 days) from the time of the original interactive authentication. It is desirable if applications could instead make the tokenValiditySeconds duration relative to the last interactive OR automatic authentication.

This represents a new feature of TokenBasedRememberServices which will be implemented by a boolean property, extendValidityOnAutomaticLogin, which will default to false to maintain consistency with original behaviour.

**Comment by kaosko** [comment]
While the issue is closed, I **must** note how both refreshing and absurd it was to get a notification about this issue now, almost 10 years later, as it was the one that originally pushed me to look for alternative options for Acegi such as JSecurity (now Apache Shiro), become a committer for it and eventually write a module that would implement rolling tokens for your end-to-end (http://www.tynamo.org/2012/08/15/rememberme-with-rolling-tokens/).
