### ISSUE TITLE
Digest Auth support in WebClient

### ISSUE THREAD

**Issue by PyvesB** [spring-projects/spring-security#7861]
### Summary

Spring's WebClient allows specifying Basic Auth credentials quite simply:
```
webClient.get()
        .uri(someEndpoint)
        .headers(httpHeaders -> httpHeaders.setBasicAuth(someUserName, somePassword))
        ...
```

However, there doesn't seem to be a way to configure the WebClient to perform Digest Auth ([RFC 7616](https://tools.ietf.org/html/rfc7616)).

I understand Spring's stance on not wanting to support this protocol in its server capabilities (#7248). However, a lot of servers rely on Digest Auth, and given that WebClient supports the less secure Basic Auth protocol, it would make sense to add support to the client's capabilities. Note that this feature has been requested in other places, for example on [StackOverflow](https://stackoverflow.com/questions/50865597/spring-webflux-webclient-does-it-supports-digest-based-authentication).

Thanks for considering this feature request!

**Comment by eleftherias** [comment]
@PyvesB Thanks for the suggestion.

I think the StackOverflow question may have misled you by mentioning Spring Security, since both `WebClient` and the `setBasicAuth` method that you mentioned are part of [Spring Framework](https://github.com/spring-projects/spring-framework).

I suggest reporting the issue in that repository instead.
