### ISSUE TITLE
how to disable spring security globally , such as in yaml config file

### ISSUE THREAD

**Issue by UCNTFME** [spring-projects/spring-security#8041]
### Summary
how to disable spring security globally?

### Actual Behavior
tried many methods, but no one work

### Expected Behavior
in configuration file add :
```
spring:
    security:
       enable: false
```
then, the serurity feature can be removed .

**Comment by rwinch** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
