### ISSUE TITLE
Cache token validation result

### ISSUE THREAD

**Issue by RomainWilbert** [spring-projects/spring-security#8117]
### Summary
 I can't find if there is a way to prevent bearer validation on each request for a short period. I would hope there was a cache that could be configured for that purpose?

### Configuration
Spring boot REST api secured with Spring Security

### Version
5.1.7

**Comment by rwinch** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by jzheaux** [comment]
Related to https://stackoverflow.com/questions/60673828/is-there-a-way-with-spring-security-to-cache-token-introspection-result/60723929
