### ISSUE TITLE
where is the spring-security-openid sample

### ISSUE THREAD

**Issue by vangyong** [spring-projects/spring-security#8129]
where is the spring-security-openid sample?  It can be instead of spring-social?

**Comment by rwinch** [comment]
All of the samples are documented at https://docs.spring.io/spring-security/site/docs/current/reference/html5/#samples

Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
