### ISSUE TITLE
spring security 5.2.x resource-server BearerTokenAuthentication

### ISSUE THREAD

**Issue by 99bird** [spring-projects/spring-security#8156]
If I want to access to the permitAll web api with bearer token ,but my token is invalid, I cant't access the web api.  If I access the permitAll web api without bearer token ,in this way I can access it.  Is this a logic problem？

**Comment by eleftherias** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
