### ISSUE TITLE
Use HTTP Basic Auth with OAuth2 login at the same time

### ISSUE THREAD

**Issue by sergiopacezup** [spring-projects/spring-security#8231]
### Summary

Is it possible to configure HTTP Basic Auth for a group of paths and OAuth2 for the rest of the application?

### Actual Behavior

?

### Expected Behavior

GET /basic
Authorization Basic a234abcdef

GET /oauth
Authorization Bearer a9b4c5d0f

### Configuration

The configuration below is not valid, but I would like to be able to do something like that: 
```
http.authorizeRequests()
    .antMatchers("/basic").httpBasic()
    .antMatchers("/oauth").oauth2ResourceServer().jwt()
    .anyRequest().authenticated()
```
### Version
5.2.2

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
