### ISSUE TITLE
Allow customization of restOperations for JwtDecoder built using an issuer uri

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-security#8365]
`JwkSetUriJwtDecoderBuilder` allows customizing the `restOperations` that is used to make calls to the authorization server. However, when using an `issuerUri`, using `JwtDecoders.fromIssuerLocation`, this customization doesn't look like it's possible. [This issue](https://github.com/spring-projects/spring-boot/issues/20750) in Spring Boot is the original issue for enabling these sort of customizations.

**Comment by jgrandja** [comment]
@mbhave We have a similar issue with `ClientRegistrations` as we do with `JwtDecoders`. The following tickets are all related #7027 #7391 #5607. We're planning on addressing this for 5.4.

**Comment by 20fps** [comment]
The same issue will be present also for `Cache` added here:
https://github.com/spring-projects/spring-security/pull/8332

**Comment by jzheaux** [comment]
It might be better to introduce `NimbusJwtDecoder#withIssuerUri` so that applications have full access to the builder. One could then do:

```java
NimbusJwtDecoder jwtDecoder = NimbusJwtDecoder
        .withIssuerUri(issuerUri)
        .restOperations(rest)
        .build();
jwtDecoder.setJwtValidator(JwtValidators.createDefaultWithIssuer(issuerUri));
```

And the builder would use that `RestOperations` to both query the discovery endpoint on startup and the JWKs endpoint when verifying JWTs.

There may also be value in `JwtDecoders` having a configurable `RestOperations` as well, but I think it's important to keep in mind that it's a convenience class and shouldn't expose every feature of the Nimbus builder.

**Comment by jgrandja** [comment]
This issue is related to #7027. A proposed solution is provided in this [comment](https://github.com/spring-projects/spring-security/issues/5607#issuecomment-613053361).

A similar solution could be implemented to address this issue, specifically for `JwtDecoders` and `ReactiveJwtDecoders`.

**Comment by jgrandja** [comment]
Closing in favour of #8882. Please see [JwtDecoders](https://github.com/spring-projects/spring-security/issues/8882#user-content-jwt-decoders) and provide any additional feedback there.
