### ISSUE TITLE
Spring Security configuration 

### ISSUE THREAD

**Issue by snow-flowers** [spring-projects/spring-security#8381]
I have a  problem about Spring Security。it may not a bug。but i can‘t find answer。

Spring Security provides a variety of options for performing authentication. These follow a simple contract – an Authentication request is processed by an AuthenticationProvider and a fully authenticated object with full credentials is returned.

My configuration it may look like this：
![image](https://user-images.githubusercontent.com/56668765/79090995-22b72280-7d7e-11ea-8c84-b0debfc0d036.png)
in ProviderManager class：
the source code is like this：
![image](https://user-images.githubusercontent.com/56668765/79090890-bdfbc800-7d7d-11ea-9469-44edba6a7504.png)
It does circular processing for all AuthenticationProvider。
Now i want：
if(A)
   use daoAuthenticationProvider
if(B)
   use daoAuthenticationProvider2
what should I do？
My configuration is spring-security2.0.3.I want an idea。
 should  I rewrite one custom ProviderManager？

**Comment by jzheaux** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
