### ISSUE TITLE
spring security with oauth2 resource server multiple jwk uri's

### ISSUE THREAD

**Issue by ndopj** [spring-projects/spring-security#8458]
**Expected Behavior**

Spring Security should provide way to use multiple Oauth2 resource server jwk uris's
Spring webflux Oauth2 resource server functionality is not included directly inside Spring Security but is depending on it (see following links).

**Current Behavior**

Spring Security (5.3) provided way for webflux to use multiple Oauth2 resource server issuer uri's:
https://github.com/spring-projects/spring-security/pull/7887 (merge)
https://github.com/spring-projects/spring-security/issues/7857 (original issue)

**Context**

I am trying to configure spring boot webflux application acting as oauth2 resource to use multiple identity providers.
Currently only issuer URI can be used to verify access token
I am not aware of any workarounds

**Comment by rwinch** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
