### ISSUE TITLE
Support customization of BearerTokenResolver in JwtIssuerAuthenticationManagerResolver

### ISSUE THREAD

**Issue by marci74** [spring-projects/spring-security#8535]
**Expected Behavior**

It should be possible to set or customize the BearerTokenResolver inside the JwtIssuerAuthenticationManagerResolver

**Current Behavior**

The customization is not possible.

**Context**

I have to support multiple token issuers and bearer tokens in query parameters. I would like to use the new JwtIssuerAuthenticationManagerResolver but I cannot alter the "allowUriQueryParameter"
property of the DefaultBearerTokenResolver which is being used inside the JwtIssuerAuthenticationManagerResolver.JwtClaimIssuerConverter class.

**Comment by jzheaux** [comment]
Thanks for the report, @marci74. I think what needs to be done here is to remove the dependency on the bearer token resolver altogether.

Since the resolver can return an `AuthenticationManager`, it could return one that retrieves the token from the given authentication, e.g.:

```java
public AuthenticationManager resolve(HttpServletRequest request) {
    return authentication -> {
        BearerTokenAuthenticationToken token = (BearerTokenAuthenticationToken) authentication;
        String issuer = this.issuerConverter.convert(token);
        // ...
        return authenticationManager.authenticate(token);
    };
}
```

Something similar can be done on the reactive side as well.

Would you be interested in filing a PR to address this?

**Comment by AbstractConcept** [comment]
@jzheaux I have run into a very similar issue, if not the same one.

Using an external `oauth2ResourceServer`, in a multi-tenant environment, it should be possible to override / select a custom `JwtDecoder` / `jwtAuthenticationProvider` with a custom `jwtAuthenticationConverter`, as not all of the JWT tokens are the same, and this leads to errors.

Currently, according to the official documentation, if there is a need to support multi-tenancy by JWT Claim, one can use `JwtIssuerAuthenticationManagerResolver` that has to be configured by a class extending `WebSecurityConfigurerAdapter`, however, it comes with an overriden `public AuthenticationManager resolve(String issuer)` method, that contains a predefined, hardcoded basic `JwtAuthenticationProvider`, that also contains a predefined, hardcoded `JwtAuthenticationConverter`, which in turn contains a predefined, hardcoded `JwtGrantedAuthoritiesConverter`, the root of my problems.

Normally, the issue could be solved by configuring a `Customizer<JwtConfigurer>` within the `HttpSecurity` DSL, but `OAuth2ResourceServerConfigurer` runs the `validateConfiguration()` method that throws an `IllegalStateException` because, quote: If an authenticationManagerResolver() is configured, then it takes precedence over any jwt() or opaqueToken() configuration, and that's understandable, however, there should be a way to configure your own Customizer/JwtGrantedAuthoritiesConverter.

Currently, I have solved this issue by using my own implementation of a `JwtIssuerAuthenticationManagerResolver`, that I have used instead of the 'official' one, that basically creates a new `JwtAuthenticationConverter` and sets my custom `JwtGrantedAuthoritiesConverter`, but I am willing to work on a PR, since the issue seems to be stale.

Some additional information would be great though: could the solution be based on allowing the end-user to provide his own `JwtAuthenticationProvider`, that will take priority over the default one?

**Comment by jzheaux** [comment]
Sounds great, @AbstractConcept, the issue is yours.

**Comment by jzheaux** [comment]
How is this coming, @AbstractConcept? Are you still able to provide a PR?

**Comment by AbstractConcept** [comment]
@jzheaux Yes, apologies for the delay. The PR should be submitted by the end of this week (at the latest).

**Comment by jzheaux** [comment]
Is this something you are still wanting to contribute, @AbstractConcept?

**Comment by AbstractConcept** [comment]
Sometimes life gets in a way, unfortunately. If this is still a valid issue, and hasn't been fixed yet with some other PR, I got the code ready. Could you provide an update on the status, so I know whether to create a PR? @jzheaux

**Comment by jzheaux** [comment]
@AbstractConcept, yes, a PR is still welcome. Thanks for checking.
