### ISSUE TITLE
Maven enforcer plugin throws convergence error for version 5.3.2.RELEASE

### ISSUE THREAD

**Issue by bratwurzt** [spring-projects/spring-security#8543]
```
Dependency convergence error for com.nimbusds:nimbus-jose-jwt:8.8 paths to dependency are:
+-some.internal.package:our-security:1.5.32-SNAPSHOT
  +-org.springframework.security:spring-security-oauth2-client:5.3.2.RELEASE
    +-com.nimbusds:oauth2-oidc-sdk:7.1.1
      +-com.nimbusds:nimbus-jose-jwt:8.8
and
+-some.internal.package:our-security:1.5.32-SNAPSHOT
  +-org.springframework.security:spring-security-oauth2-jose:5.3.2.RELEASE
    +-com.nimbusds:nimbus-jose-jwt:8.9
```

**Comment by jgrandja** [comment]
@bratwurzt Please provide more details and a minimal sample or test that reproduces the error.

**Comment by bratwurzt** [comment]
> 
> 
> @bratwurzt Please provide more details and a minimal sample that reproduces the error.

sorry, notifications were muted. Will prepare one next week ASAP.

**Comment by jgrandja** [comment]
#8564 may be related

**Comment by jzheaux** [comment]
@bratwurzt Thanks for the report. 

This is something that the community should take up with the Nimbus team. 

The fact is that the `oauth2-oidc-sdk` and `nimbus-jose-jwt` releases aren't synchronized. For example, [Nimbus released `nimbus-jose-jwt:8:18` today](https://mvnrepository.com/artifact/com.nimbusds/nimbus-jose-jwt/8.18), but [the latest `oauth2-oidc-sdk`](https://mvnrepository.com/artifact/com.nimbusds/oauth2-oidc-sdk/8.4.3) is on `nimbus-jose-jwt:8.14.1`.

Because of that, if we were to constrain Spring Security to stay in sync with `oauth2-oidc-sdk`, it would delay us from getting valuable `nimbus-jose-jwt` updates. Further, adding a constraint like that would make our dependency management story more complex.

To me, it seems to be a reasonable request for Nimbus to keep `oauth2-oidc-sdk` up to date with the latest `nimbus-jose-jwt` by releasing `oauth2-oidc-sdk` when `nimbus-jose-jwt` is released. We do this kind of thing for [`spring-security-oauth2-boot-autoconfigure`](https://github.com/spring-projects/spring-security-oauth2-boot/milestones), for example, to keep it in sync with Spring Boot.

If you [log a ticket](https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issues/new) with Nimbus, please consider adding the link here so that others who find this ticket can follow along.
