### ISSUE TITLE
PKCE code verifier code challenge generated by client

### ISSUE THREAD

**Issue by Piotr-Filochowski** [spring-projects/spring-security#8610]
Hi,

as i understand PKCE in this flow code verifier and code challenge should be created on a clients front-end side (for example native app). 
To implement that i have to add additional parameters to token request (endpoint on clients backend application that is responsible for exchange of authorization code for access token).  I was looking for option for implementing it by customizing spring-security-oauth2-client, but I'm not sure is such possibility provided.  Is there such possibility to override this token endpoint with his parameters, or should i write this endpoint from scratch? 

Here is sequence diagram with flow:

<img width="884" alt="sequence_diagram" src="https://user-images.githubusercontent.com/37939948/83250658-c92d7a80-a1a8-11ea-87b7-39494f3849dc.png">

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).

**Comment by Piotr-Filochowski** [comment]
Okey, thanks for answering. Here is my post on stackoverflow:
https://stackoverflow.com/questions/62062191/additional-parameter-in-oauth2-token-request/62091450#62091450
