### ISSUE TITLE
Support for MatchableHandlerMapping with parsed patterns

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-security#8691]
In Spring Framework 5.3 snapshots Spring MVC has support for parsed `PathPattern`s, see https://github.com/spring-projects/spring-framework/issues/24945. 

After the changes if a `HandlerMappingIntrospector` returns a `MatchableHandlerMapping` [with](https://github.com/spring-projects/spring-framework/blob/5225a5741197a7e2123437709c2468e4537b0469/spring-webmvc/src/main/java/org/springframework/web/servlet/handler/AbstractHandlerMapping.java#L121-L154) a `PathPatternParser`, the existing `match` method raises an `IllegalArgumentException`. To support this, Spring Security would need have its own patterns parsed on startup and at runtime it would use either the `PathPattern` or its String representation available via `PathPattern#getPatternString` based on `MatchableHandlerMapping.usesPathPatterns()`.

`PathPattern` expects a parsed `PathContainer` path to match to. There is `ServletRequestPathUtils` to help parse and cache the path in a request attribute, and that is done once in the `DispatcherServlet` but there is also a `ServletRequestPathFilter` that can be used to do the same earlier. That will probably be of interest to Spring Security.

As an aside, there are a number of components in Spring MVC including `MappedInterceptor`, `WebContentInterceptor`, and `UrlBasedCorsConfigurationSource` that operate in similar fashion. They hold parsed patterns and using them either as `PathPattern` or as String patterns with `PathMatcher`. However in their case they simply check whether a parsed `RequestPath` is present or not, while Spring Security can check more directly against through the `MatchableHandlerMapping`.

**Comment by rwinch** [comment]
Thanks for the detailed writeup. I've started work on this [in a branch](https://github.com/rwinch/spring-security/tree/gh-8691-patternparser), but I have a few questions.

The first is that Spring Security uses [some default logic](https://github.com/rwinch/spring-security/blob/f640137b8efeb577c1957577cfedb67c521eca78/web/src/main/java/org/springframework/security/web/servlet/util/matcher/MvcRequestMatcher.java#L75) if no `MatchableHandlerMapping` is found. Now that there is another code path (using PathPatternParser), I'm not sure if this is a good default. What are your thoughts?

The second is that you stated:

> To support this, Spring Security would need have its own patterns parsed on startup

What do you mean it's own patterns parsed at startup? As far as I'm aware [I cannot do this](https://github.com/rwinch/spring-security/blob/f640137b8efeb577c1957577cfedb67c521eca78/web/src/main/java/org/springframework/security/web/servlet/util/matcher/MvcRequestMatcher.java#L96) because parsing is done via `MatchableHandlerMapping` which I need the `HttpServletRequest` to look up. This means I cannot parse the patterns until runtime. Does this sound correct?

**Comment by rstoyanchev** [comment]
The null return value means that no matching handler as found and that Spring MVC would return a 404 or some other 4xx code in case of a near match (e.g. 405) when it processes the request. Whether the pattern matching was done with PathPattern's or PathMatcher shouldn't matter since either way it is not a match. So I would think that any default matching that Spring Security uses in this scenario is okay.

For having Spring Security patterns parsed, yes that is a bit of a challenge. PathPatternParser has two settings that can be changed. One of case sensitivity and another trailing slashes. Does it make sense for Spring Security to have those fixed to some default, e.g. `caseSensitive=false` and `matchOptionalTrailingSeparator=true` so that way Spring Security's matching is always a superset of Spring MVC's? If the answer is no, then Spring Security might have to to maintain a different set of patterns parsed for each combination. For this we might have the HandlerMapingIntrpospector expose a method that returns a list of PathPatternParser instances that are in use and from that Spring Security could determine how many sets of patterns it needs.

**Comment by rwinch** [comment]
> Does it make sense for Spring Security to have those pinned to some default, e.g. caseSensitive=false and matchOptionalTrailingSeparator=true so that Spring Security always matches a superset of Spring MVC might?

This won't work because depending on the rule the user is setting it might be more or less restrictive. For example, the matching might be to denyAll which we would want the pattern to match more things or it might be permitAll in which case we'd want it to match fewer items.

I wonder if there would be a way to expose single `PathPatternParser` so Spring Security could use that vs exposing it on every `HandlerMapingIntrpospector`?

**Comment by rstoyanchev** [comment]
Challenge is, each HandlerMapping can have its own PathPatternParser.

**Comment by rwinch** [comment]
I don't think we can parse up front. Spring Security may have a rule specified that matches multiple HandlerMapping instances. Consider a rule of `/admin/**` for security. Spring MVC may have one `HandlerMapingIntrpospector` match `/admin/foo` and another `HandlerMappingIntrospector` match `/admin/bar`.

**Comment by rstoyanchev** [comment]
The changes for https://github.com/spring-projects/spring-framework/issues/25312 have been made. The `PathPattern` support should be transparent for Spring Security but if you could you take and confirm all is good, that would be great. In any case this can be closed now. We can discuss further under the Spring Framework issue if needed.

**Comment by rwinch** [comment]
Thanks @rstoyanchev The changes look good to me
