### ISSUE TITLE
Default support for classlink

### ISSUE THREAD

**Issue by jmoseman01** [spring-projects/spring-security#8751]
**Expected Behavior**
in the configuraion yml
registration:
    classlink:
           ...

**Current Behavior**

Default support for google, github and okta exist.

**Context**
How has this issue affected you?
What are you trying to accomplish?
What other alternatives have you considered?
Are you aware of any workarounds?
  security:
    oauth2:
      client:
        registration:
          classlink:
            provider: classlink
            client-id: <client id>
            client-secret: <client secret>
            client-authentication-method: post 
            authorization-grant-type: authorization_code
            scope: full,profile,oneroster,openid
            # redirect-uri: https://www.classlink.com/callback?code={registrationId}&response_type=code
            redirect-uri: http://localhost:8080/login/oauth2/code/{registrationId}
            client-name: classlink
        provider:
          classlink:
            authorization-uri: https://launchpad.classlink.com/oauth2/v2/auth
            token-uri: https://launchpad.classlink.com/oauth2/v2/token
            user-info-uri: https://nodeapi.classlink.com/v2/my/info
            user-name-attribute: userId
I've been trying this but I can't get it to authenticate.  Help would be appreciated.

**Comment by jmoseman01** [comment]
Looks like they don't have a jwk set uri

**Comment by eleftherias** [comment]
Thanks for getting in touch, @jmoseman01, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
