### ISSUE TITLE
How to disable spring-security version 5.3.3

### ISSUE THREAD

**Issue by Accidentaly-across** [spring-projects/spring-security#9029]
### Actual Behavior
Hello ,
I want to disable spring-security, in order to be able to skip login verification authority verification.
I tried many methods but I cannot disable spring-security.

### Expected Behavior
disable spring-security version 5.3.3

### Version

Springboot version is v2.3.2.RELEASE 
Spring Security version is 5.3.3

Looking forward to your reply.

Thanks in advance.

Regards,

**Comment by eleftherias** [comment]
Thanks for getting in touch, @Accidentaly-across , but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.

Briefly, though, Spring Boot automatically secures all HTTP endpoints with Basic authentication if Spring Security is on the classpath. If you are using the dependency `org.springframework.boot:spring-boot-starter-security` in your application, then all your endpoint will be secured. If you do not need Spring Security, then you can remove the dependency.
