### ISSUE TITLE
invalid_client error 

### ISSUE THREAD

**Issue by levin950825** [spring-projects/spring-security#9036]
**Describe the bug**
How to catch wrong clients_ ID, it seems that no exception information has been thrown

**Comment by jzheaux** [comment]
Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
