### ISSUE TITLE
Add NameIdFormat support to RelyingPartyRegistration

### ISSUE THREAD

**Issue by Gayathri92** [spring-projects/spring-security#9115]
`RelyingPartyRegistration` contains [SAML 2.0 Metadata](https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf) for both the relying party and its associated asserting party.

It would be nice to include `NameIDFormat` support in both `RelyingPartyRegistration` and `RelyingPartyRegistration.AssertingPartyDetails`. The application could then communicate a set of preferred formats to the asserting party (with #9297, for example) as well as lookup the asserting party's preferred formats.

**Comment by jzheaux** [comment]
Thanks for reaching out, @Gayathri92. Would you please add some more detail about your use case?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by amergey** [comment]
@jzheaux I saw your mention, I will try to submit a PR for this

**Comment by amergey** [comment]
We have some customers where specifying NameIdFormat is mandated by their IDP (or the way they configure it). It seems quite common with PingFederate (but we have that we other as well).

NameIdFormat is a part of NameIDPolicy which support others attributes
SAML Core specification:

**Comment by jzheaux** [comment]
Good points, @amergey. I think I created some confusion by not first updating the description in this ticket. It's updated now.

The reason I'd like to leave changes to `OpenSamlAuthenticationRequestFactory` out of this PR is I'd like to see what happens with https://github.com/spring-projects/spring-security/pull/9277 first since that may obviate the need to change the factory.

Would you be able to update the PR to match the issue's description?

**Comment by amergey** [comment]
@jzheaux Do you mean updating this PR by keeping only nameid format ? (so remove other part of nameid policy but keeping related work on metadata ?) . Also correct me if I am wrong but it seems to me NameID format is defined at SP level, there is no IDP metadatas related to NameID format.

**Comment by jzheaux** [comment]
Sorry for the delay, @amergey, I was on holiday.

> Do you mean updating this PR by keeping only nameid format

Yes, since that's the only one that appears in metadata.

> NameID format is defined at SP level, there is no IDP metadatas related to NameID format.

I was drawing my thoughts from line 658 of [the spec](https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf) in the `SSODescriptorType` section:

> <NameIDFormat> [Zero or More]
Zero or more elements of type anyURI that enumerate the name identifier formats supported by
this system entity acting in this role. See Section 8.3 of [SAMLCore] for some possible values for
this element.

which applies to both `IDPSSODescriptor` and `SPSSODescriptor`.

That said, I think it would be fine to only add it to the relying party for now. We can always add it to `AssertingPartyDetails` later if necessary.

**Comment by amergey** [comment]
> > NameID format is defined at SP level, there is no IDP metadatas related to NameID format.
> 
> I was drawing my thoughts from line 658 of [the spec](https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf) in the `SSODescriptorType` section:
> 
> > [Zero or More]
> > Zero or more elements of type anyURI that enumerate the name identifier formats supported by
> > this system entity acting in this role. See Section 8.3 of [SAMLCore] for some possible values for
> > this element.
> 
> which applies to both `IDPSSODescriptor` and `SPSSODescriptor`.
> 
> That said, I think it would be fine to only add it to the relying party for now. We can always add it to `AssertingPartyDetails` later if necessary.

Sorry I was not clear enough, when I said "NameID format is defined at SP level, there is no IDP metadatas related to NameID format." I meant in OpenSAML implementation so it would be hard to support it on IDP anyway

**Comment by PHameete** [comment]
Hello all! Thank you for the discussion so far. I have an interest in this issue as well.

Currently if a Relying Party wishes to request the NameID in a specific format the suggested way in the docs is to modify the AuthnRequest as specified here https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-saml2login-opensaml-customization

It would be nice if the `NameIDFormat` field as present on the `SPSSODescriptor` field of the `EntityDescriptor` could be defined via the RelyingPartyRegistration. I think that would be more elegant than modifying a value 'last minute' in the AuthnRequest marshaller, and it would be present on the Relying Party metadata to allow for dynamic configuration as well.

I imagine this would be used as follows:

```
        RelyingPartyRegistrations
            .fromMetadataLocation(identityProvider.getMetadataUrl())
            .registrationId(identityProvider.getRegistrationId())
            .assertingPartyDetails(builder -> builder.setNameIdFormat(NameIDType.EMAIL))
            .build();
```

**Comment by fr2lancer** [comment]
Also it would be good to access it by

Saml2AuthenticationRequestContext.getRelyingPartyRegistration().getAssertingPartyDetails().**

**Comment by Bas83** [comment]
Unfortunately the link @PHameete shared seems to have been removed from the Spring docs, but an older version is up at https://docs.spring.io/spring-security/site/docs/5.5.2/reference/html5/#servlet-saml2login-opensaml-customization

**Comment by PHameete** [comment]
Thank you @jzheaux!

**Comment by valentingoebel** [comment]
> > > NameID format is defined at SP level, there is no IDP metadatas related to NameID format.
> > 
> > ...
> > 
> > which applies to both `IDPSSODescriptor` and `SPSSODescriptor`.
> > That said, I think it would be fine to only add it to the relying party for now. We can always add it to `AssertingPartyDetails` later if necessary.
> 
> Sorry I was not clear enough, when I said "NameID format is defined at SP level, there is no IDP metadatas related to NameID format." I meant in OpenSAML implementation so it would be hard to support it on IDP anyway

The Shibboleth IDP matches based on the `NameIDFormat` and the `NameID` value itself. If the format is not specified in the `saml2p:LogoutRequest`. The `NameIDFormat` is provided in the IDP metadata xml file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<EntitiesDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata"
    xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
    xmlns:mdui="urn:oasis:names:tc:SAML:metadata:ui"
    xmlns:remd="http://refeds.org/metadata"
    xmlns:saml1md="urn:mace:shibboleth:metadata:1.0">
<EntityDescriptor entityID="...">
    <IDPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        ...
        <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="..." />
        <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign" Location="..." />
        <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="..." />
        <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="..." />
        <NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</NameIDFormat>
        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="..." />
        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign" Location="..." />
        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="..." />
        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="..." />
    </IDPSSODescriptor>
</EntityDescriptor>
</EntitiesDescriptor>
```

The fixed schema for `IDPSSODescriptor` is defined in the interface `org.opensaml.saml.saml2.metadata.IDPSSODescriptor` of opensaml. `IDPSSODescriptor` extends `SSODescriptor`, which has the `getNameIDFormats()` function that lets you retrieve all `NameIDFormat`s given by the IDP. There are no restrictions on retrieving the XML information on the IDP side nor are there any restrictions in opensaml. The problem is clearly with `saml2-service-provider` not implementing it on the `AssertingPartyDetails` metadata and updating `OpenSamlMetadataAssertingPartyDetailsConverter` (which has retrieved the `IDPSSODescriptor` and outputs the AssertingPartyDetails.Builder).

My suggestion is the following: Please implement the `NameIDFormat` for `AssertingPartyDetails` and preferrably support multiple `NameIDFormat`s (I personally only use one).

That alone would be more than helpful enough for me, but you could do one better and automatically choose the `NameIDFormat` from the metadata based on two rules.

-  If there is exactly one `NameIDFormat` in either `AssertingPartyDetails` or `RelyingPartyDetails`, use that `NameIDFormat` as default
-  If there are multiple `NameIDFormat`s in the IDP, then choose the one specified by `RelyingPartyDetails` and throw an error if it is not in the IDP metadata
- otherwise leave it as `unspecified`

The `NameIDFormat` needs to set alongside the `NameID` itself in `OpenSamlLogoutRequestResolver`.

Since the service provider (SP) is under the control of this library, it doesn't make sense to support multiple `NameIDFormat`s on the SP side. Anyone who wants to customize the `NameIDFormat` at runtime can already do it using the `parametersConsumer` in `OpenSaml4LogoutRequestResolver`. What's irritating is that `saml2-service-provider` gives you broken Single Logout on Shibboleth out of the box and you need to learn a lot about the internals of `saml2-service-provider` to simply set the `NameIDFormat` (let alone figuring out that the Shibboleth IDP is very particular about the `NameIDFormat` to begin with, which took several days of back and forth).
