### ISSUE TITLE
jwt-set-uri set the uri from the registration center address

### ISSUE THREAD

**Issue by yumindayu** [spring-projects/spring-security#9117]
Hi,
I want to set jwt-set-uri as the address of the service registration center. Now I can only implement load balancing by myself. Is there any other way to avoid a single point of failure? like use spring cloud gateway method "lb://xxxx/rsa/public"

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
