### ISSUE TITLE
Automatically refresh saml metadata in configurable intervals

### ISSUE THREAD

**Issue by dawi** [spring-projects/spring-security#9134]
**Expected Behavior**

The spring-security-saml extension provides a [`HTTPMetadataProvider`](https://docs.spring.io/spring-security-saml/docs/1.0.x/reference/html/configuration-metadata.html#configuration-metadata-idp-http) which is able to automatically refresh saml metadata in configurable intervals. It would be nice if this feature would also be supported by spring security.

**Current Behavior**

The current API, as far as I can see, does not support automatic metadata reloading.

I tried to implement a custom `InMemoryRelyingPartyRegistrationRepository`, but it seems that there are edge cases which I don't know how to handle correctly. E.g it should be possible to start the application while the IDP is not available and it should recover after IDP is available again.

**Comment by jzheaux** [comment]
I think that there are a couple of ways that you can achieve this with existing Spring components:

* First, you can create an instance of `RelyingPartyRegistrationRepository` where `findByRegistrationId` computes the `RelyingPartyRegistration` and then caches the results for a period of time, like with the `@Cacheable` annotation.

* Second, you can create an instance of `RelyingPartyRegistrationRepository` where an additional `@Scheduled` method computes the `RelyingPartyRegistration` periodically.

Spring's caching and scheduling support is very likely to exceed anything that Spring Security could provide. This approach is also nice because it allows you to periodically update the relying party side of the configuration.

Does that clear things up, or is there still something you'd like to see Spring Security provide?

**Comment by dawi** [comment]
Yes, it's fairly easy to create a simple `RelyingPartyRegistrationRepository` implementation.

I found one pitfall though: If you implement a custom `RelyingPartyRegistrationRepository` by implementing `RelyingPartyRegistrationRepository` and don't implement `Iterable<RelyingPartyRegistration>` too, then in line https://github.com/spring-projects/spring-security/blob/6714112961335adad004979f7e38f580dc5bd004/config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurer.java#L214
`singleProvider` will be false and therefore the "auto-redirect to provider login page" is not done. Therefore it may make sense to implement `Iterable<RelyingPartyRegistration>` also if only one `RelyingPartyRegistration` is configured.

I created two examples of how metadata-reloading could be implemented:

- [keycloak-saml-4-with-metadata-reloading](https://github.com/dawi/spring-authentication-examples/blob/master/keycloak-saml-4-with-metadata-reloading/src/main/java/examples/)
- [keycloak-saml-5-with-bootiful-metadata-reloading](https://github.com/dawi/spring-authentication-examples/tree/master/keycloak-saml-5-with-bootiful-metadata-reloading)

Those are only examples and may very well be improved, but I think they show that it's not as simple as it should/could be.

From a user perspective it would be nice if all this could be part of spring security and spring boot.

**Comment by jzheaux** [comment]
@dawi, I think one thing that might help the community is a sample. Would you be able to contribute [a Boot-based sample](https://github.com/spring-projects/spring-security-samples/issues/2) to `spring-security-samples` that shows what a custom `RelyingPartyRegistrationRepository` looks like?

This would help with the gotcha you mentioned as well as give a starting point to folks who are migrating `spring-security-saml` apps.

**Comment by jzheaux** [comment]
Closing in favor of https://github.com/spring-projects/spring-security-samples/issues/2

**Comment by OrangeDog** [comment]
SAML specifies both `cacheDuration` and `validUntil` attributes. An implementation should follow these for each entity and refresh accordingly, rather than refresh everything at a fixed interval.
