### ISSUE TITLE
XML-based configuration for Spring SAML2

### ISSUE THREAD

**Issue by w8forme** [spring-projects/spring-security#9138]
**Context**

In our current project we've been using [spring saml extension](https://github.com/spring-projects/spring-security-saml) for a couple of years. It works fine so far except this extension isn't supported anymore. Right now we are planning to migrate to Spring Security native implementation instead of using the outdated extension. We don't have Spring Boot and all our configs for Spring Security are XML-based. Is there any information about migration for existing users and what's more important some examples of XML-based configuration without Spring Boot?

**Expected Behavior**

Would be awesome to have:

- examples of XML-based based config without Spring Boot
- migration guide for existing users of the spring saml extension.

**Current Behavior**

**Comment by dawi** [comment]
Looks similar to https://github.com/spring-projects/spring-security/issues/8685.

**Comment by jzheaux** [comment]
Thanks for the suggestion, @w8forme. I'm going to close this as a duplicate of #9012, but please feel free to comment over there if you'd like to add to the conversation.

**Comment by marcusdacoregio** [comment]
Hi @gspadmapriya.

Yes, there is this sample https://github.com/spring-projects/spring-security-samples/tree/5.7.x/servlet/xml/java/saml2/login-logout and also the [migration guide](https://github.com/spring-projects/spring-security/wiki/SAML-2.0-Migration-Guide) that may help you with the migration.

**Comment by gspadmapriya** [comment]
Is there any extensive example in xml as I have to replace the current
configuration of Saml2entrypoint, metadata filter, extended metadata
delegate?

also looking for multitenancy XML examples of relaying party repositories,
resolvers, etc.

Thank you, any help is much appreciated!

**Comment by marcusdacoregio** [comment]
For now, there is no extensive sample showing the XML configuration. The work on the migration guide and further examples are now paused since we have a lot on our plate with the upcoming major releases.

I'd suggest that you read the migration guide and also the reference docs to see the differences, if there is something that you cannot figure out, please open an issue and let's see how to improve that.

**Comment by gspadmapriya** [comment]
I am creating custom RelyingPartyRegistrationRepository
where i am giving as in spring doc

RelyingPartyRegistration registration = RelyingPartyRegistration
        .withRegistrationId("example")
        .assertingPartyDetails(party -> party
                .entityId("https://idp.example.com/issuer")

.singleSignOnServiceLocation("https://idp.example.com/SSO.saml2")
                .wantAuthnRequestsSigned(false)
                .verificationX509Credentials(c ->
c.add(assertingPartyCredential()))
        )
        .build();
inMemoryRelyingPartyRegistrationRepository = new
InMemoryRelyingPartyRegistrationRepository(registration);

But when this custom class is instantiated as Bean getting exception as
   Caused by:
org.springframework.beans.factory.UnsatisfiedDependencyException: Error
creating bean with name 'saml2RelyingPartyRegistrationRepository':
Unsatisfied dependency expressed through field 'privateKey'; nested
exception is org.springframework.beans.ConversionNotSupportedException:
Failed to convert value of type 'java.lang.String' to required type
'java.security.PrivateKey'; nested exception is
java.lang.IllegalStateException: Cannot convert value of type
'java.lang.String' to required type 'java.security.PrivateKey': no matching
editors or conversion strategy found

Any help will be appreciated, thanks

**Comment by marcusdacoregio** [comment]
You can see an example of a `RelyingPartyRegistration` configuration with its certificates [here](https://github.com/spring-projects/spring-security-samples/blob/5.7.x/servlet/spring-boot/java/saml2/login-single-tenant/src/main/java/example/SecurityConfiguration.java), it may help you since you are having problems with conversion to a private key.

**Comment by gspadmapriya** [comment]
Hello

Earlier we used to extend the class SAMLContextProviderImpl to wrap it for
load balancer. So is that taken care of in 5.7.3 and opensaml 4?

If not, what is the equivalent class that needs to be extended?

Thank you
