### ISSUE TITLE
WebFlux security should not overwrite the default entry point with a delegating entry point

### ISSUE THREAD

**Issue by foo4u** [spring-projects/spring-security#9266]
**Describe the bug**

When `ServerHttpSecurity.build()` creates a `SecurityWebFilterChain`, it replaces the default entry point with the last delegating entry point in `this.defaultEntryPoints`.

https://github.com/spring-projects/spring-security/blob/3cba4eccdcd5f17932ea9f365bd6df2684820819/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java#L1434-L1445

Specifically:

```java
result.setDefaultEntryPoint(this.defaultEntryPoints.get(this.defaultEntryPoints.size() - 1).getEntryPoint());
```

Since delegating entry points should be applied conditionally, this breaks the contract for certain default entry points, such as [`OAuth2LoginSpec.setDefaultEntryponits`](https://github.com/spring-projects/spring-security/blob/3cba4eccdcd5f17932ea9f365bd6df2684820819/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java#L3236), which are designed to be conditional. For example, the `OAuth2LoginSpec` is designed to not redirect on XHR requests but this behavior breaks that contract.

This cannot be worked around by configuring a new default entry point (e.g., `.exceptionHandling().authenticationEntryPoint(...)`) because doing so triggers another bug, which I'll open another issue about.

**To Reproduce**

The issue is reproducible most easily with OAuth2 login. However, the problem is not unique to this scenario. 

1. Configure Spring WebFlux security with OAuth2 login

```java
@Configuration
@EnableWebFluxSecurity
public class SecurityConfig
{
    @Bean
    public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http)
    {
        return http
                .authorizeExchange(exchanges -> exchanges.anyExchange().authenticated())
                .oauth2Login()
                .and()
                .build();
    }
}
```

https://github.com/foo4u/spring-security-bugs/blob/38ba4cd007eb3a7d75f5912f5a013b7ee4ac197d/src/main/java/com/example/demo/SecurityConfig.java#L9-L22

2. Make an XHR request to an endpoint requiring authentication with XHR headers expecting an HTTP 401.

```java
	@Test
	void respondsWithHttp401()
	{
		client
				.get()
				.accept(MediaType.APPLICATION_JSON)
				.header("X-Requested-With","XMLHttpRequest")
				.exchange()
				.expectStatus()
				.isUnauthorized();
	}
```

https://github.com/foo4u/spring-security-bugs/blob/38ba4cd007eb3a7d75f5912f5a013b7ee4ac197d/src/test/java/com/example/demo/DemoApplicationTests.java#L27-L37

3. Note a 302 redirect to the login provider is sent as the response instead of a 401.

    [ERROR] Failures:
    [ERROR]   DemoApplicationTests.respondsWithHttp401:36 Status expected:<401 UNAUTHORIZED> but was:<302 FOUND>

**Expected behavior**

The web filter chain should return an HTTP 401, not redirect.

**Sample**

[GitHub repository with minimal, reproducible sample](https://github.com/foo4u/spring-security-bugs/tree/spring-security-webflux-default-entry-point-bug).

Two ways to reproduce with sample:
1. Run the test suite
2. Start the server and cURL any endpoint

**Comment by pszemus** [comment]
I took me 2 days to track this problem and finally find this issue, so +1 from me.

**Comment by jgrandja** [comment]
@foo4u The test you provided `respondsWithHttp401()` is not the correct behaviour.

When `oauth2Login()` is configured, unauthenticated XHR requests will be redirected to the default login page `/login`. See this [test](https://github.com/spring-projects/spring-security/blob/7ef3f619242816683a72b35a1f8b4fb4f32d5203/config/src/test/java/org/springframework/security/config/web/server/OAuth2LoginTests.java#L181) for the expected behaviour.

**NOTE:** To be clear, the redirect is to the default login page in the client application NOT the login page of the external provider.

Can you provide another test that demonstrates if this is a bug?

**Comment by foo4u** [comment]
@jgrandja why would you intentionally redirect XHR requests to the login page? Also, the test case you mentioned doing a 3XX redirect only "works" as a side effect of this bug.

The code in `OAuth2LoginSpec` specifically attempts to return a 401: 

https://github.com/spring-projects/spring-security/blob/8cefc8a792dab5bfef7dc698cf44c7c2bb909d54/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java#L3274-L3312

**Comment by jgrandja** [comment]
@foo4u I looked into this further and my [comment](https://github.com/spring-projects/spring-security/issues/9266#issuecomment-755427010) still holds.

To further support the expected behaviour in `OAuth2LoginSpec.setDefaultEntryPoints()`, these tests pass:


```java
@Test
void xhrRequestThenRedirectToDefaultLogin()
{
	client
			.get()
			.accept(MediaType.APPLICATION_JSON)
			.header("X-Requested-With","XMLHttpRequest")
			.exchange()
			.expectStatus()
			.is3xxRedirection()
			.expectHeader().location("/login");
	// NOTE:
	// It does not trigger the authorization request redirect -> '/oauth2/authorization/smartling'
	// This is the expected behaviour configured in setDefaultEntryPoints()
}

@Test
void notXhrRequestThenRedirectToProviderLogin()
{
	client
			.get()
			.exchange()
			.expectStatus()
			.is3xxRedirection()
			.expectHeader().location("/oauth2/authorization/smartling");
}
```

Does this make sense? If not, please provide additional tests to demonstrate because `respondsWithHttp401()` is not the expected behaviour.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by pszemus** [comment]
But why would anyone expect a redirect as a response to an unauthorized XHR request? I thought that a default spring-security response since #3887 is 401 Unauthorized. If so, why this behaviour was it changed for oauth2?

**Comment by foo4u** [comment]
@jgrandja, as I mentioned previously, the test case is incorrect. I'm not sure why you're fixated on this test passing. It makes zero sense to send a redirect on an XHR request.

I'll attempt to send another code sample clarifying the problem

**Comment by everflux** [comment]
@jgrandja could you look into this? Since XHR is triggered by a browser application a 3xx has to be handled in code, since the result page will not be presented to a user. Hard to distinguish form a valid redirect after creating a resource.

**Comment by jgrandja** [comment]
@foo4u 

> I'll attempt to send another code sample clarifying the problem.

I still have not received a code sample clarifying the problem.

To further clarify:

> the test case is incorrect. I'm not sure why you're fixated on this test passing. It makes zero sense to send a redirect on an XHR request.

If you're not already aware, the [OAuth 2.0 Authorization Code grant](https://tools.ietf.org/html/rfc6749#section-4.1) is **redirection-based flow**:

> The authorization code grant type is used to obtain both access
   tokens and refresh tokens and is optimized for confidential clients.
   Since **this is a redirection-based flow, the client must be capable of
   interacting with the resource owner's user-agent (typically a web
   browser) and capable of receiving incoming requests (via redirection)
   from the authorization server**.

`oauth2Login()` is implemented with the OAuth 2.0 Authorization Code grant flow. Therefore, the authentication flow should be handled by the browser agent **NOT the XHR client**.

The comments and explanation you provided in this issue is related to `oauth2Login()` and **the usage is incorrect**. You should not use XHR to authenticate via `oauth2Login()`. Furthermore, if the user is not authenticated and an XHR request is issued than `302` is the expected behaviour if only `oauth2Login()` is configured as the authentication mechanism.

In a typical SPA (or XHR/JS) application that has `oauth2Login()` configured for authentication, the authentication flow is triggered at the start allowing the browser agent to handle it. After authentication completes, the SPA (or XHR/JS) code is loaded and continues from there.

If you still feel there is an issue that is NOT related to `oauth2Login()`, then please provide a minimal sample that reproduces the issue. Otherwise, I'll close this issue.

**Comment by candrews** [comment]
I agree with the reporter of this issue. XHR should not trigger a redirect to login

> Since **this is a redirection-based flow, the client must be capable of interacting with the resource owner's user-agent (typically a web browser) and capable of receiving incoming requests (via redirection) from the authorization server**.

XHR requests are not capable of interacting with the user, therefore they should result in immediate denial (not redirect) if unauthorized.

And, that's how Spring Security already works for every method _except_ OAuth2; see https://github.com/spring-projects/spring-security/issues/3887

IMHO, Spring Security OAuth2 Client should behave the same as the rest of Spring Security. So either Spring Security should change (undoing https://github.com/spring-projects/spring-security/issues/3887) or Spring Security OAuth2 Client should change.

**Comment by jgrandja** [comment]
@foo4u I put together some tests that demonstrate the correct behaviour depending on the authentication configured in the application, e.g. `httpBasic()`, `formLogin()` and `oauth2Login()`.

I did find an issue with one of the tests that should pass. Can you take a look at this [test](https://github.com/jgrandja/spring-security/commit/befd50a65540647115692d8b5882f5892dae3f9e#diff-59afda4a9a98e1db76735b450ee63940b1974b7ecbdd29668cf77d5743aeba26R122) and let me know if this is the same issue you are experiencing?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by jgrandja** [comment]
@foo4u I'm closing this since I haven't received a minimal sample reproducing the issue.

However, I believe this issue is fixed via gh-9660.

I also added a few tests (53e94bc) demonstrating the expected behaviour.
