### ISSUE TITLE
Retrieving user profile from facebook fails, if **Require App Secret** is enabled in facebook.

### ISSUE THREAD

**Issue by rajsenthil** [spring-projects/spring-security#9292]
**Describe the bug**
The user is getting successfully authenticated. The retrieval of profile fails and getting 
```
[invalid_user_info_response]
 An error occurred while attempting to retrieve the UserInfo Resource

```

**To Reproduce**
I am using spring-boot 2.3.7.RELEASE with spring-boot-starter-oauth2-client. 
The oauth2 for facebook is configured with 

> clientId
> clientSecret
> provider.facebook.user-info-uri with https://graph.facebook.com/me?fields=id,name,email,picture
In the developers.facebook.com, under the application **advanced setting** for **security**, enable the property **Require App Secret**

When it is enabled the exception 
```
[invalid_user_info_response]
 An error occurred while attempting to retrieve the UserInfo Resource
```
is thrown. Once it is disabled, it works as expected.

**Expected behavior**

**Sample**

There is another user posted the same issue on [stackoverflow](https://stackoverflow.com/questions/64540494/spring-security-oauth2-supporting-facebook-appsecret-proof). Please check.

**Comment by jzheaux** [comment]
Thanks for the report, @rajsenthil. I've responded to the StackOverflow question and will keep track of it. 

Also, Spring Security's Facebook example appears to work, so maybe the question needs more detail to find what's not working.

Since I've responded on the StackOverflow question, I'm going to close this issue. However, if this turns out to be a bug, we can reopen.
