### ISSUE TITLE
spring-security-saml2-service-provider dependency on spring-boot-starter-web while using spring-cloud-gateway

### ISSUE THREAD

**Issue by aabuniaj** [spring-projects/spring-security#9347]
Question

I'm currently implementing an API Gateway authenticating using spring-security-saml2-service-provider. Looks like that Saml2 dependency is dependent on spring-boot-starter-web and I know spring-cloud-gateway is not compatible with it.

When removing the spring-boot-starter-web dependency, I receive the following:
Consider defining a bean of type 'org.springframework.security.saml2.provider.service.registration.RelyingPartyRegistrationRepository' in your configuration.

Bug report

Spring Boot 2.4.1
spring-cloud 2020.0.0

**Comment by aabuniaj** [comment]
Any comments on this please?

**Comment by jzheaux** [comment]
Hi, @aabuniaj, thanks for the report. Spring Security's SAML support is not dependent on any Spring Boot projects as can be seen in [its build file](https://github.com/spring-projects/spring-security/blob/master/saml2/saml2-service-provider/spring-security-saml2-service-provider.gradle).

Spring Cloud Gateway and Spring Security's SAML are incompatible since one is reactive (Gateway) while the other is imperative (SAML). There either needs to be [reactive SAML support](https://github.com/spring-projects/spring-security/issues/7954) or [a servlet-based gateway](https://github.com/spring-cloud/spring-cloud-gateway/issues/36) to use them together.
