### ISSUE TITLE
how to use one project access token in another project in spring boot

### ISSUE THREAD

**Issue by hameedriswan7** [spring-projects/spring-security#9422]
Hi,

I need some assist in authentication. let me explain my query.

user registration and login and some other stuffs are integrated  in one project. Now I need to create another spring boot project implement some other logic for that already created user for that I need to secure my API using Authorization. 

So how can I use token from one project Login api and use in newly created spring boot project?

**Comment by jzheaux** [comment]
Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
