### ISSUE TITLE
Cannot unsecure actuator endpoints when using WebFlux

### ISSUE THREAD

**Issue by adenix** [spring-projects/spring-security#9476]
**Describe the bug**
When using Spring Security with WebFlux, /actuator can be unsecured but all other actuator endpoints cannot. The sample code below shows `/actuator` and `/actuator/info` being configured with `.permitAll()`. The former allows anonymous traffic but the latter returns 401 Unauthorized. This issues does not happen when using a servlet web app.

**To Reproduce**
1. Create a new Spring Boot project using WebFlux, Actuator, and Spring Security
2. Attempt to remove security from actuator endpoints other than the root `/actuator`
 
**Expected behavior**
Endpoints defined as `.permitAll()` without an overriding definition should allow anonymous access.

**Sample**
[Demo Project](https://github.com/adenix/Reactive-Security-Bug)
[Reactive Security Bug.postman_collection.json.txt](https://github.com/spring-projects/spring-security/files/6052514/Reactive.Security.Bug.postman_collection.json.txt)

```java
@Configuration
@EnableWebFluxSecurity
@RequiredArgsConstructor
public class SecurityConfiguration {

  private final ReactiveAuthenticationManager authenticationManager;
  private final ServerSecurityContextRepository securityContextRepository;

  @Bean
  public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {

    http
        .csrf().disable()
        .formLogin().disable()
        .httpBasic().disable();

    http
        .authorizeExchange()
        .pathMatchers(HttpMethod.GET, "/actuator", "/actuator/info", "/demo").permitAll()
        .anyExchange().authenticated();

    http
        .authenticationManager(authenticationManager)
        .securityContextRepository(securityContextRepository);

    return http.build();
  }
}
```

**Comment by adenix** [comment]
Adding debug logs for `org.springframework.security`

```javascript
[
  {
    "@timestamp": "2021-02-26T15:06:51.131-05:00",
    "message": "Trying to match using PathMatcherServerWebExchangeMatcher{pattern='/logout', method=POST}",
    "logger_name": "org.springframework.security.web.server.util.matcher.OrServerWebExchangeMatcher",
    "thread_name": "boundedElastic-1",
    "level": "DEBUG"
  },
  {
    "@timestamp": "2021-02-26T15:06:51.132-05:00",
    "message": "Request 'GET /actuator/info' doesn't match 'POST /logout'",
    "logger_name": "org.springframework.security.web.server.util.matcher.PathPatternParserServerWebExchangeMatcher",
    "thread_name": "boundedElastic-1",
    "level": "DEBUG"
  },
  {
    "@timestamp": "2021-02-26T15:06:51.132-05:00",
    "message": "No matches found",
    "logger_name": "org.springframework.security.web.server.util.matcher.OrServerWebExchangeMatcher",
    "thread_name": "boundedElastic-1",
    "level": "DEBUG"
  },
  {
    "@timestamp": "2021-02-26T15:06:51.132-05:00",
    "message": "Trying to match using PathMatcherServerWebExchangeMatcher{pattern='/actuator', method=GET}",
    "logger_name": "org.springframework.security.web.server.util.matcher.OrServerWebExchangeMatcher",
    "thread_name": "boundedElastic-1",
    "level": "DEBUG"
  },
  {
    "@timestamp": "2021-02-26T15:06:51.133-05:00",
    "message": "Request 'GET /actuator/info' doesn't match 'GET /actuator'",
    "logger_name": "org.springframework.security.web.server.util.matcher.PathPatternParserServerWebExchangeMatcher",
    "thread_name": "boundedElastic-1",
    "level": "DEBUG"
  },
  {
    "@timestamp": "2021-02-26T15:06:51.133-05:00",
    "message": "Trying to match using PathMatcherServerWebExchangeMatcher{pattern='/actuator/info', method=GET}",
    "logger_name": "org.springframework.security.web.server.util.matcher.OrServerWebExchangeMatcher",
    "thread_name": "boundedElastic-1",
    "level": "DEBUG"
  },
  {
    "@timestamp": "2021-02-26T15:06:51.133-05:00",
    "message": "Checking match of request : '/actuator/info'; against '/actuator/info'",
    "logger_name": "org.springframework.security.web.server.util.matcher.PathPatternParserServerWebExchangeMatcher",
    "thread_name": "boundedElastic-1",
    "level": "DEBUG"
  },
  {
    "@timestamp": "2021-02-26T15:06:51.134-05:00",
    "message": "matched",
    "logger_name": "org.springframework.security.web.server.util.matcher.OrServerWebExchangeMatcher",
    "thread_name": "boundedElastic-1",
    "level": "DEBUG"
  },
  {
    "@timestamp": "2021-02-26T15:06:51.134-05:00",
    "message": "Checking authorization on '/actuator/info' using org.springframework.security.config.web.server.ServerHttpSecurity$AuthorizeExchangeSpec$Access$$Lambda$1415/0x000000080084fc40@3fdac2d9",
    "logger_name": "org.springframework.security.web.server.authorization.DelegatingReactiveAuthorizationManager",
    "thread_name": "boundedElastic-1",
    "level": "DEBUG"
  },
  {
    "@timestamp": "2021-02-26T15:06:51.134-05:00",
    "message": "Authorization successful",
    "logger_name": "org.springframework.security.web.server.authorization.AuthorizationWebFilter",
    "thread_name": "boundedElastic-1",
    "level": "DEBUG"
  }
]
```

**Comment by jzheaux** [comment]
What's interesting to me is that in your `DemoSecurityContextRepository`, you are making an authorization decision. Since that repository always errors when no `X-Principal` header is supplied, I'd expect all the public endpoints to fail in this case, not just `actuator/info`.

I think there are two things to address:

First, I'm wondering if it's correct for the filter chain to continue when `ServerSecurityContextRepository` implementations resolve to `Mono.error`. It seems like they should propagate the error at that point. I'll leave this ticket open to continue investigating that.

Second, it's better to have `AuthorizationWebFilter` to make your authorization decisions instead of the security context repository. I'd recommend returning `Mono.empty()` if you can't find a security context instead of returning `Mono.error(UnauthorizedException::new)`.

or

Instead of having a custom security context repository, it's much more common for a custom web filter to use an authentication manager than a custom security context repository. Instead of a custom security context repository, consider:

```java
public class XPrincipalAuthenticationConverter implements ServerAuthenticationConverter {
    Mono<Authentication> converter(ServerWebExchange swe) {
        ServerHttpRequest request = swe.getRequest();
    
        String principal = request.getHeaders().getFirst("X-Principal");
    
        if (principal != null) {
          return Mono.just(new UsernamePasswordAuthenticationToken(principal, principal));
        } else {
          return Mono.empty(); // no error, let the authorization filter take care of authorization decisions
        }
    }
}
```

and then instead of `.securityContextRepository(securityContextRepository)`, do:

```
AuthenticationWebFilter xPrincipalFilter = new AuthenticationWebFilter(authenticationManager);
xPrincipalFilter.setServerAuthenticationConverter(authenticationConverter);

// ...

http.addFilterAt(xPrincipalFilter, SecurityWebFiltersOrder.AUTHENTICATION);
```

**Comment by rwinch** [comment]
The `SecurityContextRepository` is not the proper API to perform authentication. Instead, use `AuthenticationWebFilter`.

If you really want to use `SecurityContextRepository`, @jzheaux is correct. you should not return `Mono.error` if the `SecurityContext` is not found. Instead you should return `Mono.empty`.

The reason this does not impact `/demo` is because it never subscribes to the `SecurityContext`. The `/actuator/info` attempts to include the authenticated user in the response and so the `SecurityContext` is subscribed to. When it isn't found it produces the error and it is handled by returning the 401 response.
