### ISSUE TITLE
Looking for a way to use configured redirect url over cached

### ISSUE THREAD

**Issue by zahiritpro** [spring-projects/spring-security#9490]
OAuth2AuthorizationCodeGrantFilter gives precedence to the cached redirect url over configured one.

This fails Use cases where all the redirects have to happen via a particular endpoint. Please review.

https://github.com/spring-projects/spring-security/blob/92b3a7b01bfd2fb44de0f92b41d91740dd25f52e/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/OAuth2AuthorizationCodeGrantFilter.java#L242-L246

**Comment by jgrandja** [comment]
@zahiritpro Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
