### ISSUE TITLE
UsernamePasswordAuthenticationFilter It supports retrieving the username password from the body

### ISSUE THREAD

**Issue by ChenZheOnePiece** [spring-projects/spring-security#9533]
In order to get the username password from the body, I have to customize a filter, but all the logic is the same as it. I wonder if obtainusername can support the body, so I don't need to write another filter

**Comment by bensiegler** [comment]
If i'm not mistaken, the obtainUsername() and obtainPassword() methods in the UsernamePasswordAuthenticationFilter already pull information from the request body. If you have a different implementation of HttpServletRequest this may be different since the two aforementioned methods call getParameter() on HttpServletRequest.

**Comment by jzheaux** [comment]
@ChenZheOnePiece thanks for the question. Could you elaborate more on what you are trying to do?

What I'm not understanding is this:

> In order to get the username password from the body, I have to customize a filter

`UsernamePasswordAuthenticationFilter` reads the body by default, so what is it that you are customizing?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
