### ISSUE TITLE
Document Jwt Client Authentication support

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#9578]
Document Jwt Client Authentication support in the reference.

Issue gh-9520

**Comment by siren** [comment]
Thank you @jgrandja for your efforts in adding jwt client authentication support to spring security! I am currently trying to test the private_key_jwt method with 3rd party provider within a spring boot app but I am failing to see how would I set it up properly. I already looked at the test cases you mentioned in gh-9520 but since this is new stuff for me I am still puzzled.  

Can you share a working example code/configuration that I could mimic?

**Comment by jgrandja** [comment]
@siren I'm planning on putting together a sample along with the documentation. I'm planning on getting to this later next week.

**Comment by Giambapisasale** [comment]
Hi,
I'm looking for a working example of private_key_jwt with client_crendentials, but I can't find the version with ServerOAuth2AuthorizedClientExchangeFilterFunction (no ServletContext), but only with OAuth2ClientCredentialsGrantRequestEntityConverter in a ServletContext.
Can you add a working example please?
thanks
