### ISSUE TITLE
Getting response committed when writing to response.getWriter/getOutputStream

### ISSUE THREAD

**Issue by nwbkhan** [spring-projects/spring-security#9652]
**Describe the bug**
I have declared a filter and using spring-security. I noticed that when forwarding request to new ServletDispatcher (forward declared inside HandlerInterceptor), i see response committed when sysout inside Filter , but if i do direct RequestMapping call i see response is not committed in the Filter.

**To Reproduce**
Try to add simple HandlerInterceptor, and do **sysout before doFilter and after it**, calling direct request mapping has correct scenario but calling with **servletDsiapatcher.forward** and doing operation inside controller (responseServlet.getWriter().print()) makes it Committed.

**Expected behaviour**
Should not get response as committed for forward case.

Let me know if if thats how it used to be, I spent 8 hours to investigate what can be done, I am running problem with ShallowETagFilter from Spring, and in controller i am doing responseServlet.getWriter().print(). response get committed after this.

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
