### ISSUE TITLE
Active Directory authentication failed: Supplied password was

### ISSUE THREAD

**Issue by waytoharish** [spring-projects/spring-security#9655]
Hi Team,
I am always getting below error when trying to connect with ldap server-
error is on the below line -
 return new InitialLdapContext(env, null);

Below is my configuration for bind user-

  private DirContext bindAsUser(String username, String password) {
        // TODO. add DNS lookup based on domain
        final String bindUrl = url;
         Hashtable<String, String> env = new Hashtable<String, String>();
        env.put(Context.SECURITY_AUTHENTICATION, "simple");
        String bindPrincipal = createBindPrincipal(username);
      //  env.put(Context.SECURITY_PRINCIPAL, bindPrincipal);
        env.put(Context.SECURITY_PRINCIPAL, "ServerName\\" + username);
        env.put(Context.PROVIDER_URL, bindUrl);
        env.put(Context.SECURITY_CREDENTIALS, password);
        env.put(Context.INITIAL_CONTEXT_FACTORY, "com.sun.jndi.ldap.LdapCtxFactory");
        env.put(Context.OBJECT_FACTORIES, DefaultDirObjectFactory.class.getName());

        try {
            return contextFactory.createContext(env);
        }
        catch (NamingException e) {
            if ((e instanceof AuthenticationException)
                    || (e instanceof OperationNotSupportedException)) {
                handleBindException(bindPrincipal, e);
                throw badCredentials(e);
            }
            else {
                throw LdapUtils.convertLdapException(e);
            }
        }
    }

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
