### ISSUE TITLE
SAML2Login in Grails without using Spring Boot

### ISSUE THREAD

**Issue by sandhya0107** [spring-projects/spring-security#9657]
We have received blackduck security vulnerability for Apache Client 3.1 which is a transitive dependency of org.springframework.security.extensions1.0.10.RELEASE

To resolve above issue we need to migrate from spring security extensions to https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-saml2

Can any one suggest how to use https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-saml2 in Grails without using Spring boot.

**Comment by jzheaux** [comment]
Hi, @sandhya0107, thanks for reaching out!

Please see the Spring Security Reference section about [SAML 2.0 Login without Spring Boot](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-saml2login-sansboot).

In the future, this feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). If you feel like there's more to discuss, please post your question to Stack Overflow and post that link here in the ticket so that others can find it.

**Comment by sandhya0107** [comment]
Thank you for the reply.

**Comment by sandhya0107** [comment]
@jzheaux Could you please check https://stackoverflow.com/questions/67228136/saml2login-with-grails-spring-security-core
