### ISSUE TITLE
saml2-service-provider: OpenSaml4AuthenticationProvider has Java 11 bytecode

### ISSUE THREAD

**Issue by handcraftedbits** [spring-projects/spring-security#9731]
**Describe the bug**
In contrast to the rest of the classes in `spring-security-saml2-service-provider-5.5.0*.jar`, `OpenSaml4AuthenticationProvider` and `OpenSaml4AuthenticationRequestFactory` contain Java 11 bytecode.  These classes are the replacement for `OpenSamlAuthenticationProvider` and `OpenSamlAuthenticationRequestFactory`, but users on JVMs < 11 can't use them.

**To Reproduce**
Attempt to use one of the listed classes on a JVM < 11.

**Expected behavior**
These classes should be usable on Java 8 JVMs since everything else in the library is.

**Comment by eleftherias** [comment]
Hi @handcraftedbits, Spring Security's runtime baseline is JDK 8, and it remains that way. However since OpenSAML 4's runtime baseline is JDK 11, an application that uses OpenSAML 4 will need to run with JDK 11.

See gh-9095 for more details and specifically [this comment](https://github.com/spring-projects/spring-security/issues/9095#issuecomment-809514402).
