### ISSUE TITLE
IdP SingleSignOnService Binding overridden to REDIRECT

### ISSUE THREAD

**Issue by darrenpm** [spring-projects/spring-security#9744]
**Describe the bug**
Binding value of POST provided in IdP metadata overridden by default value of REDIRECT

**To Reproduce**
Configure IdP via metadata, containing either:
 - a single SingleSignOnService
 - multiple SingleSignOnService, with POST being first

`<md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://path/to/sso/url" /> `

**Expected behavior**
Auth requests should be done via HTTP POST, but the default of REDIRECT in registration properties overrides the metadata value.
See Saml2RelyingPartyRegistrationConfiguration.mapIdentityProvider() when no IdP properties are set, other than the metadata location.

Note: it is possible to workaround by adding a property to set the binding to POST, but that shouldn't be necessary.

**Comment by jzheaux** [comment]
Hi, @darrenpm, thanks for the report. I agree that the metadata binding value should take precedence when an application does not specify a binding value property.

Since `Saml2RelyingPartyRegistrationConfiguration` is a Spring Boot file, I think it would be best if this issue were filed in [the Spring Boot project](https://github.com/spring-projects/spring-boot/issues). Would you mind reporting it there, please?

**Comment by darrenpm** [comment]
Sure: https://github.com/spring-projects/spring-boot/issues/26454
