### ISSUE TITLE
Working samples link for both JWTs and Opaque Tokens are returning 404

### ISSUE THREAD

**Issue by driptaroop** [spring-projects/spring-security#9842]
**Describe the bug**
In the spring security documentation (https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver) , the links to samples of JWT and opeque token is not working with 404
![Screenshot 2021-06-01 at 10 07 12](https://user-images.githubusercontent.com/9862551/120289031-25960f00-c2c1-11eb-8e9c-929cac594e0f.png)

**To Reproduce**
Go here: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver and click the link to the samples of jWT and Opeque token

**Expected behavior**
The link should redirect to the github repo with the samples. Either the repo path is wrong in the link or the repo permission is not setup correctly.

**Sample**

NA

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by tekgainers** [comment]
Team, same issue is for each sample.

**Comment by marcusdacoregio** [comment]
Hi @driptaroop, thank you for the report. 
The Spring Security samples have been moved to a [new project](https://github.com/spring-projects/spring-security-samples) since the version **5.5.x**.
You can still find the not migrated samples in an [older branch of Spring Security](https://github.com/spring-projects/spring-security/tree/5.4.x/samples).
The documentation is being updated to reflect that. We are addressing this in #9784.

I'm closing this issue but feel free to discuss here.
