### ISSUE TITLE
JwtDecoders fails if Json Web Key comes without algorithm

### ISSUE THREAD

**Issue by GabrielBB** [spring-projects/spring-security#9926]
In `2.4.7` we do: `JwtDecoders.fromOidcIssuerLocation(auth0Properties.issuer) as NimbusJwtDecoder` with an issuer that returns a JWKS without `alg` properties, which [should be fine](https://datatracker.ietf.org/doc/html/rfc7517#section-4.4) since is an optional property. However when we upgrade to `2.5.x` we get an error: `java.lang.IllegalArgumentException: Failed to find any algorithms from the JWK set`

**Comment by jzheaux** [comment]
Thanks for the report, @GabrielBB. I agree that the code should not require `alg` to be set.

However, there might be more going on here. The code has a test to confirm that [`alg` is not required](https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/JwtDecoderProviderConfigurationUtilsTests.java#L67).

JWKs need to have a `kty`. The code first checks if an `alg` is set, and If not, then it uses the `kty` to decide a set of algorithms. It makes me wonder what the `kty` attribute is for each of your JWKs.

Are you able to share a sample that reproduces the issue?

**Comment by GabrielBB** [comment]
> Thanks for the report, @GabrielBB. I agree that the code should not require `alg` to be set.
> 
> However, there might be more going on here. The code has a test to confirm that [`alg` is not required](https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/JwtDecoderProviderConfigurationUtilsTests.java#L67).
> 
> JWKs need to have a `kty`. The code first checks if an `alg` is set, and If not, then it uses the `kty` to decide a set of algorithms. It makes me wonder what the `kty` attribute is for each of your JWKs.
> 
> Are you able to share a sample that reproduces the issue?


@jzheaux Thanks for quick response. This is our JWKS:

`{
  "keys": [
    {
      "p": "8haNBWQZEpBxn6IGXoX6UKN8fMEIwhfVV4mOAx6go2OjpE-EVLNEOof_PhKDhFfK9DPxlmxaFB1F2lez8D2HHZnt_3N35Wsjxv9WnI8l0bPoHZck-C_BNRxueJlZG4CUOvroviY3iB8lhKgbTR8EFihMQ4LNWKR1qpERBCyU4dU",
      "kty": "RSA",
      "q": "2SZdELqxxR0XqDXJe6UWl7-HjDvfgzZQk0WbCmL2FzP_dhGj3ikneD7MYZe8d1qp0FhHV2NxX3xeqJmAFAO_lnrU89uZy4ikIxzgEFsoslB7Dn27_pJql8WmQkB_oofWUEW9atXAZvC7n7gz3PG7vFwtuxDTt1VG1LzS7s6JTgs",
      "d": "hSA6J2dM-M9Vt4iKKuBcvgbGUxpsf6ZFuBsvN0B1dH45CoXsMfcoRZbtHSoM648cP4Kux01UD4ja6gmJeJLUgLrxg8sw3oZ4z9sYPojpgKCKvUS11ZPSMIQaNIdDON2MYJTFe0m6_iW6uka2NYmzChfdG3tLOwM3hiRh8v6OMLSwfhyv4V_P-lWE5oJ-tzWQavppxlOdWabaQymvj8rjma_oipsTmTAmDlx6jxe5s70uaQPYtZZlfJi59Qf9UqEIetXjPXM8k2KSbrRGsR_CZfZ4NlcGFYbYpcucUVNfJodokwUGwKu_j-JJNbUa9V9rTMMFr0oUM3w7_X-WrcLzeQ",
      "e": "AQAB",
      "kid": "my_favorite_key",
      "qi": "tJjQm6CBEwdCVkblai8W-0c_Ynej_AzrRFKb6rd9rLd8pDemLwKdt0SNPBRHQ_gDAW1q5f8vAvUkdIbJD4zqfKtiqM9_-Z2Pb45r5Vv3-H6PHRyFhQAbE0u7S-mFV_Nc7YReOAX2xlEGZm1RPMNa0jzbo3h6Kg9ZLKdL7EYaWAA",
      "dp": "eQnbYkmk24pKtRSueI4mFDFZaYqeFWUTLtxAm8Cxcl-8DsgPEsY6o8UhUeixxvaaK7TY4mu0MgBcz4kwFzq8FonC3Ajgdl02GyXJKSfNMebwc_MA8fH2eNaJSVTqn3yPIFoZChFTjIR-HrBqTgnm4ikt0EdS4jH__tLfHiYoHi0",
      "dq": "FXesda3vSyxgHVoL7DRa8m-V5_A3XZJuDtEvzawQ5iRW2gZOa_UnmMSkkfVdRXNqHFXN377OA4GZHhPmzJO-ShMkoGMSZkPA7lO5dwR8FnzMXZdikX1KGm0Izb3woFHLhy4N1tUA62xbMCQWxH4FcE6wmrDELXi5wuhT9hXnDxc",
      "n": "zVlk5IPWYJzX93UjMNCSblJYSHQeWzRmG7XJlNrYhX8HtgCPBH8-yGk-TxWBS84uWdT02-cTQZqPPZN0uu7XF1IlN5absaRfyxi_Ls5YWnDseHrjWeDfHAmuXCkwHQXYmEe24F45-bOp7wFMYplAt59lez1Gu9Na7-TED9Z0x4MsARVieu41IFKVbpGyIkVLzwaL08riDpNcj_QyT-NhSB4IuOVtPhD84rt1BuRJr7CVIRY3Eh9nTWYaoSZXVif_sVVCTClmthyz0sGqRDnesPipqUXnS29HjrvKQF3SUdhBKsle-c1ofTiSINoW3Y3SYtIct6vnrmXOnVgviDGaJw"
    }
  ]
}`

**Comment by jzheaux** [comment]
@GabrielBB, your payload contains elements necessary to reformulate the associated private key, which is why it's not included in the list of potential keys. It would be safer for it to [only contain the public key elements](https://datatracker.ietf.org/doc/html/rfc7517#section-9.2).

Because it contains private key elements, I've deleted your comment just in case it's a production key. I'm not sure if deleting the comment makes the details unfindable.

Are you able to adjust the endpoint so it only returns the public key elements?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by GabrielBB** [comment]
> @GabrielBB, your payload contains elements necessary to reformulate the associated private key, which is why it's not included in the list of potential keys. It would be safer for it to [only contain the public key elements](https://datatracker.ietf.org/doc/html/rfc7517#section-9.2).
> 
> Because it contains private key elements, I've deleted your comment just in case it's a production key. I'm not sure if deleting the comment makes the details unfindable.
> 
> Are you able to adjust the endpoint so it only returns the public key elements?

@jzheaux Working after using only public key elements. Thanks

**Comment by jzheaux** [comment]
5.5 adds an additional HTTP request - if you are using `MockWebServer` to test `JwtDecoders`, you will need to configure it for both the OIDC discovery and JWK set requests.

Or, you might consider publishing a `@MockBean` of `JwtDecoder` and Spring Security will pick that up during your tests. This would help so that your tests aren't so reliant on Spring Security internals. Or, you could mock `JwtDecoders.fromIssuerLocation`.

It feels like this is moving a bit into a question instead of a bug report, so I'm going to close the issue. If you can identify a way that Spring Security functionality is broken, please feel free to re-open with additional details. If you'd like to look more deeply into integration testing with Spring Security, please feel free to post a separate StackOverflow question, and I'd be happy to take a look with you.
