### ISSUE TITLE
please support lazily doing issuer checks (and all other checks) on startup for oauth resource servers

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-security#9991]
right now the app is slowed a bit by HTTP checks it has to make when the app startsup. other implementations do a lot of these HTTP requests lazily, on the first use. this means that developers don't have to pay the sometimes significant cost of making the HTTP request to slow providers unless they trigger a request that needs it for their dev iteration cycle

**Comment by jzheaux** [comment]
Hey, @joshlong! 

The following setup is the preferred way to defer HTTP calls on startup:

```yaml
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://authz.example.org/jwks
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://authz.example.org
```

If the `jwk-set-uri` property is present, then Spring Security will do checks lazily. This is because it relies on Nimbus, which operates lazily.

Here is a sample where [these two properties point to an intentionally slow endpoint](https://github.com/jzheaux/spring-security-samples/tree/gh-9991/servlet/spring-boot/java/oauth2/resource-server/hello-security). The endpoint is configured to take 30 seconds to reply; however, the app still starts up in less than 2 seconds. This implies that no HTTP requests are getting made when the sample starts up.

Using that sample, you can try the following:

```bash
export TOKEN="eyJraWQiOiJjOWEyMzIxYy01N2NmLTQ1YmYtOWIzYS1kYjdjYzk3ODkwZTEiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoiZ29hbHMtY2xpZW50IiwibmJmIjoxNjI0OTk1ODMwLCJzY29wZSI6WyJnb2FsOnJlYWQiLCJ1c2VyOnJlYWQiLCJnb2FsOndyaXRlIl0sImlzcyI6Imh0dHBzOlwvXC9vYXV0aDIucHJvdmlkZXIuY29tIiwiZXhwIjoxNjI0OTk5NDMwLCJpYXQiOjE2MjQ5OTU4MzAsImp0aSI6IjM5OWIzMWUxLWZlNDItNDQwNS1iYjY0LWVkYmY5YTQ1M2I4ZSJ9.Z8Jy3JhFDK7Ijv9IWT9taLTbXXiXw8Eb0ZO2mD4pRFVLODYfAXLpt-fx5j9ZiApsrejj0pvyCBXOnjsroG8spZmSEHNlUO4_eVlrBtuB3pF54E7jDF6CrnS5nP2u5CSfsXAPoXqzcxHyghQ-n0vtaKhuCbgpVUyV6w5Gye7JrQa-Sj7eIPv4CfumC9vbphrnjVOlQvF_i7qJnp4cnDFM5AuGPkzdmOy_7nTwaYgXczyp4_2Qr4qPhju38g-GK-6S2YtPSmy5tgLGoMgllRU5elVmHZ5jddZAmnVu4couNM9jDxfIU3g3cfGiVSDVdXoqR3E2mpLuHn45Ml2mkmNl5g"

http :8080 "Authorization: Bearer $TOKEN"
```

and the request will timeout, having taken 30 seconds to get a reply from the JWKS endpoint.

I remember that you and Matt Raible were experiencing something different, though, where startup seemed to be different based on internet speeds. Can you share a sample that is making those HTTP calls on startup and we can take a look?

**Comment by mraible** [comment]
Hello, @jzheaux! 

I published a [blog post](https://developer.okta.com/blog/2021/06/18/native-java-framework-comparison) with my findings on the Okta developer blog. See the [build native images](https://developer.okta.com/blog/2021/06/18/native-java-framework-comparison#build-native-images-for-micronaut-quarkus-and-spring-boot) section to see how to build each example and run it. It also explains what we found.

You can find all the code in https://github.com/oktadev/native-java-examples.

**Comment by jzheaux** [comment]
Hi, @mraible, @joshlong. I noticed something in [Matt's blog post](https://developer.okta.com/blog/2021/06/18/native-java-framework-comparison) that I didn't before. I want to make sure that this ticket is resolving the issue you identified, and the way I read it this afternoon made me think that there might be more to discuss.

It says:

> Our hypothesis is Micronaut and Quarkus do the JWKS lookup on the first request rather than at startup. That’s how they achieve faster startup times.

I think there's more to this since Micronaut, Quarkus, and Boot all three already [do the JWKS lookup on the first request](https://github.com/spring-projects/spring-security/issues/9991#issuecomment-871424452) rather than at startup. I think their faster startup times are due to something else.

> ... Follow this Spring Security issue to see when Spring Security adds lazy OIDC discovery support.

This ticket indeed combined with https://github.com/spring-projects/spring-boot/issues/28122 adds lazy OIDC discovery support. But your second experiment already disables OIDC discovery, so even with these changes your second chart will stay the same. 

IOW, after updating to Boot 2.6, your first chart and your second chart will be the same as [the current second chart](https://developer.okta.com/blog/2021/06/18/native-java-framework-comparison#spring-boot-init).

Is that what you would have expected? If not, we can reopen the ticket to take a second look.

FWIW, when I run the [Boot sample from the blog post](https://github.com/oktadev/native-java-examples), I can confirm that Boot already does the JWKS lookup on the first request rather than at startup. I confirmed this by deploying a [local authorization server](https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/oauth2/authorization-server) and watching the request logs.
