### ISSUE TITLE
Support @Transient SecurityContext and Provide TransientSecurityContext

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#9995]
We should add support for `@Transient SecurityContext` in `HttpSessionSecurityContextRepository` and then provide a `SecurityContext` that is annotated with `@Transient`

**Comment by aliaksei-astashenka** [comment]
Hi!
Have a question regarding this change. We ran into issues after upgrading to 5.7 version. Our current logic was like this:

1. First request being made with bearer JWT token to obtain html page for webview
2. All subsequent requests from that page (static resources and ajax calls) being made without JWT (because we don't have it there), but within the same session that has been opened in the point above (with JSESSIONID cookie), so those requests has been considered as authenticated

When upgrading to 5.7, point 2 is not working anymore, and we're getting UNAUTHORIZED, because in point 1 security context is not being saved into session repository, because of this part: 
```   
final Authentication authentication = context.getAuthentication();   
if (isTransient(authentication)) {
      return;   
}
```
in `org.springframework.security.web.context.HttpSessionSecurityContextRepository.SaveToSessionResponseWrapper#saveContext`, and our authentication object which is `org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken` marked with `@Transient` annotation.

So my question is, is this somehow expected behavior for 5.7? Because this is a little bit breaking change for us :) 

Thanks in advance!
